@startuml
[*] --> Usuario
Usuario : Estado del usuario
Usuario --> Alta : Dado de alta
Usuario --> NoAlta : No dado de alta
Alta : Usuario activo
NoAlta : Usuario inactivo
Alta --> Suspendido : Infracción
Suspendido --> Alta : Fin suspensión
Suspendido : Usuario suspendido indefinidamente

[*] --> Post
Alta --> Post: Crea
Suspendido -[dashed]-> Post: No puede crear
Post : Estado del post
Post --> Borrador : Creación inicial
Borrador --> Resuelto : Marcado como resuelto
Borrador --> NoResuelto : Marcado como no resuelto
Resuelto : Resuelto
NoResuelto : No resuelto
NoResuelto --> Resuelto : Marcar resuelto
Resuelto --> NoResuelto : Reabrir

[*] --> Comunidad
Comunidad : Estado de la comunidad
Comunidad --> Creada : Usuario crea
Creada : Comunidad nueva

state Creada {
  [*] --> SinMiembros
  SinMiembros --> ConMiembros : Usuarios se unen
  ConMiembros --> SinMiembros : Usuarios salen
  ConMiembros : Miembros > 0
  ConMiembros --> ConPosts : Miembros publican
  ConPosts --> ConMiembros : Posts eliminados
  ConPosts --> Post : Genera nuevo post
}

Creada --> BaneadaTemporal : Infracción
BaneadaTemporal : Comunidad suspendida
BaneadaTemporal --> Creada : Fin del ban

Creada --> BaneadaPermanente : Infracción grave
BaneadaPermanente : Comunidad cerrada
BaneadaPermanente --> [*] : Eliminación

@enduml
