@startuml

[*] --> Administrador: inicia sesión administrador

state Administrador {

  [*]-->Activo: gestionar Docutrace
  
  Activo --> GestionandoUsuarios
  GestionandoUsuarios --> GestionandoPermisos
  Activo --> GestionandoMensajes
  Activo --> GestionandoCategorias
  
  Activo --> Inactivo
  Inactivo --> Activo

}

@enduml