@startuml manejoDestinatarios
left to right direction
actor "Responsable" as Responsable

package "CRUD de Destinatarios" {
    usecase "Crear Destinatario" as CD1
    usecase "Ver Destinatario" as CD2
    usecase "Actualizar Destinatario" as CD3
    usecase "Borrar Destinatario" as CD4
}

Responsable --> CD1
Responsable --> CD2
Responsable --> CD3
Responsable --> CD4
@enduml
