@startuml ManejoUsuario
left to right direction
actor "Administrador General" as AdminGeneral
actor "Usuario" as Usuario

package "CRUD de Usuarios" {
    usecase "Crear Usuario" as CU1
    usecase "Ver Usuario" as CU2
    usecase "Actualizar Usuario" as CU3
    usecase "Borrar Usuario" as CU4
}

AdminGeneral --|> Usuario
Usuario --> CU1
Usuario --> CU2
Usuario --> CU3
Usuario --> CU4
@enduml
