@startuml
title Caso de uso: Revisar Test

skinparam {
    NoteBackgroundColor #lightYellow
    ArrowColor #blue
    NoteBorderColor #blue
    linetype polyline
}

state startState as "PÁGINA PRINCIPAL"
state endState as "PÁGINA PRINCIPAL"

startState --> VerTestCorregido
note on link
    <b>Usuario Accede</b>
    * Selecciona un test de la lista corregida
end note

VerTestCorregido --> MostrarFeedback
note on link
    <b>Sistema Muestra</b>
    * Respuestas correctas e incorrectas
    * Puntuación final
end note

MostrarFeedback --> endState
note on link
    <b>Usuario Termina</b>
    * Regresa a la página principal
end note
@enduml
