@startuml
title Casos de Uso (Postulante) - Capacitación, Test y Progreso

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

left to right direction

actor Postulante

folder "Capacitación" as capacitacion {
    Postulante --> (Realizar Capacitación)
    Postulante --> (Consultar Disponibilidad de Capacitación)
    Postulante --> (Ver Progreso de Capacitación)
}

folder "Test" as test {
    Postulante --> (Realizar Test)
    Postulante --> (Consultar Resultados del Test)
    Postulante --> (Ver Test Corregido)
}

@enduml
