@startuml


actor "User" as User
actor "Admin" as Admin
actor "Time" as Time
Admin -u-|> User

package "Sistema Gestión de Usuarios" {
    usecase "Crear Usuario" as UCU1
    usecase "Activar Usuario" as UCU2
    usecase "Suspender Usuario" as UCU3
    usecase "Reactivar Usuario" as UCU4
    usecase "Desactivar Usuario" as UCU5
    usecase "Consultar Usuario" as UCU6
    usecase "Editar Usuario" as UCU7
}

package "Sistema Gestión Pruebas" {
    usecase "Crear Prueba" as UCU8
    usecase "Consultar Prueba" as UCU9
    usecase "Revisar Estadisticas" as UCU10
    usecase "Desactivar Prueba" as UCU11
    usecase "Ver Prueba Corregida" as UCU12
    usecase "Realizar Prueba" as UCU13
}

package "Sistema de Capacitación" {
    usecase "Crear Capacitacion" as UCU14
    usecase "Consultar Capacitacion" as UCU15
    usecase "Revisar Estadisticas" as UCU10
}

Admin --> UCU1
Admin --> UCU2
Admin --> UCU3
Admin --> UCU4
Admin --> UCU5
Admin --> UCU6
Admin --> UCU7
Admin --> UCU14
Admin --> UCU15
Admin --> UCU8
Admin --> UCU9
Admin --> UCU10
Admin --> UCU11
Admin --> UCU12

User --> UCU13
User --> UCU12
User --> UCU7

@enduml