@startuml
actor Administrador
actor Seleccionador
participant "Interfaz de Usuario" as UI
participant "Sistema de Gestión de Capacitación" as Sistema
participant "Base de Datos de Capacitación" as BD

== Consultar Progreso y Resultados ==
Administrador -> UI: Solicitar consulta de resultados de capacitación
Seleccionador -> UI: Solicitar consulta de resultados de capacitación
UI -> Sistema: Solicitar datos de progreso y resultados del becario
Sistema -> BD: Consultar progreso y resultados de capacitación
BD -> Sistema: Enviar datos de progreso y resultados
Sistema -> UI: Enviar resultados a la interfaz
UI -> Administrador: Mostrar resultados de capacitación
UI -> Seleccionador: Mostrar resultados de capacitación
@enduml
