@startuml
actor Administrador
participant "Interfaz de Usuario" as UI
participant "Sistema de Gestión de Estadísticas" as Sistema
participant "Base de Datos de Usuarios y Pruebas" as BD

Administrador -> UI: Seleccionar tipo de reporte o estadísticas a generar
UI -> Sistema: Solicitar generación de reporte estadístico
Sistema -> BD: Consultar datos de desempeño de los becarios
BD -> Sistema: Devolver datos de desempeño
Sistema -> UI: Enviar reporte generado
UI -> Administrador: Mostrar reporte estadístico
@enduml
