@startuml

actor "Usuario No Registrado" as UsuarioNoRegistrado
actor Usuario
actor Profesor
actor Alumno
actor Admin

UsuarioNoRegistrado <|-- Usuario : necesita registrarse para ser Usuario
Usuario <|-- Alumno : rol de Alumno
Usuario <|-- Profesor : rol de Profesor
Usuario <|-- Admin : rol de Admin

Admin <|-- Profesor : tiene permisos avanzados
Admin <|-- Alumno : acceso limitado en comparación al Admin

note right of UsuarioNoRegistrado
  **Usuario No Registrado**: 
  Debe registrarse para acceder a 
  cualquier funcionalidad del sistema.
end note

note right of Usuario
  **Usuario**: 
  Representa a cualquier usuario del sistema
  con roles específicos como Alumno, Profesor o Admin.
end note

note right of Alumno
  **Alumno**: 
  Puede usar la aplicación y 
  seguir las rutinas asignadas.
end note

note right of Profesor
  **Profesor**: 
  Puede controlar a sus alumnos 
  y añadir rutinas y objetivos.
end note

note right of Admin
  **Admin**: 
  Tiene control total del sistema,
  incluyendo la gestión de usuarios y 
  la administración de contenidos.
end note

@enduml
