@startuml
left to right direction

package "Sistema Académico" {
    usecase "Introducir Datos Académicos" as UC1
    usecase "Consultar Datos Personales y Contrato" as UC2
    usecase "Consultar Asignación Docente" as UC3
    usecase "Validar Datos del Profesorado" as UC4
    usecase "Modificar Datos del Profesorado" as UC5
    usecase "Introducir Datos Laborales" as UC6
    usecase "Revisar Carga Docente" as UC7
    usecase "Consultar Claustro Docente" as UC8
    usecase "Consultar Asignación por Profesor" as UC9
    usecase "Validar Memoria y Titulación" as UC10
    usecase "Asignar Carga Docente" as UC11
    usecase "Asignar Valores de Memoria" as UC12
    usecase "Asignar Información a SIIU/DGU" as UC13
    usecase "Obtener Indicadores" as UC14
    usecase "Emitir Informe del Profesorado" as UC15
}

@enduml
