@startuml
left to right direction
actor Ordenacion
package "Sistema Académico" {
    usecase "Revisar listado de Profesores cuya Carga Docente no se ajusta al Contrato" as RevisarCarga
    usecase "Consultar Claustro Docente (listado PDI asociado a una titulación)" as ConsultarClaustro
    usecase "Consultar Asignacion Docente por profesor" as ConsultarAsignacion
    usecase "Validar cumplimiento de compromisos de memoria" as ValidarCumplimiento
    usecase "Asignar Carga Docente de Asignaturas a Profesores" as AsignarCarga
}
Ordenacion --> RevisarCarga
Ordenacion --> ConsultarClaustro
Ordenacion --> AsignarCarga
Ordenacion --> ValidarCumplimiento
Ordenacion --> ConsultarAsignacion
@enduml