@startuml

hide empty members
hide circle

class Profesor
class DatosAcademicos
class DatosLaborales
class AsignacionDocente
class CargaDocente
class Memoria
class Informe
class Indicadores
class RRHH
class Ordenacion
class TecnicoCalidad
class ClaustroDocente

Profesor --> DatosAcademicos : introduce
Profesor --> AsignacionDocente : consulta
Profesor --> DatosLaborales : consulta

RRHH --> DatosLaborales : introduce
RRHH --> DatosAcademicos : valida/modifica
RRHH --> CargaDocente : revisa
RRHH --> ClaustroDocente : consulta
RRHH --> AsignacionDocente : consulta

Ordenacion --> CargaDocente : revisa/asigna
Ordenacion --> Memoria : valida
Ordenacion --> ClaustroDocente : consulta
Ordenacion --> AsignacionDocente : consulta

TecnicoCalidad --> Memoria : valida/asigna
TecnicoCalidad --> Indicadores : obtiene
TecnicoCalidad --> Informe : emite
TecnicoCalidad --> ClaustroDocente : consulta
TecnicoCalidad --> AsignacionDocente : consulta

CargaDocente --> AsignacionDocente : define
Memoria --> CargaDocente : establece_límites
DatosAcademicos --> Indicadores : proporciona_métricas
DatosLaborales --> CargaDocente : condiciona

@enduml
