@startuml
hide empty description

[*] --> Inscrito : alumno se inscribe en la asignatura
Inscrito --> EnClaseTeorica : estudia la teoría
Inscrito --> EnClasePractica : realiza las prácticas
EnClaseTeorica --> EvaluacionFinal : se evalúa su trabajo
EnClasePractica --> EvaluacionFinal 

EvaluacionFinal --> Aprobado : supera ambas partes
EvaluacionFinal --> Suspendido : no supera ambas partes

Aprobado --> FinDelCurso : supera la asignatura
Suspendido --> FinDelCurso : no supera la asignatura
FinDelCurso --> [*] : termina el curso

@enduml
