@startuml

hide empty description

[*] --> Inscrito : alumno se inscribe en la asignatura
Inscrito --> EnClaseTeorica : asiste a clases teóricas
Inscrito --> EnClasePractica : asiste a clases prácticas

EnClaseTeorica --> ValoracionFinal : se le evalúa
EnClasePractica --> RutinaAsignada : se le enseña una rutina

RutinaAsignada --> RutinaCompletada : completa la rutina
RutinaCompletada --> ValoracionFinal : se le evalúa

ValoracionFinal --> FinDelCurso : finaliza la asignatura

FinDelCurso --> [*] : termina el curso

@enduml
