@startuml
left to right direction

actor "User" as User
actor "Admin" as Admin
actor "Time" as Time
actor "Seleccionador" as Seleccionador
Admin -u-|> User
Seleccionador -u-|> User


package "Sistema Gestión de Usuarios" {
    usecase "Crear Usuario" as UCU1
    usecase "Activar Usuario" as UCU2
    usecase "Suspender Usuario" as UCU3
    usecase "Reactivar Usuario" as UCU4
    usecase "Desactivar Usuario" as UCU5
    usecase "Consultar Usuario" as UCU6
}

package "Sistema Gestión Pruebas" {
    usecase "Crear Prueba" as UCU7
    usecase "Consultar Prueba" as UCU8
    usecase "Revisar Estadisticas" as UCU9
    usecase "Crear estadisticas" as UCU10
    usecase "Desactivar Prueba" as UCU11
}

package "Sistema de Capacitación" {
    usecase "Crear Capacitacion" as UCU12
    usecase "Consultar Capacitacion" as UCU13
    usecase "Revisar Estadisticas" as UCU14
    usecase "Crear estadisticas" as UCU15
}
@enduml