@startuml
actor "Destinatario" as Destinatario
actor "Gestor" as Usuario
actor "Administrador" as Administrador

Destinatario --|> Usuario : Puede crear destinatarios y enviar documentos
Usuario --|> Administrador : Puede crear gestores y destinatarios, y enviar documentos

note right of Administrador
    Puede hacer todo lo que hace un Gestor
    más las acciones de administración de usuarios
end note

note right of Usuario
    Puede hacer todo lo que hace un Destinatario
    más las acciones de envío de documentos
end note
@enduml
