@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(CONSULTAR_RETOS)
' Subfunciones de "Retos"
RECTANGLE(CREAR_RETO) 
RECTANGLE(MODIFICAR_RETO) 
RECTANGLE(ELIMINAR_RETO) 

' Submenús de "Retos"
CONSULTAR_RETOS --> CREAR_RETO : Crear Retos
CREAR_RETO --> CONSULTAR_RETOS : Ir al menú Retos

CONSULTAR_RETOS --> MODIFICAR_RETO : Modificar Retos
MODIFICAR_RETO --> CONSULTAR_RETOS : Ir al menú Retos

CONSULTAR_RETOS --> ELIMINAR_RETO : Eliminar Retos
ELIMINAR_RETO --> CONSULTAR_RETOS : Ir al menú Retos
@enduml