@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(CONSULTAR_REPORTES)

' Subfunciones de "Reportes"
RECTANGLE(CONSULTAR_REPORTES_DETALLADOS) 
RECTANGLE(DESCARGAR_ESTADISTICAS) 

' Submenús de "Reportes"
CONSULTAR_REPORTES --> CONSULTAR_REPORTES_DETALLADOS : Consultar Reportes Detallados
CONSULTAR_REPORTES_DETALLADOS --> CONSULTAR_REPORTES : Ir al menú Reportes

CONSULTAR_REPORTES --> DESCARGAR_ESTADISTICAS : Descargar Estadísticas
DESCARGAR_ESTADISTICAS --> CONSULTAR_REPORTES : Ir al menú Reportes

@enduml