@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_REPORTES) #LightCoral
RECTANGLE(NAVEGACION_MENUS) #SkyBlue


' Subfunciones de "Reportes"
RECTANGLE(CONSULTANDO_REPORTES_DETALLADOS) #LightCoral
RECTANGLE(DESCARGANDO_ESTADISTICAS) #LightCoral

' Submenús de "Reportes"
MENU_REPORTES -[#LightCoral]-> CONSULTANDO_REPORTES_DETALLADOS : Consultar Reportes Detallados
CONSULTANDO_REPORTES_DETALLADOS -[#SkyBlue]-> NAVEGACION_MENUS :  Cambiar Menú

MENU_REPORTES -[#LightCoral]-> DESCARGANDO_ESTADISTICAS : Descargar Estadísticas
DESCARGANDO_ESTADISTICAS -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar Menú

@enduml