@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_RUTINAS) #PaleGreen

' Subfunciones de "Rutinas"
RECTANGLE(CREANDO_RUTINA) #PaleGreen
RECTANGLE(MODIFICANDO_RUTINA) #PaleGreen
RECTANGLE(ELIMINANDO_RUTINA) #PaleGreen
RECTANGLE(BATERIA_EJERCICIOS) #PaleGreen
RECTANGLE(NAVEGACION_MENUS) #SkyBlue


' Submenús de "Rutinas"
MENU_RUTINAS -[#PaleGreen]-> CREANDO_RUTINA : Crear Rutinas
CREANDO_RUTINA -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar Menú

MENU_RUTINAS -[#PaleGreen]-> MODIFICANDO_RUTINA : Modificar Rutinas
MODIFICANDO_RUTINA -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar Menú

MENU_RUTINAS -[#PaleGreen]-> ELIMINANDO_RUTINA : Eliminar Rutinas
ELIMINANDO_RUTINA -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar Menú

MENU_RUTINAS -[#PaleGreen]-> BATERIA_EJERCICIOS : Modificar Batería de Ejercicios
BATERIA_EJERCICIOS -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar Menú

@enduml