@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_RETOS)#LightSalmon
' Subfunciones de "Retos"
RECTANGLE(CREANDO_RETO)#LightSalmon
RECTANGLE(MODIFICANDO_RETO)#LightSalmon
RECTANGLE(ELIMINANDO_RETO)#LightSalmon
RECTANGLE(NAVEGACION_MENUS) #SkyBlue


' Submenús de "Retos"
MENU_RETOS -[#LightSalmon]-> CREANDO_RETO : Crear Retos
CREANDO_RETO -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar Menú

MENU_RETOS -[#LightSalmon]-> MODIFICANDO_RETO : Modificar Retos
MODIFICANDO_RETO -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar Menú

MENU_RETOS -[#LightSalmon]-> ELIMINANDO_RETO : Eliminar Retos
ELIMINANDO_RETO -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar Menú
@enduml