@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(CONSULTAR_CONFIGURACION)

' Subfunciones de "Configuración"
RECTANGLE(CONFIGURAR_SISTEMA) 
RECTANGLE(ADMINISTRAR_PERMISOS) 
RECTANGLE(AJUSTES_GENERALES) 

' Submenús de "Configuración"
CONSULTAR_CONFIGURACION --> CONFIGURAR_SISTEMA : Configurar Sistema
CONFIGURAR_SISTEMA --> CONSULTAR_CONFIGURACION : Ir al menú Configuración

CONSULTAR_CONFIGURACION --> ADMINISTRAR_PERMISOS : Administrar Permisos
ADMINISTRAR_PERMISOS --> CONSULTAR_CONFIGURACION : Ir al menú Configuración

CONSULTAR_CONFIGURACION --> AJUSTES_GENERALES : Ajustes Generales
AJUSTES_GENERALES --> CONSULTAR_CONFIGURACION : Ir al menú Configuración
@enduml