@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(CONSULTAR_RUTINAS)

' Subfunciones de "Rutinas"
RECTANGLE(CREAR_RUTINA) 
RECTANGLE(MODIFICAR_RUTINA) 
RECTANGLE(ELIMINAR_RUTINA) 
RECTANGLE(BATERIA_EJERCICIOS) 

' Submenús de "Rutinas"
CONSULTAR_RUTINAS --> CREAR_RUTINA : Crear Rutinas
CREAR_RUTINA --> CONSULTAR_RUTINAS : Ir al menú Rutinas

CONSULTAR_RUTINAS --> MODIFICAR_RUTINA : Modificar Rutinas
MODIFICAR_RUTINA --> CONSULTAR_RUTINAS : Ir al menú Rutinas

CONSULTAR_RUTINAS --> ELIMINAR_RUTINA : Eliminar Rutinas
ELIMINAR_RUTINA --> CONSULTAR_RUTINAS : Ir al menú Rutinas

CONSULTAR_RUTINAS --> BATERIA_EJERCICIOS : Modificar Batería de Ejercicios
BATERIA_EJERCICIOS --> CONSULTAR_RUTINAS : Ir al menú Rutinas

@enduml