@startuml
!define RECTANGLE(x) rectangle x

!define COLOR_USUARIOS #LightBlue

RECTANGLE(MENU_CONFIGURACION) #Gold
RECTANGLE(NAVEGACION_MENUS) #SkyBlue


' Subfunciones de "Configuración"
RECTANGLE(CONFIGURANDO_SISTEMA) #Gold
RECTANGLE(ADMINISTRANDO_PERMISOS) #Gold
RECTANGLE(AJUSTES_GENERALES) #Gold

' Submenús de "Configuración"
MENU_CONFIGURACION -[#Gold]-> CONFIGURANDO_SISTEMA : Configurar Sistema
CONFIGURANDO_SISTEMA -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú

MENU_CONFIGURACION -[#Gold]-> ADMINISTRANDO_PERMISOS : Administrar Permisos
ADMINISTRANDO_PERMISOS -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú

MENU_CONFIGURACION -[#Gold]-> AJUSTES_GENERALES : Ajustes Generales
AJUSTES_GENERALES -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
@enduml