@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_USUARIOS) #Yellow
' Subfunciones de "Usuarios"
RECTANGLE(CREANDO_USUARIO) #Yellow
RECTANGLE(MODIFICANDO_USUARIO) #Yellow
RECTANGLE(ELIMINANDO_USUARIO) #Yellow
RECTANGLE(NAVEGACION_MENUS) #SkyBlue


MENU_USUARIOS -[#Yellow]-> CREANDO_USUARIO : Crear Usuarios
CREANDO_USUARIO -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar Menú

MENU_USUARIOS -[#Yellow]-> MODIFICANDO_USUARIO : Modificar Usuarios
MODIFICANDO_USUARIO -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar Menú

MENU_USUARIOS -[#Yellow]-> ELIMINANDO_USUARIO : Eliminar Usuarios
ELIMINANDO_USUARIO -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar Menú

@enduml