@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(ADMINISTRADOR)
RECTANGLE(MENU_PRINCIPAL)
RECTANGLE(MENU_CLASE)
RECTANGLE(MENU_RUTINAS)
RECTANGLE(MENU_RETOS)

' Relación entre el Administrador y el Menú Principal
ADMINISTRADOR --> MENU_PRINCIPAL : Iniciar Sesión

' Funciones del Administrador desde el Menú Principal
MENU_PRINCIPAL --> ADMINISTRADOR : Cerrar Sesión
MENU_PRINCIPAL --> MENU_CLASE : Acceder a Clases
MENU_PRINCIPAL --> MENU_RUTINAS : Usar Rutinas
MENU_PRINCIPAL --> MENU_RETOS : Participar en Retos/Actividades
MENU_PRINCIPAL --> MENU_PRINCIPAL : Administrar Usuarios
MENU_PRINCIPAL --> MENU_PRINCIPAL : Configurar Sistema
MENU_RETOS --> MENU_PRINCIPAL : Volver al inicio
MENU_RUTINAS --> MENU_PRINCIPAL : Volver al inicio
MENU_CLASE --> MENU_PRINCIPAL : Volver al inicio



@enduml
