@startuml AlumnosCasosDeUso
!define RECTANGLE(x) rectangle x

RECTANGLE(ALUMNOS)
RECTANGLE(PAGINA_PRINCIPAL)
RECTANGLE(MENU_RUTINAS)
RECTANGLE(MENU_RETOS)
RECTANGLE(MENU_CLASIFICACION)
RECTANGLE(MENU_PERFIL)
RECTANGLE(INSIGNIAS)
RECTANGLE(INSCRIPCION_CLASE)
RECTANGLE(QR_CENTROS_DEPORTIVOS)
RECTANGLE(RETOS_OBLIGATORIOS)
RECTANGLE(RETOS_OPCIONALES)

ALUMNOS --> PAGINA_PRINCIPAL : Iniciar Sesión
PAGINA_PRINCIPAL --> ALUMNOS : Cerrar Sesión

PAGINA_PRINCIPAL --> MENU_RUTINAS : Usar Rutinas
PAGINA_PRINCIPAL --> MENU_RETOS : Participar en Retos/Actividades
PAGINA_PRINCIPAL --> MENU_CLASIFICACION : Ver Clasificaciones
PAGINA_PRINCIPAL --> MENU_PERFIL : Consultar Perfil

MENU_PERFIL --> INSIGNIAS : Ver Insignias Conseguida
MENU_PERFIL --> INSCRIPCION_CLASE : Inscribirse en Clases
MENU_PERFIL --> QR_CENTROS_DEPORTIVOS : Utilizar QR para Centros Deportivos

MENU_RETOS --> RETOS_OBLIGATORIOS : Completar Retos Obligatorios
MENU_RETOS --> RETOS_OPCIONALES : Completar Retos Opcionales
RETOS_OBLIGATORIOS --> MENU_RETOS : Volver al Menú Retos
RETOS_OPCIONALES --> MENU_RETOS : Volver al Menú Retos

MENU_RUTINAS --> PAGINA_PRINCIPAL : Volver página principal
MENU_RETOS --> PAGINA_PRINCIPAL : Volver página principal
MENU_CLASIFICACION --> PAGINA_PRINCIPAL : Volver página principal
MENU_PERFIL --> PAGINA_PRINCIPAL : Volver página principal

INSIGNIAS --> MENU_PERFIL : Volver al Perfil
INSCRIPCION_CLASE --> MENU_PERFIL : Volver al Perfil
QR_CENTROS_DEPORTIVOS --> MENU_PERFIL : Volver al Perfil

@enduml
