@startuml AlumnosCasosDeUso
!define RECTANGLE(x) rectangle x

RECTANGLE(ALUMNO)
RECTANGLE(AUTENTICANDO)
RECTANGLE(PAGINA_PRINCIPAL)
RECTANGLE(MENU_RUTINAS)
RECTANGLE(MENU_RETOS)
RECTANGLE(MENU_CLASIFICACION)
RECTANGLE(MENU_PERFIL)
RECTANGLE(INSIGNIA)
RECTANGLE(INSCRIPCION_CLASE)
RECTANGLE(ESCANEANDO_QR)

RECTANGLE(ACTUALIZANDO_RETO)
RECTANGLE(CREANDO_RUTINA)
RECTANGLE(ACTIVIDAD)

ALUMNO --> AUTENTICANDO : Autenticación
AUTENTICANDO --> PAGINA_PRINCIPAL : Ingresar al sistema
PAGINA_PRINCIPAL --> ALUMNO : Cerrar Sesión

PAGINA_PRINCIPAL --> MENU_RUTINAS : Usando rutina
PAGINA_PRINCIPAL --> MENU_RETOS : Participando en retos/actividades
PAGINA_PRINCIPAL --> MENU_CLASIFICACION : Consultando clasificación
PAGINA_PRINCIPAL --> MENU_PERFIL : Revisando perfil

MENU_PERFIL --> INSIGNIA : Observando insignia
MENU_PERFIL --> INSCRIPCION_CLASE : Inscribiéndose en clase
MENU_PERFIL --> ESCANEANDO_QR : Usando QR en centro deportivo

MENU_RETOS --> ACTUALIZANDO_RETO : Cambiando estado reto



ACTUALIZANDO_RETO --> MENU_RETOS : Volviendo al menú retos
ACTIVIDAD --> MENU_RETOS : Volviendo al menú retos

MENU_RUTINAS --> CREANDO_RUTINA : Creando rutina
CREANDO_RUTINA --> MENU_RUTINAS : Volviendo al menú rutinas

MENU_RUTINAS --> PAGINA_PRINCIPAL : Volviendo a página principal
MENU_RETOS --> PAGINA_PRINCIPAL : Volviendo a página principal
MENU_CLASIFICACION --> PAGINA_PRINCIPAL : Volviendo a página principal
MENU_PERFIL --> PAGINA_PRINCIPAL : Volviendo a página principal

INSIGNIA --> MENU_PERFIL : Volviendo al perfil
INSCRIPCION_CLASE --> MENU_PERFIL : Volviendo al perfil
ESCANEANDO_QR --> MENU_PERFIL : Volviendo al perfil
@enduml
