@startuml ProfesorCasosDeUso
!define RECTANGLE(x) rectangle x

RECTANGLE(PROFESOR)
RECTANGLE(AUTENTICANDO)
RECTANGLE(PAGINA_PRINCIPAL)
RECTANGLE(MENU_RUTINAS_EJERCICIOS)
RECTANGLE(MENU_RETOS)
RECTANGLE(MENU_CLASIFICACION)
RECTANGLE(MENU_PERFIL)
RECTANGLE(CREANDO_RUTINA)
RECTANGLE(CREANDO_EJERCICIO)
RECTANGLE(EDITANDO_RUTINA)
RECTANGLE(EDITANDO_EJERCICIO)
RECTANGLE(CREANDO_RETOS)
RECTANGLE(EDITANDO_RETOS)
RECTANGLE(VIENDO_CLASES)
RECTANGLE(VIENDO_ALUMNOS_CLASE)
RECTANGLE(CREANDO_CLASE)
RECTANGLE(MOSTRANDO_QR)
RECTANGLE(VIENDO_MIS_CLASES)
RECTANGLE(VIENDO_ALUMNOS)
RECTANGLE(VIENDO_RETOS_ALUMNOS)
RECTANGLE(EVALUANDO_RETOS)


PROFESOR --> AUTENTICANDO : Autenticación
AUTENTICANDO --> PAGINA_PRINCIPAL : Ingresar al sistema

PAGINA_PRINCIPAL --> MENU_RUTINAS_EJERCICIOS : Gestionando rutinas y ejercicios
PAGINA_PRINCIPAL --> MENU_RETOS : Gestionando retos
PAGINA_PRINCIPAL --> MENU_CLASIFICACION : Consultando clasificación
PAGINA_PRINCIPAL --> MENU_PERFIL : Revisando perfil

MENU_RUTINAS_EJERCICIOS --> CREANDO_RUTINA : Creando rutina
MENU_RUTINAS_EJERCICIOS --> CREANDO_EJERCICIO : Creando ejercicio
MENU_RUTINAS_EJERCICIOS --> EDITANDO_RUTINA : Editando rutina
MENU_RUTINAS_EJERCICIOS --> EDITANDO_EJERCICIO : Editando ejercicio

CREANDO_RUTINA --> MENU_RUTINAS_EJERCICIOS : Volviendo al menú rutinas y ejercicios
CREANDO_EJERCICIO --> MENU_RUTINAS_EJERCICIOS : Volviendo al menú rutinas y ejercicios
EDITANDO_RUTINA --> MENU_RUTINAS_EJERCICIOS : Volviendo al menú rutinas y ejercicios
EDITANDO_EJERCICIO --> MENU_RUTINAS_EJERCICIOS : Volviendo al menú rutinas y ejercicios

MENU_RETOS --> CREANDO_RETOS : Creando retos
MENU_RETOS --> EDITANDO_RETOS : Editando retos
CREANDO_RETOS --> MENU_RETOS : Volviendo al menú retos
EDITANDO_RETOS --> MENU_RETOS : Volviendo al menú retos

MENU_CLASIFICACION --> VIENDO_CLASES : Viendo clases
VIENDO_CLASES --> VIENDO_ALUMNOS_CLASE : Viendo alumnos dentro de clases
VIENDO_ALUMNOS_CLASE --> MENU_CLASIFICACION : Volviendo al menú clasificación
VIENDO_CLASES --> MENU_CLASIFICACION : Volviendo al menú clasificación

MENU_PERFIL --> CREANDO_CLASE : Creando clase
MENU_PERFIL --> MOSTRANDO_QR : Mostrando QR en centro deportivo
MENU_PERFIL --> VIENDO_MIS_CLASES : Viendo mis clases
MENU_PERFIL --> PROFESOR : Cerrando sesión

VIENDO_MIS_CLASES --> VIENDO_ALUMNOS : Viendo alumnos
VIENDO_ALUMNOS --> VIENDO_RETOS_ALUMNOS : Viendo retos alumnos
VIENDO_RETOS_ALUMNOS --> EVALUANDO_RETOS : Evaluando/calificando retos
EVALUANDO_RETOS --> VIENDO_RETOS_ALUMNOS : Volviendo a retos alumnos
VIENDO_RETOS_ALUMNOS --> VIENDO_ALUMNOS : Volviendo a alumnos
VIENDO_ALUMNOS --> VIENDO_MIS_CLASES : Volviendo a mis clases

CREANDO_CLASE --> MENU_PERFIL : Volviendo al perfil
MOSTRANDO_QR --> MENU_PERFIL : Volviendo al perfil
MENU_RUTINAS_EJERCICIOS --> PAGINA_PRINCIPAL : Volviendo a página principal
MENU_RETOS --> PAGINA_PRINCIPAL : Volviendo a página principal
MENU_CLASIFICACION --> PAGINA_PRINCIPAL : Volviendo a página principal
MENU_PERFIL --> PAGINA_PRINCIPAL : Volviendo a página principal
@enduml
