@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(PROFESOR)
RECTANGLE(MENU_PRINCIPAL)
RECTANGLE(MENU_CLASE)
RECTANGLE(MENU_RUTINAS)
RECTANGLE(MENU_ASIGNATURA)
RECTANGLE(MENU_RETOS)

PROFESOR --> MENU_PRINCIPAL : Iniciar Sesión
MENU_PRINCIPAL --> PROFESOR : Cerrar Sesión
MENU_PRINCIPAL --> MENU_ASIGNATURA : Publicar Información de Asignatura
MENU_PRINCIPAL --> MENU_RUTINAS : Gestionar Rutinas
MENU_PRINCIPAL --> MENU_RETOS : Publicar Retos/Actividades
MENU_PRINCIPAL --> MENU_CLASE : Acceder a Clases
MENU_PRINCIPAL --> MENU_PRINCIPAL : Administrar Alumnos/Rutias/Retos

MENU_CLASE --> MENU_ASIGNATURA : Impartir Asignatura
MENU_CLASE --> MENU_CLASE : Gestionar Alumnos
MENU_CLASE --> MENU_ASIGNATURA : Calificar Alumnos

MENU_RUTINAS --> MENU_RUTINAS : Asignar Rutinas

MENU_RETOS --> MENU_RETOS : Validar Retos

MENU_RETOS --> MENU_PRINCIPAL : Volver al inicio
MENU_RUTINAS --> MENU_PRINCIPAL : Volver al inicio
MENU_CLASE --> MENU_PRINCIPAL : Volver al inicio
MENU_ASIGNATURA --> MENU_PRINCIPAL : Volver al inicio

@enduml
