@startuml
title Casos de Uso (Usuario) - Actualización de Datos

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

left to right direction

actor Usuario

folder "Gestión de Usuario" as usuario {
    Usuario --> (Actualizar Datos de Usuario)
}

@enduml
