@startuml diagramaContextoProfesor  
state "NO_AUTENTICADO" as NoAutenticado
state "MENU_PRINCIPAL" as MenuPrincipal  
state "EDITANDO_GUÍA" as EditandoGuia  
state "VISUALIZANDO_GUÍA" as VisualizandoGuia  
state "ENVIANDO_GUÍA" as EnviandoGuia  

[*] --> NoAutenticado   
    
NoAutenticado --> MenuPrincipal
note on link  
        iniciar sesión  
    end note  

MenuPrincipal -> [*]  
    note on link  
        cerrar sesión  
    end note  

MenuPrincipal --> VisualizandoGuia  
    note on link  
        Visualizar guías asignadas  
        para consulta  
    end note  

VisualizandoGuia --> MenuPrincipal  
    note on link  
        Regresar al menú principal  
    end note  

MenuPrincipal --> EditandoGuia  
    note on link  
        Acceder a guías asignadas  
        para edición  
    end note  

EditandoGuia --> EditandoGuia  
    note on link  
        Ajustar contenido editable  
    end note  

EditandoGuia --> EnviandoGuia  
    note on link  
        Finalizar edición y enviar guía  
        al Director de Grado  
    end note  

EnviandoGuia --> MenuPrincipal  
    note on link  
        Confirmar envío y regresar  
        al menú principal  
    end note  

@enduml  
