@startuml diagramaContextoGuiasDocentes

state "MENU_PRINCIPAL" as MenuPrincipal
state "EDITAR_CONTENIDO" as EditarContenido
state "REVISAR_CONTENIDO" as RevisarContenido
state "APROBAR_CONTENIDO" as AprobarContenido
state "PUBLICAR_GUIA" as PublicarGuia
state "AUDITAR_GUIA" as AuditarGuia
state "GENERAR_VERSION" as GenerarVersion
state "ASIGNAR_GUIA_TITULACION" as AsignarGuiaTitulacion
state "ASIGNAR_ASIGNATURA_TITULACION" as AsignarAsignaturaTitulacion
state "SUPERVISAR_GUIAS" as SupervisarGuias
state "VERIFICAR_MEMORIA" as VerificarMemoria

[*] ----> MenuPrincipal
    note on link
        Actor accede al sistema
    end note

MenuPrincipal --> [*]
    note on link
        Cierra sesión
    end note

MenuPrincipal -> EditarContenido
    note on link
        Técnico de Calidad: Editar contenido
    end note

EditarContenido ----> MenuPrincipal
    note on link
        Guardar cambios
    end note

MenuPrincipal ----> RevisarContenido
    note on link
        Director de Grado: Revisar contenido
    end note

RevisarContenido ----> AprobarContenido
    note on link
        Aprobar o rechazar contenido
    end note

AprobarContenido ----> MenuPrincipal
    note on link
        Confirmar aprobación o rechazo
    end note

MenuPrincipal ----> PublicarGuia
    note on link
        Director de Grado: Publicar guía docente
    end note

PublicarGuia ----> MenuPrincipal
    note on link
        Confirmar publicación
    end note

MenuPrincipal ----> AuditarGuia
    note on link
        Dirección de Calidad: Auditar guías
    end note

AuditarGuia ----> MenuPrincipal
    note on link
        Finalizar auditoría
    end note

MenuPrincipal ----> GenerarVersion
    note on link
        Técnico de Calidad: Generar nueva versión
    end note

GenerarVersion ----> MenuPrincipal
    note on link
        Confirmar generación
    end note

MenuPrincipal ----> AsignarGuiaTitulacion
    note on link
        Técnico de Calidad: Asignar guía a titulación
    end note

AsignarGuiaTitulacion ----> MenuPrincipal
    note on link
        Confirmar asignación
    end note

MenuPrincipal ----> AsignarAsignaturaTitulacion
    note on link
        Técnico de Calidad: Asignar asignatura a titulación
    end note

AsignarAsignaturaTitulacion ----> MenuPrincipal
    note on link
        Confirmar asignación
    end note

MenuPrincipal ----> SupervisarGuias
    note on link
        Técnico de Calidad: Supervisar guías
    end note

SupervisarGuias ----> MenuPrincipal
    note on link
        Finalizar supervisión
    end note

MenuPrincipal ----> VerificarMemoria
    note on link
        Dirección de Calidad: Verificar cumplimiento con memoria
    end note

VerificarMemoria ----> MenuPrincipal
    note on link
        Confirmar verificación
    end note

@enduml
