@startuml
[*] --> INICIANDO_SESION
    note on link
        Iniciar sesión
    end note
INICIANDO_SESION --> MENU_PRINCIPAL
    note on link
        Ver menu
    end note
MENU_PRINCIPAL --> ASIGNANDO_ASIGNATURA
    note on link
        Asignar asignatura
    end note
ASIGNANDO_ASIGNATURA --> MENU_PRINCIPAL
    note on link
        Ver menu
    end note
MENU_PRINCIPAL --> ASIGNANDO_PROFESOR
    note on link
        Asignar profesor
    end note
ASIGNANDO_PROFESOR --> MENU_PRINCIPAL
    note on link
        Ver menu
    end note

MENU_PRINCIPAL --> BUSCANDO_GRADO
    note on link
        Buscar grado
    end note

BUSCANDO_GRADO --> MENU_PRINCIPAL
    note on link
        Ver menu
    end note

MENU_PRINCIPAL --> CONSULTANDO_HORARIO_PROFESOR
    note on link
        Consultar 
        horario profesor
    end note

CONSULTANDO_HORARIO_PROFESOR --> MENU_PRINCIPAL
    note on link
        Ver menu
    end note

MENU_PRINCIPAL --> EDITANDO_ASIGNACION
    note on link
        Editar asignación
    end note

EDITANDO_ASIGNACION --> MENU_PRINCIPAL
    note on link
        Ver menu
    end note
MENU_PRINCIPAL --> MOSTRANDO_ASIGNATURAS
    note on link
        Mostrar asignaturas
    end note

MOSTRANDO_ASIGNATURAS --> MENU_PRINCIPAL
    note on link
        Ver menu
    end note
MENU_PRINCIPAL --> REGISTRANDO_ASIGNATURA
    note on link
        Registrar asignatura
    end note

REGISTRANDO_ASIGNATURA --> MENU_PRINCIPAL
    note on link
        Ver menu
    end note

MENU_PRINCIPAL --> VIENDO_DISPONIBILIDAD_AULAS
    note on link
        Ver disponibilidad 
        de aulas
    end note

VIENDO_DISPONIBILIDAD_AULAS --> MENU_PRINCIPAL
    note on link
        Ver menu
    end note

MENU_PRINCIPAL --> [*] 
@enduml