@startuml diagramaContextoDirectorCalidad

state "USUARIO" as Usuario
state "MENU_PRINCIPAL" as MenuPrincipal
state "AUDITANDO_GUÍAS" as AuditandoGuias
state "VERIFICANDO_CUMPLIMIENTO" as VerificandoCumplimiento

[*] -->Usuario
   
Usuario --> MenuPrincipal
     note on link 
       Iniciar Sesión
    end note

MenuPrincipal -> [*]
    note on link
        Cerrar sesión
    end note


MenuPrincipal --> AuditandoGuias
    note on link
        Acceder al módulo de auditoría /
        Revisar guías
    end note

AuditandoGuias --> MenuPrincipal
    note on link
        Finalizar auditoría /
        Regresar al menú principal
    end note

MenuPrincipal --> VerificandoCumplimiento
    note on link
        Acceder al módulo de verificación
    end note

VerificandoCumplimiento --> MenuPrincipal
    note on link
        Finalizar verificación /
        Regresar al menú principal
    end note

@enduml
