@startuml diagramaContextoAdministrador
state "MENU_PRINCIPAL" as MenuPrincipal
state "LISTANDO_MENSAJES" as ListandoMensaje
state "LISTANDO_GRUPOS" as Grupos
state "LISTANDO_USUARIOS" as Usuarios
state "LISTANDO_ACCIONES" as Auditoria

[*] --> MenuPrincipal
    note on link
        Administrador 
        inicia sesión
    end note

MenuPrincipal -> [*]
    note on link
        Administrador 
        cierra sesión
    end note

MenuPrincipal --> ListandoMensaje
    note on link
        Listar mensajes
    end note

ListandoMensaje --> MenuPrincipal
    note on link
        Abrir Menú Principal
    end note

MenuPrincipal --> Grupos
    note on link
        Listar grupos
    end note

Grupos --> MenuPrincipal
    note on link
        Abrir Menú Principal
    end note

MenuPrincipal --> Usuarios
    note on link
        Listar usuarios
    end note

Usuarios--> MenuPrincipal
    note on link
        Abrir Menú Principal
    end note

MenuPrincipal --> Auditoria
    note on link
        Listar acciones
    end note

Auditoria --> MenuPrincipal
    note on link
        Abrir Menú Principal
    end note

@enduml