@startuml
state "MENU_PRINCIPAL" as MenuPrincipal
state "CREANDO_MENSAJE" as CreandoMensaje
state "VIENDO_RESUMEN" as ViendoResumen
state "LISTANDO_GRUPOS" as Grupos
state "LISTANDO_USUARIOS" as Usuarios

[*] --> MenuPrincipal
    note on link
        Administrador 
        inicia sesión
    end note

MenuPrincipal -> [*]
    note on link
        Administrador 
        cierra sesión
    end note

MenuPrincipal --> CreandoMensaje
    note on link
        Crear mensaje
    end note

CreandoMensaje --> CreandoMensaje 
    note on link
        Crear envio
    end note

MenuPrincipal--> ViendoResumen
    note on link
        Ver resumen
    end note

ViendoResumen -l-> MenuPrincipal
    note on link
        Listar mensajes
    end note

ViendoResumen -l-> ViendoResumen 
    note on link
        Descargar resumen
    end note

CreandoMensaje --> MenuPrincipal
    note on link
        Listar mensajes
    end note

MenuPrincipal --> Grupos
    note on link
        Listar categorias
    end note

Grupos --> MenuPrincipal
    note on link
        Listar mensajes
    end note

MenuPrincipal --> Usuarios
    note on link
        Listar usuarios
    end note

Usuarios--> MenuPrincipal
    note on link
        Listar mensajes
    end note

@enduml