@startuml
start
:El usuario solicita asignar un profesor a una asignatura;
:Sistema muestra formulario para asignar profesor;
:Sistema solicita datos del profesor y asignaturas;
:Usuario selecciona al profesor;
:Usuario selecciona una o múltiples asignaturas;
:Sistema guarda los cambios;
:Sistema actualiza el calendario del profesor con la información correspondiente;
stop
@enduml
