@startuml
start
:El usuario solicita introducir edición de una asignación;
:El sistema permite la introducción de datos para la edición;
:El usuario introduce selección del día y la fecha;
:El sistema presenta las aulas disponibles;
if (¿Existen aulas disponibles?) then (Sí)
  :El sistema actualiza los datos de la asignatura con los nuevos seleccionados;
  :El sistema guarda la información y visualiza el cambio de estatus de la asignatura si es necesario;
  :El sistema presenta confirmación: "Asignatura actualizada correctamente";
else (No)
  :El sistema presenta mensaje de error: "No hay aulas disponibles";
endif
stop
@enduml
  