@startuml
start
:El usuario solicita editar una asignación;
:Sistema muestra la asignatura previamente seleccionada y su información actual;

:Usuario selecciona el día y la fecha;
:Sistema chequea por aulas disponibles;
if (¿Aulas disponibles?) then (Sí)
  :Sistema actualiza los datos de la asignatura con los nuevos seleccionados;
  :Sistema guarda la información y cambia el estatus de la asignatura si es necesario;
  :Sistema muestra confirmación: "Asignatura actualizada correctamente";
else (No)
  :Sistema muestra mensaje de error: "No hay aulas disponibles";
endif
stop
@enduml

