@startuml
start
:El usuario solicita introducir inicio de sesión;
:Sistema permite introducir credenciales (usuario y contraseña);
if (¿Credenciales válidas?) then (Sí)
  :Sistema permite el acceso;
  :Sistema presenta mensaje de bienvenida;
else (No)
  :Sistema presenta mensaje de error: "Credenciales incorrectas";
endif
stop
@enduml
