@startuml
title Iniciar Sesión
start
:El usuario solicita introducir credenciales;
:El sistema permite introducir credenciales (usuario y contraseña);
:El usuario introduce credenciales;
if (¿Credenciales válidas?) then (Sí)
  :El sistema permite el acceso;
  :El sistema presenta mensaje de bienvenida;
else (No)
  :El sistema presenta mensaje de error: "Credenciales incorrectas";
endif
stop
@enduml