@startuml
start
:El usuario solicita registrar una nueva asignatura;
:Sistema muestra formulario para registrar asignatura;
:Sistema solicita datos de la asignatura (grado, nombre);
:Sistema permite el registro;
:Sistema incorpora la asignatura;
stop
@enduml