@startuml
start
:El usuario solicita listar aulas disponibles;
:El Sistema permite listar aulas disponibles;
:El Usuario solicita introducir datos de aulas;
:Sistema permite introducir datos de aulas;
:Usuario introduce especificación de filtros:
  - Día,
  - Hora,
  - Aula grande,
  - Aulas con computadoras,
  - Ninguno;
if (¿Existen aulas disponibles con los filtros?) then (Sí)
  :Sistema presenta las aulas disponibles entre los filtros seleccionados;
else (No)
  :Sistema presenta mensaje de error: "No se encontraron aulas disponibles";
endif
stop
@enduml