@startuml
start
:El usuario solicita ver la disponibilidad de aulas;
:Sistema solicita fecha y rango horario;
if (Datos válidos?) then (Sí)
  :Sistema muestra aulas disponibles;
else (No)
  :Sistema muestra mensaje de error: "No se encontraron aulas disponibles";
endif
stop
@enduml
