@startuml
title Casos de Uso (Usuario) - Listar Datos de Usuario

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

left to right direction

actor Usuario

folder "Gestión de Usuario" as usuario {
    Usuario --> (Listar Datos de Usuario)
}

@enduml
