@startuml visualizacionConfirmacionDocumentos
left to right direction
actor "Usuario" as Usuario
actor "Destinatario" as Destinatario

package "Visualización y Confirmación de Documentos" {
    usecase "Listar Mensajes" as VCD1
    usecase "Abrir Mensaje" as VCD2
    VCD2 .> VCD1 : <<extend>>
    usecase "Abrir Documento" as VCD3
    VCD3 .> VCD2 : <<extend>>
    usecase "Confirmar Lectura/firmar Documento" as VCD4
    VCD4 .> VCD3 : <<extend>>
}

Usuario <|- Destinatario
Destinatario <|- Administrador
Usuario -u-> VCD1
Usuario --> VCD2
Usuario --> VCD3
Usuario --> VCD4
@enduml