@startuml visualizacionConfirmacionDocumentos
left to right direction
actor "Gestor" as Usuario
actor "Destinatario" as Destinatario

package "Visualización y Confirmación de Mensajes" {
    usecase "Listar Mensajes" as VCD1
    usecase "Abrir Mensaje" as VCD2
    usecase "Abrir Documento" as VCD3
    usecase "Confirmar Lectura/firmar Mensaje" as VCD4
    VCD4 .> VCD2 : <<include>>
}

Destinatario -|> Usuario
Usuario -|> Administrador
Destinatario -u-> VCD1
Destinatario --> VCD2
Destinatario --> VCD3
Destinatario --> VCD4
@enduml