@startuml DiagramaDeContextoMenuRutinasyEjerciciosProfesor
!define RECTANGLE(x, color) rectangle x #color

' Definición de los rectángulos con sus colores
RECTANGLE(NAVEGACION_MENUS, SkyBlue) 
RECTANGLE(MENU_RUTINAS_y_EJERCICIOS, PaleGreen)

' Submenús de "Rutinas y Ejercicios" con sus colores
RECTANGLE(CREANDO_RUTINA, PaleGreen) 
RECTANGLE(MOSTRANDO_RUTINA, PaleGreen) 
RECTANGLE(EDITANDO_RUTINA, PaleGreen) 
RECTANGLE(CREANDO_EJERCICIO, PaleGreen) 
RECTANGLE(MOSTRANDO_EJERCICIO, PaleGreen) 
RECTANGLE(EDITANDO_EJERCICIO, PaleGreen) 


CREANDO_RUTINA -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
MOSTRANDO_RUTINA -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
EDITANDO_RUTINA -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
CREANDO_EJERCICIO -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
MOSTRANDO_EJERCICIO -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
EDITANDO_EJERCICIO -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú

' Menú "Rutinas y Ejercicios"
MENU_RUTINAS_y_EJERCICIOS -[#PaleGreen]-> CREANDO_RUTINA : Crear rutina
MENU_RUTINAS_y_EJERCICIOS -[#PaleGreen]-> CREANDO_EJERCICIO : Crear ejercicio
MENU_RUTINAS_y_EJERCICIOS -[#PaleGreen]-> MOSTRANDO_RUTINA : Mostrar rutina
MENU_RUTINAS_y_EJERCICIOS -[#PaleGreen]-> MOSTRANDO_EJERCICIO : Mostrar ejercicio
MOSTRANDO_RUTINA -[#PaleGreen]-> EDITANDO_RUTINA : Editar rutina
MOSTRANDO_EJERCICIO -[#PaleGreen]-> EDITANDO_EJERCICIO : Editar ejercicio

@enduml