@startuml DiagramaDeContextoMenuClasificacionProfesor
!define RECTANGLE(x, color) rectangle x #color

RECTANGLE(NAVEGACION_MENUS, SkyBlue)
RECTANGLE(MENU_CLASIFICACION, Gold)

' Submenús de "Clasificación"
RECTANGLE(VIENDO_ALUMNOS_CLASE, Gold)

VIENDO_ALUMNOS_CLASE -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú

' Menú "Clasificación"
MENU_CLASIFICACION -[#Gold]->  VIENDO_ALUMNOS_CLASE : Ver alumnos dentro de clases

@enduml