@startuml DiagramaDeContextoMenuPerfilProfesor
!define RECTANGLE(x, color) rectangle x #color

' Definición de los rectángulos con sus colores
RECTANGLE(NAVEGACION_MENUS, SkyBlue) 
RECTANGLE(MENU_PERFIL, LightCoral)

' Submenús de "Perfil" con sus colores
RECTANGLE(CREANDO_CLASE, LightCoral) 
RECTANGLE(MOSTRANDO_QR, LightCoral) 
RECTANGLE(VIENDO_MIS_CLASES, LightCoral) 
RECTANGLE(VIENDO_ALUMNOS, LightCoral) 
RECTANGLE(VIENDO_RETOS_ALUMNOS, LightCoral) 
RECTANGLE(EVALUANDO_RETOS, LightCoral)

' Conexiones entre submenús y navegación
CREANDO_CLASE -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
MOSTRANDO_QR -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
VIENDO_MIS_CLASES -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
VIENDO_ALUMNOS -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
VIENDO_RETOS_ALUMNOS -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
EVALUANDO_RETOS -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú

' Conexiones en el menú "Perfil"
MENU_PERFIL -[#LightCoral]-> CREANDO_CLASE : Crear clase
MENU_PERFIL -[#LightCoral]-> MOSTRANDO_QR : Mostrar QR
MENU_PERFIL -[#LightCoral]-> VIENDO_MIS_CLASES : Ver mis clases
VIENDO_MIS_CLASES -[#LightCoral]-> VIENDO_ALUMNOS : Ver alumnos
VIENDO_ALUMNOS -[#LightCoral]-> VIENDO_RETOS_ALUMNOS : Ver retos alumnos
VIENDO_RETOS_ALUMNOS -[#LightCoral]-> EVALUANDO_RETOS : Evaluar retos

@enduml
