@startuml DiagramaDeContextoMenuRetosProfesor
!define RECTANGLE(x, color) rectangle x #color

RECTANGLE(NAVEGACION_MENUS, SkyBlue)
RECTANGLE(MENU_RETOS, LightSalmon) 

' Submenús de "Retos"
RECTANGLE(CREANDO_RETOS, LightSalmon) 
RECTANGLE(EDITANDO_RETOS, LightSalmon) 

CREANDO_RETOS -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
EDITANDO_RETOS -[#SkyBlue]> NAVEGACION_MENUS : Cambiar menú

' Menú "Retos"
MENU_RETOS -[#LightSalmon]-> CREANDO_RETOS : Crear retos
MENU_RETOS -[#LightSalmon]-> EDITANDO_RETOS : Editar retos

@enduml