@startuml
' Clase que representa al candidato que opta a la beca
class Candidato 

' Clase que representa el test que debe realizar el candidato
class Test 

' Clase que representa la evaluación del candidato por parte de la administración
class Evaluacion 

' Clase que representa los videos tutoriales a los que el candidato tiene acceso
class VideoTutorial 

' Clase que representa la administración encargada del proceso de selección
class Administracion 

' Clase que recoje a los candidatos
class Sede

' Relaciones entre las clases
Candidato -- Test           : Realiza
Candidato -- VideoTutorial   : Accede
Candidato -- Evaluacion      : Es evaluado en
Administracion -- Evaluacion : Realiza
Sede -- Candidato : Recoje
@enduml
