@startuml

class Profesor {
titulación
categoría 
ECTS

}

Enum Contrato{
Parcial Temporal
Parcial Indefinido
Parcial Obra
Parcial Baja
Completo Temporal
Completo Indefinido
Completo Obra
Completo Baja
}

class Titulacion {
nombre 
curso
}

class Asignatura {
curso  
semestre 
codigoCampus
tipo 
ECTS 
}

class MemoriaAcademica {
 
}

class Departamento {
   
}

class PlanEstudios {
}


Profesor --> Titulacion : "imparte en"
Profesor --> Asignatura : "enseña"
Asignatura --> Titulacion : "pertenece a"
MemoriaAcademica --> Asignatura : "reporta sobre"
Profesor --> MemoriaAcademica : "elabora"
Asignatura --> PlanEstudios : "forma parte de"
Profesor --> Departamento : "pertenece a"
Titulacion --> Departamento : "se ofrece en"
Profesor --> Contrato : "tiene un "
@enduml