@startuml
title Diagrama de Objetos Simplificado - Time Guardian

object "gestorDeHorarios" as gestorDeHorarios {
    rol = "Gestor de Horarios"
}

object "asignacionDocenteAsignatura" as asignacionDocenteAsignatura {
    docente = "Manuel Masias"
    asignatura = "Programación I"
}
gestorDeHorarios -r-> asignacionDocenteAsignatura : "Asigna >"

object "asignacionAulaAsignatura" as asignacionAulaAsignatura {
    asignatura = "Programación I"
    aula = "-2.6"
}


gestorDeHorarios -r-> asignacionAulaAsignatura : "Asigna >"

object "horario : Horario" as horario {
    dia = "Lunes"
    horaInicio = "8:00"
    horaFin = "10:00"
    asignatura = "Programación I"
    aula = "-2.6"
    docente = "Manuel Masias"
}
asignacionDocenteAsignatura -d-> horario : "Contribuye a >"
asignacionAulaAsignatura -d-> horario : "Contribuye a >"

note "Completar todas las\nasignaciones para formar\nel horario completo" as nota
gestorDeHorarios -u-> nota
nota -d-> horario
@enduml