@@startuml
class Profesores
class Indicadores
class Informes
class Titulacion
class CargaTotal
class Asignaturas


Titulacion "1" -- "many" Asignaturas : contiene
Asignaturas "many" -- "many" Profesores : son impartidas
Asignaturas "1" -- "1" CargaTotal : generan
Profesores "many" -- "1" CargaTotal : obtienen
CargaTotal "1" -- "many" Indicadores : esta medida por
Indicadores "1" -- "1" Informes : generan

@@enduml