@startuml
title Diagrama de clases

class AdministradorDeHorarios {
    - listaHorarios
}

class Profesor {
    - nombre
    - apellido
}

class Curso {
    - id
    - nombre
}

class Salon {
    - numero
}

class Horario {
    - dia
    - horaInicio
    - horaFin
    - curso
    - salon
}

class ProfesorImparte {
    - profesor
    - curso
}

class AsignarCursoSalon {
    - curso
    - salon
}

AdministradorDeHorarios -- Profesor
AdministradorDeHorarios -- Curso
AdministradorDeHorarios -- Salon

AdministradorDeHorarios -- ProfesorImparte
ProfesorImparte -- AsignarCursoSalon
AsignarCursoSalon -- Horario

Profesor -- ProfesorImparte
Curso -- ProfesorImparte
Curso -- AsignarCursoSalon
Salon -- AsignarCursoSalon
@enduml