@startuml

box "repo SDR@mmasias" 
    participant "main" as main
    activate main
    note left main: Cada grupo tendrá una \nrama asignada dentro del\nrepositorio principal de entregas
    participant "ramaGrupo" as ramaGrupo
end box

box "repo SDR@CoordinadorGrupo" 
    ' note right of participante: El participante crea una carpeta, \n dentro de la carpeta de trabajo \n con el formato nombreApellido
    participant "participante" as participante
    activate participante
end box


main --> participante: fork
participante --> ramaGrupo: aportes / avances / revisiones
activate ramaGrupo
ramaGrupo -> ramaGrupo: propuesta de revisión / ajuste

note over main, ramaGrupo: Durante el cuatrimestre, la rama \n del grupo se va actualizando con sus avances.


note left main: Al final del cuatrimestre, el repo\ncontiene las ramas de todos los participantes

@enduml
