@startuml
hide empty members
hide circle

abstract Remitente

class Notificaciones

abstract Gestor

class Mensaje

class RastreadorDocumento

abstract Receptor

class Destinatario

class Administrador

class Grupo

class Documento

class Auditoria

class RastreadorAcciones

Mensaje  "1"--"*" RastreadorDocumento : contiene

Mensaje  "1"-d-"*" Receptor : se envía

Remitente --|> Administrador
Remitente --|> Gestor

Receptor --|> Destinatario 

Receptor -r- Grupo : pertenece

RastreadorDocumento -- Notificaciones : genera

Remitente "1"-u-"*" Mensaje : genera

Administrador -- Auditoria : realiza

Auditoria --* RastreadorAcciones
Auditoria -r-* RastreadorDocumento

RastreadorDocumento "1"--"1" Documento: adjunta
@enduml