@startuml
left to right direction

package "Gestión de Carga Docente" {
    actor "Ordenación" as ord
    actor "Técnico Calidad" as tec
    actor "RRHH" as rrhh
    actor "Administrador" as admin

    rectangle "Asignaciones" {
        package "Carga Docente" as cargaDocentePackage {
            usecase "Asignar Carga" as asignarCarga
            note top of asignarCarga
                De asignaturas
                a profesores
            end note
        }

        package "Memoria" as valoresPackage {
            usecase "Asignar Valores" as asignarValores
            note top of asignarValores
                Consignados en Memoria
                por Titulación
            end note

            note "Permitir validar datos\ndel año anterior" as valoresDef
        }

        package "SIIU y DGU" as SIIUyDGUPackage {
            usecase "Asignar Valor de Información" as asignarValor

            package "Tipos" {
                usecase "a SIIU" as SIIU
                usecase "a DGU" as DGU
            }

            usecase "del PDI" as PDI

        }
    }

    rectangle "Revisión de Cumplimiento" {
        package "Revisión" as revisionPackage {
            usecase "Revisar Profesores" as revisarCarga
            note top of revisarCarga
                Revisar Listado de Profesores
                cuya Carga Docente no se ajusta
                a carga supuesta por contrato
            end note
        }
    }

    ord ---> cargaDocentePackage
    ord ---> revisionPackage

    rrhh ---> revisionPackage

    tec ---> valoresPackage
    tec ---> SIIUyDGUPackage

    asignarValor ..> SIIU
    asignarValor ..> DGU
    SIIU ..> PDI
    DGU ..> PDI

    note top of admin
        El Administrador tiene
        acceso a todos los casos
        de uso de Departamentos
    end note
}
@enduml