@startuml
actor Profesor as P
actor Personal_RRHH as RH
rectangle "Gestión de Datos de Profesorado" {
    usecase "Actualización de Datos de Profesorado" as UC3
    P --> UC3
    RH --> UC3
}
@enduml
