@startuml
left to right direction

package "Gestión de Datos del Profesorado" {
    actor "Profesores" as prof
    actor "Ordenación" as ord
    actor "Técnico Calidad" as tec
    actor "RRHH" as rrhh
    actor "Administrador" as admin
    
    together {
        rectangle "Introducción de Datos" {
            package "Datos Académicos" as datosAcadPackage {
                usecase "Introducir Datos Académicos" as datosAcad
                
                package "Tipos Académicos" {
                    usecase "de Experiencia Docente" as expDoc
                    usecase "de Experiencia Profesional" as expProf
                    usecase "de Experiencia Investigadora" as expInv
                    usecase "de Sexenios" as sexenios
                    usecase "de Acreditaciones" as acred
                    usecase "de Movilidad" as mov
                    usecase "de Titulación Profesional" as titProf
                }
                note "Permitir heredar datos\ndel año anterior" as notaDatosAcad
            }
            
            package "Datos Laborales" as datosLabPackage {
                usecase "Introducir Datos Laborales" as datosLab
                
                package "Tipos Laborales" {
                    usecase "de Contrato" as contrato
                    usecase "de Horas" as horas
                    usecase "de Temporalidad" as temp
                    usecase "de Categoría Profesional" as catProf
                }
                note "Permitir heredar datos\ndel año anterior" as notaDatosLab
            }
        }
        
        rectangle "Consulta de Datos" {
            package "Datos Personales" as datosPersonalesPackage {
                usecase "Consultar Valores" as consultaValores
                note top of consultaValores
                    Consultar valores asignados
                    de contrato y otros datos
                    personales
                end note
            }
            
            package "Asignacion Docente" as asignacionesDocentesPackage {
                together {
                    package "Por Varios" as porVarPackage {
                        usecase "Consultar Asignación" as consAsig
                        usecase "por Titulación" as porTit
                        usecase "por Curso" as porCurso
                        usecase "por Semestre" as porSem
                    }

                    package "Por Profesor" as porProfPackage {
                        usecase "Consultar Asignación" as consProf
                        note top of consProf
                            Consultar asignación docente por
                            profesor (créditos y asignaturas)
                        end note
                    }
                }
            }
            
            package "Claustro Docente" as claustroPackage {
                usecase "Consultar Claustro" as consClaustro
                note top of consClaustro
                    Listado PDI asociado
                    a una titulación, anual,
                    por semestre
                end note
            }
        }
        
        rectangle "Modificación y Validación" {
            package "Gestión Datos" as gestDatosPackage {
                usecase "Validar Datos"
                usecase "Modificar Datos"
                note "Datos introducidos previamente\npor el profesorado" as notaGestDatos
            }
            
            package "Validación Memoria" as valMemPackage {
                usecase "Validar Cumplimiento" as valCumpli1
                note right 
                    Validar cumplimiento de
                    compromisos de memoria con
                    los valores de la titulación
                end note
            }
        }
    }
    
    ' Relaciones de datos académicos
    datosAcad ..> expDoc
    datosAcad ..> expProf
    datosAcad ..> expInv
    datosAcad ..> sexenios
    datosAcad ..> acred
    datosAcad ..> mov
    datosAcad ..> titProf
    
    ' Relaciones de datos laborales
    datosLab ..> contrato
    datosLab ..> horas
    datosLab ..> temp
    datosLab ..> catProf
    
    ' Relaciones de asignación por asignatura
    consAsig ..> porTit
    consAsig ..> porCurso
    consAsig ..> porSem
    
    ' Relaciones de actores
    prof --> datosAcadPackage
    prof --> datosPersonalesPackage
    prof --> porVarPackage

    rrhh ---> gestDatosPackage
    rrhh ---> datosLabPackage
    rrhh ---> claustroPackage
    rrhh ---> porProfPackage

    ord ---> claustroPackage
    ord ---> porProfPackage
    ord ---> valCumpli1

    tec --> claustroPackage
    tec --> porProfPackage
    tec --> valCumpli1
    
    note top of admin
        El Administrador tiene
        acceso a todos los casos
        de uso de Técnico de Calidad,
        RRHH y Ordenación
    end note
}
@enduml