@startuml
left to right direction

actor Profesor as A_Profesor
actor Departamento as A_Departamento
actor Sistema as A_Sistema

rectangle "Carga Docente" {
    usecase "Ajustar" as Caso1
    usecase "Proponer" as Caso2
    usecase "Revisar" as Caso4
    usecase "Asignar" as Caso5
    usecase "Ver" as Caso7
}

rectangle "Memoria Académica" {
 usecase "Verificar Contratos" as Caso6
 usecase "Generar" as Caso3
    
   
}

A_Profesor --> Caso7

A_Departamento --> Caso2
A_Departamento --> Caso4
A_Departamento --> Caso5

A_Sistema --> Caso1
A_Sistema --> Caso6
A_Sistema --> Caso3




@enduml
