@startuml
left to right direction

package "Generación de Indicadores e Informes" {
    actor "Técnico Calidad" as tec
    actor "Administrador" as admin
  
    rectangle "Generación de Indicadores e Informes" {
      package "Indicadores" as indicadores {
        usecase "Obtener indicadores"
        note right of "Obtener indicadores"
           Para Sistema de Gestión
        end note
      }
      
      package "Informes" as informes {
        usecase "Emitir informe del Profesorado" as emitirInforme
        package "Tipos de Informes" {
          usecase "por Titulación" as titulacion
          usecase "Global" as global
        }
      }
    }

    emitirInforme ..> titulacion
    emitirInforme ..> global

    tec --> indicadores
    tec --> informes

    note right of admin
      El Administrador tiene
      acceso a todos los casos
      de uso de Departamentos
    end note
}
@enduml
