@startuml
left to right direction

package "Generación de Indicadores e Informes" {
  actor "Técnico Calidad" as tec
  actor "Administrador" as admin

  rectangle "Generación de Indicadores e Informes" {
    package "Indicadores" as indicadores {
      usecase "Obtener Indicadores" as obtenerIndicadores
      note top of obtenerIndicadores
        Para el Sistema de Gestión
      end note
    }

    package "Informes" as informes {
      usecase "Emitir Informe" as emitirInforme
      package "Tipos de Informes" {
        usecase "por Titulación" as titulacion
        usecase "Global" as global
      }
      note top of emitirInforme
        Emitir Informe
        del Profesorado
      end note
    }
  }

  emitirInforme ..> titulacion
  emitirInforme ..> global

  tec --> indicadores
  tec --> informes

  note top of admin
    El Administrador tiene
    acceso a todos los casos
    de uso de Departamentos
  end note
}
@enduml
