@startuml
left to right direction

actor "Ordenación" as A_Ordenacion

rectangle "Gestión de Ordenación" {
    usecase "Asignar carga docente (herencia)" as UC1
    usecase "Revisar cumplimiento de memoria por titulación" as UC2
    usecase "Revisar profesores con carga no ajustada al contrato" as UC3
}

rectangle "Consultas Comunes" {
    usecase "Consultar claustro docente" as UC4
    usecase "Consultar asignación docente por profesor" as UC5
}

A_Ordenacion --> UC1
A_Ordenacion --> UC2
A_Ordenacion --> UC3
A_Ordenacion --> UC4
A_Ordenacion --> UC5

@enduml
