@startuml
left to right direction

actor "Profesores" as Profesores

rectangle "Casos de Uso - Profesor" {
  usecase "Introducir datos de experiencia docente, profesional, investigadora, etc." as CU1
  usecase "Consultar valores asignados de contrato y otros datos personales" as CU2
  usecase "Consultar asignaciones docentes (por titulación, curso y semestre)" as CU3
}

Profesores --> CU1
Profesores --> CU2
Profesores --> CU3

@enduml
