@startuml
left to right direction

actor "RRHH" as A_RRHH

rectangle "Gestión de RRHH" {
    usecase "Validar/modificar datos del profesorado" as UC1
    usecase "Introducir datos de contrato y categoría (herencia)" as UC2
    usecase "Revisar profesores con carga no ajustada al contrato" as UC3
}

rectangle "Consultas Comunes" {
    usecase "Consultar claustro docente" as UC4
    usecase "Consultar asignación docente por profesor" as UC5
}

A_RRHH --> UC1
A_RRHH --> UC2
A_RRHH --> UC3
A_RRHH --> UC4
A_RRHH --> UC5

@enduml
