@startuml
left to right direction

actor "Técnico Calidad" as A_TecnicoCalidad

rectangle "Gestión de Calidad" {
    usecase "Asignar valores en memoria por titulación (herencia)" as UC1
    usecase "Asignar datos a SIIU/DGU" as UC2
    usecase "Validar memoria vs compromisos" as UC3
    usecase "Obtener indicadores y emitir informes" as UC4
}

rectangle "Consultas Comunes" {
    usecase "Consultar claustro docente" as UC5
    usecase "Consultar asignación docente por profesor" as UC6
}

A_TecnicoCalidad --> UC1
A_TecnicoCalidad --> UC2
A_TecnicoCalidad --> UC3
A_TecnicoCalidad --> UC4
A_TecnicoCalidad --> UC5
A_TecnicoCalidad --> UC6

@enduml
