@startuml
hide empty description

[*] --> Asignado : inicio del periodo académico

Asignado --> PreparandoClases : preparar materiales didácticos
PreparandoClases --> ImpartiendoClasesTeoricas : iniciar clases teóricas
PreparandoClases --> ImpartiendoClasesPracticas : iniciar clases prácticas

ImpartiendoClasesTeoricas --> ImpartiendoClasesTeoricas : continuar sesiones teóricas
ImpartiendoClasesTeoricas --> Evaluando : finalizar clases teóricas y calificar

ImpartiendoClasesPracticas --> ImpartiendoClasesPracticas : continuar sesiones prácticas
ImpartiendoClasesPracticas --> Evaluando : finalizar clases prácticas y calificar

Evaluando --> FinDePeriodo : consolidar calificaciones
FinDePeriodo --> [*] : acaba el periodo escolar

@enduml
