@startuml
state "NO_AUTENTICADO" as NoAuth
state "MENU_PRINCIPAL" as Menu
state "GESTION_CARGA_DOCENTE" as Car
state "GESTION_DATOS" as Dat
state "VALIDACION_Y_CUMPLIMIENTO" as Val
state "CONSULTA_DE_INFORMACION" as Inf
state "INDICADORES_Y_REPORTES" as Ind

[*] --> NoAuth

NoAuth --> Menu
note on link
    Iniciar sesión
end note

Menu --> Car
note on link
  Asignar Carga Docente
end note

Menu --> Dat
note on link
  Introducir Datos Laborales
  Modificar Datos del Profesorado
end note

Menu --> Val
note on link
  Asignar Información SIIU/DGU
  Asignar Valores en Memoria
end note

Menu --> Inf
note on link
  Consultar Claustro
  Consultar Asignación por Profesor
end note

Menu --> Ind
note on link
  Emitir Informe
end note

Car --> Car
note on link
  Revisar Profesores con Carga no ajustada
end note

Val --> Val
note on link
  Validar Datos del Profesorado
  Validar Cumplimiento de Memoria
end note

Ind --> Ind
note on link
  Obtener Indicadores
end note

Car --> Menu
note on link
    Volver al menú
end note

Dat --> Menu
note on link
    Volver al menú
end note

Val --> Menu
note on link
    Volver al menú
end note

Inf --> Menu
note on link
    Volver al menú
end note

Ind --> Menu
note on link
    Volver al menú
end note

Menu --> NoAuth
note on link
    Cerrar sesión
end note
@enduml