@startuml
state "NO_AUTENTICADO" as NoAuth
state "MENU_PRINCIPAL" as Menu
state "GESTION_DATOS" as Dat
state "CONSULTA_DE_INFORMACION" as Inf

[*] --> NoAuth

NoAuth --> Menu
note on link
    Iniciar sesión
end note

Menu --> Dat
note on link
  Introducir Datos Académicos
end note

Menu --> Inf
note on link
  Consultar Asignación Docente
  Consultar Datos Personales
end note

Dat --> Menu
note on link
    Volver al menú
end note

Inf --> Menu
note on link
    Volver al menú
end note

Menu --> NoAuth
note on link
    Cerrar sesión
end note
@enduml