@startuml

state "NO_AUTENTICADO" as NoAuth
state "MENU_PRINCIPAL" as Menu
state "DATOS_ACADEMICOS" as Acad
state "PERSONAL_DOCENTE" as Pers
state "CONSULTAS_Y_REPORTES" as Cons
state "ASIGNACIONES" as Asig

[*] --> NoAuth

NoAuth --> Menu
    note on link
        Iniciar sesión
    end note

Menu --> Acad
    note on link
        Consultar Asignación por Profesor
    end note

Menu --> Pers
    note on link
        Consultar Claustro Docente
        Asignar Información SIIU/DGU
    end note

Menu --> Cons
    note on link
        Emitir Informe
    end note

Menu --> Asig
    note on link
        Asignar Valores en Memoria
    end note

Cons --> Cons
    note on link
        Validar Cumplimiento de Memoria
        Obtener Indicadores
    end note

@enduml