@startuml
state "NO_AUTENTICADO" as NoAuth
state "MENU_PRINCIPAL" as Menu
state "VALIDACION_Y_CUMPLIMIENTO" as Val
state "CONSULTA_DE_INFORMACION" as Inf
state "INDICADORES_Y_REPORTES" as Ind

[*] --> NoAuth

NoAuth --> Menu
note on link
    Iniciar sesión
end note

Menu --> Val
note on link
  Asignar Información SIIU/DGU
  Asignar Valores en Memoria
end note

Menu --> Inf
note on link
  Consultar Claustro
  Consultar Asignación por Profesor
end note

Menu --> Ind
note on link
  Emitir Informe
end note

Val --> Val
note on link
  Validar Cumplimiento de Memoria
end note

Ind --> Ind
note on link
  Obtener Indicadores
end note

Val --> Menu
note on link
    Volver al menú
end note

Inf --> Menu
note on link
    Volver al menú
end note

Ind --> Menu
note on link
    Volver al menú
end note

Menu --> NoAuth
note on link
    Cerrar sesión
end note
@enduml