@startuml

title Actualizar Horario-Asignatura-Aula

start
:El usuario solicita introducir cambios en una asignación;
:El sistema permite introducir los datos de la asignación a modificar;
:El usuario introduce los nuevos datos de la asignación;
if (¿Datos válidos?) then (Sí)
:El sistema permite guardar los cambios;
:El sistema actualiza la asignación con la nueva información;
:El sistema presenta una confirmación: "Asignación actualizada correctamente";
else (No)
:El sistema presenta un mensaje de error: "Los datos introducidos no son válidos";
:El sistema permite introducir nuevamente los datos;
endif
stop

@enduml