@startuml
title Caso de uso: Listar Tests

skinparam {
    NoteBackgroundColor #lightYellow
    ArrowColor #blue
    NoteBorderColor #blue
    linetype polyline
}

state startState as "PÁGINA PRINCIPAL"
state endState as "PÁGINA PRINCIPAL"

startState --> VerTests
note on link
    <b>Administrador Accede</b>
    * Selecciona la opción de listar tests
end note

VerTests --> MostrarLista
note on link
    <b>Sistema Muestra</b>
    * Lista de tests disponibles
    * Opciones para editar o eliminar
end note

MostrarLista --> endState
note on link
    <b>Administrador Finaliza</b>
    * Regresa a la página principal
end note
@enduml
