@startuml
ListadoGuías -up-> VerificarCumplimientoConMemoriaVerificada

state VerificarCumplimientoConMemoriaVerificada {
    state SeleccionarGuia as " "
    state VerificarGuia as " "
    state ResultadoVerificacion <<choice>>
    state GuiaNoCumpleRequisitos as " "
    state GuiaCumpleRequisitos as " "


    [*] --> SeleccionarGuia
    note on link
    <b>Director de Grado Solicita</b>
    * director de calidad selecciona guía
    end note

    SeleccionarGuia --> VerificarGuia
    note on link
    <b>Sistema Permite</b>
    * director de calidad verifica la guía
    end note

    VerificarGuia --> ResultadoVerificacion
    note on link
    <b>Sistema Muestra</b>
    * sistema muestra el resultado de la verificación
    end note

    ResultadoVerificacion -->  GuiaNoCumpleRequisitos
    note on link
    <b>Sistema Muestra</b>
    * guía no cumple estandares de calidad
    end note

     GuiaNoCumpleRequisitos --> [*]
    note on link
    <b>Sistema Retorna</b>
    * al estado inicial sin seleccionar guía
    end note

    ResultadoVerificacion -->  GuiaCumpleRequisitos
    note on link
    <b>SSistema Muestra</b>
    * guía cumple estandares de calidad
    end note
    
    GuiaCumpleRequisitos --> [*]
    note on link
    <b>Sistema Retorna</b>
    * al estado inicial sin seleccionar guía
    end note
    
}

VerificarCumplimientoConMemoriaVerificada -up-> ListadoGuías
@enduml
