@startuml manejoCategoria
left to right direction
actor "Administrador General" as AdminGeneral

package "CRUD de Categorías" {
    usecase "Crear Categoría" as CC1
    usecase "Ver Categoría" as CC2
    usecase "Actualizar Categoría" as CC3
    usecase "Borrar Categoría" as CC4
}

AdminGeneral --> CC1
AdminGeneral --> CC2
AdminGeneral --> CC3
AdminGeneral --> CC4
@enduml
