@startuml

left to right direction

actor Profesor

usecase "Editar Contenido de la Guía" as EditarGuia
usecase "Enviar Guía Docente para Revisión" as EnviarGuia

Profesor --> EditarGuia
Profesor --> EnviarGuia


@enduml