@startuml
left to right direction

actor "Técnico de Calidad" as TecnicoCalidad

usecase "Generar Nueva Versión de la Guía" as GenerarVersion
usecase "Asignar Guías Docentes a Profesor" as AsignarGuiaProfesor
usecase "Editar Contenido Estatico" as EditarContenidoEstatico

TecnicoCalidad --> GenerarVersion
TecnicoCalidad --> AsignarGuiaProfesor
TecnicoCalidad --> EditarContenidoEstatico


@enduml