@startuml ManejoUsuario
left to right direction
actor "Administrador General" as AdminGeneral

package "CRUD de Usuarios" {
    usecase "Crear Usuario" as CU1
    usecase "Ver Usuario" as CU2
    usecase "Actualizar Usuario" as CU3
    usecase "Borrar Usuario" as CU4
}

AdminGeneral --> CU1
AdminGeneral --> CU2
AdminGeneral --> CU3
AdminGeneral --> CU4
@enduml
