@startuml manejoGrupo
left to right direction
actor "Responsable" as Responsable
actor "Administrador General" as AdminGeneral

package "CRUD de Grupos" {
    usecase "Crear Grupo" as CC1
    usecase "Ver Grupo" as CC2
    usecase "Actualizar Grupo" as CC3
    usecase "Borrar Grupo" as CC4
}

AdminGeneral --|> Responsable
Responsable --> CC1
Responsable --> CC2
Responsable --> CC3
Responsable --> CC4
@enduml
