@startuml diagramaDeEstados

[*] --> LeerMensaje

LeerMensaje --> LeerDocumento

LeerDocumento --> ConfirmarDocumento
LeerDocumento --> LeerMensaje

ConfirmarDocumento --> LeerMensaje
LeerMensaje --> CerrarMensaje

CerrarMensaje --> [*]
@enduml