@startuml diagramaDeEstados
[*] --> CrearMensaje
CrearMensaje --> AñadirDocumento

AñadirDocumento --> SeleccionarTipoDocumento

SeleccionarTipoDocumento --> CrearMensaje

CrearMensaje --> EnviarMensaje

EnviarMensaje --> [*]
@enduml