@startuml

title Actualizar Aula

start
:El usuario solicita introducir cambios en un aula;
:El sistema permite introducir los datos del aula a modificar;
:El usuario introduce los nuevos datos del aula;
if (¿Datos válidos?) then (Sí)
:El sistema permite guardar los cambios;
:El sistema actualiza el aula con la nueva información;
:El sistema presenta una confirmación: "Aula actualizada correctamente";
else (No)
:El sistema presenta un mensaje de error: "Los datos introducidos no son válidos";
:El sistema permite introducir nuevamente los datos;
endif
stop

@enduml