@startuml

title Eliminar Aula

start
:El usuario solicita introducir la eliminación de un aula;
:El sistema presenta la lista de aulas existentes;
:El usuario selecciona un aula para eliminar;
:El sistema permite la confirmación para eliminar el aula seleccionada;
if (¿Confirma la eliminación?) then (Sí)
:El sistema elimina el aula seleccionada del sistema;
:El sistema presenta una confirmación: "Aula eliminada correctamente";
else (No)
:El sistema cancela la operación de eliminación;
:El sistema presenta un mensaje: "Operación cancelada por el usuario";
endif
stop

@enduml