@startuml

title Eliminar Asignatura

start
:El usuario solicita introducir la eliminación de una asignatura;
:El sistema presenta la lista de asignaturas existentes;
:El usuario selecciona una asignatura para eliminar;
:El sistema permite la confirmación para eliminar la asignatura seleccionada;
if (¿Confirma la eliminación?) then (Sí)
:El sistema elimina la asignatura seleccionada del sistema;
:El sistema presenta una confirmación: "Asignatura eliminada correctamente";
else (No)
:El sistema cancela la operación de eliminación;
:El sistema presenta un mensaje: "Operación cancelada por el usuario";
endif
stop

@enduml