@startuml

actor Usuario_Invitado
actor Usuario_Registrado

rectangle "Aplicación" {
    usecase "Registrar" as UC1
    usecase "Iniciar Sesión" as UC2
    usecase "Cerrar Sesión" as UC3
    
    rectangle "Post" {
        usecase "Ver Post" as UC4
        usecase "Crear Post" as UC5
        usecase "Comentar en Post" as UC6
        usecase "Dar Like a Post" as UC7
        usecase "Compartir un Post" as UC8
        usecase "Reportar un Post" as UC9
    }
    
    rectangle "Comunidad" {
        usecase "Entrar a Comunidad" as UC10
        usecase "Salir de Comunidad" as UC11
        usecase "Crear Comunidad" as UC12
    }
  
    usecase "Filtrar Contenido" as UC13
    usecase "Modificar Datos de Usuario" as UC14
}

Usuario_Invitado --> UC1
Usuario_Invitado --> UC2
Usuario_Invitado --> UC4
Usuario_Invitado --> UC8

Usuario_Registrado --> UC3
Usuario_Registrado --> UC4
Usuario_Registrado --> UC5
Usuario_Registrado --> UC6
Usuario_Registrado --> UC7
Usuario_Registrado --> UC8
Usuario_Registrado --> UC9
Usuario_Registrado --> UC10
Usuario_Registrado --> UC11
Usuario_Registrado --> UC12
Usuario_Registrado --> UC13
Usuario_Registrado --> UC14

@enduml
