@startuml crear_mensaje

skinparam {
  NoteBackgroundColor #whiteSmoke
  ArrowColor #green
  NoteBorderColor #green
  linetype polyline
}

hide empty description

state startState as "DASHBOARD"
state endState as "DASHBOARD"

startState --> CrearMensaje
note on link
    <b>Usuario Solicita</b>
    * Crear mensaje
end note

CrearMensaje --> abrirDashboard
abrirDashboard --> endState
CrearMensaje -[#red]-> endState

state CrearMensaje{
    state solicitudFiltros as " "
    state envioFiltros as " "
    state revisionFiltrosEnviados <<choice>>

    solicitudFiltros --> envioFiltros
    note on link
        <b>Sistema Solicita</b>
        * Destinatario/Grupo
        * Asunto
        * Título
        * Cuerpo del mensaje
        * <b>Opcionales</b>
            - Documento adjunto
            - Solicitar confirmación de lectura
            - Solicitar firma
            - Fecha límite
        <b>Sistema Permite</b>
        * Crear mensaje
    end note

    envioFiltros --> revisionFiltrosEnviados
    note on link
        <b>Usuario introduce</b>
        * Destinatario/Grupo
        * Asunto
        * Título
        * Cuerpo del mensaje
        * <b>Opcionales</b>
            - Documento adjunto
            - Solicitar confirmación de lectura
            - Solicitar firma
            - Fecha límite
    end note

    revisionFiltrosEnviados -[#red]-> [*]
    note on link
        <b>Sistema Muestra</b>
        Mensaje de error
    end note

    revisionFiltrosEnviados --> [*]
    note on link
        <b>Sistema Muestra</b>
        Mensaje de confirmación
    end note
}

@enduml