@startuml enviar_mensaje

skinparam {
  NoteBackgroundColor #whiteSmoke
  ArrowColor #green
  NoteBorderColor #green
  linetype polyline
}

hide empty description

state startState as "VER_MENSAJE"
state endState as "LISTANDO_MENSAJES"

startState --> EnviarMensaje
note on link
    <b>Usuario Solicita</b>
    * Enviar mensaje
end note

EnviarMensaje--> listarMensajes
listarMensajes--> endState
EnviarMensaje -[#red]-> endState

state EnviarMensaje{
    state solicitudFiltros as " "
    state revisionFiltrosEnviados <<choice>>

    solicitudFiltros --> revisionFiltrosEnviados
    note on link
        <b>Sistema Permite</b>
        Enviar Mensaje
    end note
    
    revisionFiltrosEnviados --> [*]
    note on link
        <b>Sistema Muestra</b>
        Mensaje de confirmación
    end note

    revisionFiltrosEnviados -[#red]-> [*]
    note on link
        <b>Sistema Muestra</b>
        Mensaje de error
    end note
}

@enduml