@startuml

object OfertaTrabajo {
    titulo = "Desarrollador Junior"
    descripcion = "Puesto de desarrollo en Java"
    salario = "30000€"
}

object Administrador {
    nombre = "Carlos"
    email = "carlos@universidad.edu"
}

object Alumni {
    nombre = "Mario"
    email = "MarioDelRio@alumni.edu"
    tipo = "Antiguo Alumno"
}

object Empresa {
    nombre = "Tech Corp"
    direccion = "Calle 13"
}

object Plataforma_acceso {
}


OfertaTrabajo <-- Alumni : busca
OfertaTrabajo <--  Administrador: valida
OfertaTrabajo <.. Empresa : crea
Alumni <-- Plataforma_acceso : autentica
Administrador <-- Plataforma_acceso : autentica
Administrador <-- Empresa : contacta

@enduml
