@startuml

state Alumni_Postula {
    [*] --> Postula : Envía postulación
    Postula --> EnRevision : Empresa revisa postulado
    EnRevision --> Aceptado : Alumni aceptado
    EnRevision --> Rechazado : Alumni rechazado
    Aceptado --> [*]
    Rechazado --> [*]
}

state Empresa_Crea {
    [*] --> Creada : Decide crear una oferta
    Creada --> PendienteValidacion : Envía oferta para validación

    state Administrador_Valida {
        PendienteValidacion --> Revisando : Administrador recibe oferta
        Revisando --> Validada : Valida la oferta
        Revisando --> Rechazada : Invalida la oferta
    }

    Validada --> Disponible : Oferta disponible
    Rechazada --> Cancelada : Oferta cancelada
    Disponible --> Cerrada : Cierra oferta
    Disponible --> Cancelada : Cancela oferta
    Cerrada --> [*]
    Cancelada --> [*]
}

state Estado_Usuario {
    [*] --> Autenticado : Usuario inicia sesión
    Autenticado --> NoAutenticado : Usuario cierra sesión
    NoAutenticado --> [*]
}

@enduml
