@startuml

class Usuario {
}

class Administrador {
}

class Alumni {
}

class Empresas {
}

class OfertaTrabajo {
}

class PlataformaAcceso {
}

OfertaTrabajo <-- Alumni : encuentra & postula
OfertaTrabajo <-- Administrador : aprueba
OfertaTrabajo <-- Empresas : publican
Administrador --|> Usuario : hereda
Alumni --|> Usuario  : hereda
Usuario -- PlataformaAcceso: autentica

@enduml
