@startuml

state Alumni_Postula {
    [*] --> Postula : Envía postulación
    Postula --> EnRevision : Empresa revisa postulado
    EnRevision --> Aceptado : Alumni aceptado
    EnRevision --> Rechazado : Alumni rechazado
    Aceptado --> [*]
    Rechazado --> [*]
}

state Empresa_Crea {
    [*] --> Creada : Decide crear una oferta
    Creada --> PendienteValidacion : Envía oferta para validación
    PendienteValidacion --> Disponible : Administrador valida la oferta
    PendienteValidacion --> Cancelada : Cancela oferta
    Disponible --> Cerrada : Cierra oferta
    Disponible --> Cancelada : Cancela oferta
    Cerrada --> [*]
    Cancelada --> [*]
}

state Administrador_Valida {
    [*] --> Revisando : Recibe oferta
    Revisando --> Validada : Valida la oferta
    Revisando --> Rechazada : Invalida la oferta
    Validada --> [*]
    Rechazada --> [*]
}

state Estado_Usuario {
    [*] --> Autenticado : Usuario inicia sesión
    Autenticado --> NoAutenticado : Usuario cierra sesión
    NoAutenticado --> [*]
}

@enduml
