@startuml AlumnosCasosDeUso
!define RECTANGLE(x) rectangle x

RECTANGLE(NAVEGACION_MENUS)
RECTANGLE(MENU_PERFIL)

RECTANGLE(VIENDO_INSIGNIAS)
RECTANGLE(INSCRIBIENDO_CLASE)
RECTANGLE(MOSTRANDO_QR)

' === MENÚ PERFIL ===
MENU_PERFIL --> VIENDO_INSIGNIAS : Ver insignias
MENU_PERFIL --> INSCRIBIENDO_CLASE : Inscribir en clase
MENU_PERFIL --> MOSTRANDO_QR : Mostrar QR en centro deportivo
VIENDO_INSIGNIAS --> NAVEGACION_MENUS : Cambiar menú
INSCRIBIENDO_CLASE --> NAVEGACION_MENUS : Cambiar menú
MOSTRANDO_QR --> NAVEGACION_MENUS : Cambiar menú

@enduml