@startuml DiagramaDeContextoMenuRutinasyEjerciciosAlumno
!define RECTANGLE(x, color) rectangle x #color

RECTANGLE(NAVEGACION_MENUS, SkyBlue)

RECTANGLE(MENU_RUTINAS_y_EJERCICIOS, PaleGreen)

RECTANGLE(CREANDO_RUTINA, PaleGreen)
RECTANGLE(EDITANDO_RUTINA, PaleGreen)
RECTANGLE(MOSTRANDO_RUTINA, PaleGreen)
RECTANGLE(MOSTRANDO_EJERCICIO, PaleGreen)
RECTANGLE(BUSCANDO_RUTINA, PaleGreen)
RECTANGLE(BUSCANDO_EJERCICIO, PaleGreen)

' === MENÚ RUTINAS Y EJERCICIOS ===
MENU_RUTINAS_y_EJERCICIOS -[#PaleGreen]-> CREANDO_RUTINA : Crear rutina
MENU_RUTINAS_y_EJERCICIOS -[#PaleGreen]-> EDITANDO_RUTINA : Editar rutina
MENU_RUTINAS_y_EJERCICIOS -[#PaleGreen]-> MOSTRANDO_RUTINA : Mostrar rutina
MENU_RUTINAS_y_EJERCICIOS -[#PaleGreen]-> MOSTRANDO_EJERCICIO : Mostrar Ejercicio
MENU_RUTINAS_y_EJERCICIOS -[#PaleGreen]-> BUSCANDO_RUTINA : Buscar rutina
MENU_RUTINAS_y_EJERCICIOS -[#PaleGreen]-> BUSCANDO_EJERCICIO : Buscar ejercicio
CREANDO_RUTINA -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
EDITANDO_RUTINA -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
MOSTRANDO_RUTINA -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
MOSTRANDO_EJERCICIO -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
BUSCANDO_RUTINA -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
BUSCANDO_EJERCICIO -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú

@enduml