@startuml AlumnosCasosDeUso
!define RECTANGLE(x) rectangle x

RECTANGLE(NAVEGACION_MENUS)

RECTANGLE(MENU_RUTINAS_y_EJERCICIOS)

RECTANGLE(CREANDO_RUTINA)
RECTANGLE(EDITANDO_RUTINA)
RECTANGLE(MOSTRANDO_RUTINA)
RECTANGLE(MOSTRANDO_EJERCICIO)

' === MENÚ RUTINAS Y EJERCICIOS ===
MENU_RUTINAS_y_EJERCICIOS --> CREANDO_RUTINA : Crear rutina
MENU_RUTINAS_y_EJERCICIOS --> EDITANDO_RUTINA : Editar rutina
MENU_RUTINAS_y_EJERCICIOS --> MOSTRANDO_RUTINA : Mostrar rutina
MENU_RUTINAS_y_EJERCICIOS --> MOSTRANDO_EJERCICIO : Mostrar Ejercicio
CREANDO_RUTINA --> NAVEGACION_MENUS : Cambiar menú
EDITANDO_RUTINA --> NAVEGACION_MENUS : Cambiar menú
MOSTRANDO_RUTINA --> NAVEGACION_MENUS : Cambiar menú
MOSTRANDO_EJERCICIO --> NAVEGACION_MENUS : Cambiar menú

@enduml