@startuml DiagramaDeContextoMenuPerfilAlumnos
!define RECTANGLE(x, color) rectangle x#color

RECTANGLE(NAVEGACION_MENUS, SkyBlue)
RECTANGLE(MENU_PERFIL, LightCoral)

RECTANGLE(VIENDO_INSIGNIAS, LightCoral)
RECTANGLE(INSCRIBIENDO_CLASE, LightCoral)
RECTANGLE(MOSTRANDO_QR, LightCoral)
RECTANGLE(CERRANDO_SESION, LightCoral)

' === MENÚ PERFIL ===
MENU_PERFIL -[#LightCoral]-> VIENDO_INSIGNIAS : Ver insignias
MENU_PERFIL -[#LightCoral]-> INSCRIBIENDO_CLASE : Inscribir en clase
MENU_PERFIL -[#LightCoral]-> MOSTRANDO_QR : Mostrar QR 
MENU_PERFIL -[#LightCoral]-> CERRANDO_SESION : Cerrar sesión
VIENDO_INSIGNIAS -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
INSCRIBIENDO_CLASE -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
MOSTRANDO_QR -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú
CERRANDO_SESION -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú

@enduml