@startuml DiagramaDeContextoMenuRetosAlumno
!define RECTANGLE(x, color) rectangle x #color

RECTANGLE(NAVEGACION_MENUS, SkyBlue)
RECTANGLE(MENU_RETOS, LightSalmon)

RECTANGLE(SUBIENDO_EVIDENCIA_RETO, LightSalmon)

' === MENÚ RETOS ===
MENU_RETOS -[#LightSalmon]-> SUBIENDO_EVIDENCIA_RETO : Subir evidencia de reto
SUBIENDO_EVIDENCIA_RETO -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar menú

@enduml