@startuml

[*] --> RastreadorDocumento

state Destinatario
state startDestinatario  <<start>>
startDestinatario --> Destinatario

state RastreadorDocumento {
  
  AccediendoMensaje --> ActualizandoEstadoDocumento
  ActualizandoEstadoDocumento --> AccediendoMensaje
  
  ActualizandoEstadoDocumento --> Pendiente
  ActualizandoEstadoDocumento --> Leido
  ActualizandoEstadoDocumento --> Atrasado
  ActualizandoEstadoDocumento --> Firmado
}

Destinatario -r-> AccediendoMensaje

RastreadorDocumento -d-> [*]
@enduml