@startuml

[*] --> RastreadorDocumento

state Destinatario
state startDestinatario  <<start>>
startDestinatario -l-> Destinatario

state RastreadorDocumento {
  
  ActualizandoEstadoMensaje --> AccediendoDocumento
  AccediendoDocumento -r-> ActualizandoEstadoMensaje
  
  ActualizandoEstadoMensaje --> Pendiente
  ActualizandoEstadoMensaje --> Leido
  ActualizandoEstadoMensaje --> Atrasado
  ActualizandoEstadoMensaje --> Firmado
}

Destinatario -r-> ActualizandoEstadoMensaje

RastreadorDocumento -d-> [*]
@enduml