@startuml
left to right direction

actor "Usuario No Registrado" as UsuarioNoRegistrado
actor Usuario
actor Alumno
actor Profesor
actor Admin

Usuario <|-- Alumno
Usuario <|-- Profesor
Usuario <|-- Admin

usecase "Registrarse" as UC_Registrarse
usecase "Iniciar Sesión" as UC_IniciarSesion
usecase "Cerrar Sesión" as UC_CerrarSesion
usecase "Volver al Inicio" as UC_VolverInicio

' Casos de uso de Alumno
usecase "Ver Clasificaciones" as UC_VerClasificaciones
usecase "Usar Rutinas" as UC_UsarRutinas
usecase "Completar Retos Obligatorios" as UC_CompletarRetosObligatorios
usecase "Completar Retos Opcionales" as UC_CompletarRetosOpcionales
usecase "Inscribirse en Clases" as UC_InscribirseClases
usecase "Utilizar QR para Centros Deportivos" as UC_UsarQR

' Casos de uso de Profesor
usecase "Crear Nuevas Rutinas" as UC_CrearRutinas
usecase "Crear Retos Obligatorios" as UC_CrearRetosObligatorios
usecase "Crear Retos Opcionales" as UC_CrearRetosOpcionales
usecase "Ver Clases y Alumnos" as UC_VerClasesAlumnos

' Casos de uso de Administrador
usecase "Administrar Usuarios" as UC_AdministrarUsuarios
usecase "Gestionar Clases" as UC_GestionarClases
usecase "Gestionar Rutinas" as UC_GestionarRutinas
usecase "Gestionar Retos" as UC_GestionarRetos
usecase "Administrar Asignaturas" as UC_AdministrarAsignaturas
usecase "Configuración del Sistema" as UC_ConfigurarSistema
usecase "Ver Reportes" as UC_VerReportes
usecase "Descargar Estadísticas" as UC_DescargarEstadisticas

UsuarioNoRegistrado --> UC_Registrarse

Usuario --> UC_IniciarSesion
Usuario --> UC_CerrarSesion
Usuario --> UC_VolverInicio

Alumno --> UC_VerClasificaciones
Alumno --> UC_UsarRutinas
Alumno --> UC_CompletarRetosObligatorios
Alumno --> UC_CompletarRetosOpcionales
Alumno --> UC_InscribirseClases
Alumno --> UC_UsarQR

Profesor --> UC_CrearRutinas
Profesor --> UC_CrearRetosObligatorios
Profesor --> UC_CrearRetosOpcionales
Profesor --> UC_VerClasesAlumnos

Admin --> UC_AdministrarUsuarios
Admin --> UC_GestionarClases
Admin --> UC_GestionarRutinas
Admin --> UC_GestionarRetos
Admin --> UC_AdministrarAsignaturas
Admin --> UC_ConfigurarSistema
Admin --> UC_VerReportes
Admin --> UC_DescargarEstadisticas

@enduml
