@startuml
left to right direction

usecase "Registrar" as Registrarse

usecase "Iniciar Sesión" as IniciarSesion
usecase "Cerrar Sesión" as CerrarSesion
usecase "Volver al Inicio" as VolverInicio

usecase "Ver Clasificación" as VerClasificacion
usecase "Usar Rutina" as UsarRutina
usecase "Completar Reto Obligatorio" as CompletarRetoObligatorio
usecase "Completar Reto Opcional" as CompletarRetoOpcional
usecase "Inscribir en Clase" as InscribirseClase
usecase "Mostrar QR para Centro Deportivo" as UsarQR
usecase "Crear Rutina" as CrearRutinaPersonalizada
usecase "Seleccionar Ejercicio" as SeleccionarEjercicio

usecase "Subir Ejercicio" as SubirEjercicio
usecase "Crear Reto Obligatorio" as CrearRetoObligatorio
usecase "Crear Reto Opcional" as CrearRetoOpcional
usecase "Ver Clase y Alumno" as VerClaseAlumno

usecase "Administrar Usuario" as AdministrarUsuario
usecase "Gestionar Clase" as GestionarClase
usecase "Gestionar Rutina" as GestionarRutina
usecase "Gestionar Reto" as GestionarReto
usecase "Supervisar Ejercicio" as SupervisarEjercicio
usecase "Gestionar Permiso" as GestionarPermiso
usecase "Configurar el Sistema" as ConfigurarSistema
usecase "Ver Reporte" as VerReporte
usecase "Descargar Estadística" as DescargarEstadistica


@enduml
