@startuml
left to right direction

actor "Usuario No Registrado" as UsuarioNoRegistrado
actor Usuario
actor Alumno
actor Profesor
actor Admin

Usuario <|-- Alumno
Usuario <|-- Profesor
Usuario <|-- Admin

usecase "Registrarse" as UC_Registrarse
usecase "Iniciar Sesión" as UC_IniciarSesion
usecase "Cerrar Sesión" as UC_CerrarSesion
usecase "Ver Información de Asignaturas" as UC_VerInfoAsignaturas
usecase "Consultar Calificaciones" as UC_ConsultarCalificaciones
usecase "Impartir Asignatura" as UC_ImpartirAsignatura
usecase "Gestionar Alumnos" as UC_GestionarAlumnos
usecase "Administrar Usuarios" as UC_AdministrarUsuarios
usecase "Configurar Sistema" as UC_ConfigurarSistema
usecase "Volver al inicio" as UC_VolverInicio

' Casos de uso adicionales para Profesores
usecase "Calificar Alumnos" as UC_CalificarAlumnos
usecase "Asignar Rutinas" as UC_AsignarRutinas
usecase "Evaluar Progreso" as UC_EvaluarProgreso

' Casos de uso adicionales para Alumnos
usecase "Usar Rutinas" as UC_UsarRutinas
usecase "Participar en Retos/Actividades" as UC_ParticiparRetos

UsuarioNoRegistrado --> UC_Registrarse

Usuario --> UC_IniciarSesion
Usuario --> UC_CerrarSesion
Usuario --> UC_VolverInicio

Alumno --> UC_VerInfoAsignaturas
Alumno --> UC_ConsultarCalificaciones
Alumno --> UC_UsarRutinas
Alumno --> UC_ParticiparRetos

Profesor --> UC_VerInfoAsignaturas
Profesor --> UC_ImpartirAsignatura
Profesor --> UC_GestionarAlumnos
Profesor --> UC_CalificarAlumnos
Profesor --> UC_AsignarRutinas
Profesor --> UC_EvaluarProgreso

Admin --> UC_AdministrarUsuarios
Admin --> UC_ConfigurarSistema

@enduml
