@startuml
left to right direction
actor Profesor

package "Rutinas y Ejercicios" {

    package "Rutinas" {
        usecase "Ver Rutinas Disponibles" as VerRutinasDisponibles
        usecase "Buscar Rutina" as BuscarRutina
        usecase "Crear Rutina" as CrearRutina
        usecase "Ver Rutina Específica" as VerRutinaEspecifica

        usecase "Editar Rutina" as EditarRutina
        usecase "Ver Ejercicios en Rutina" as VerEjerciciosEnRutina
        usecase "Buscar Ejercicio en Rutina" as BuscarEjercicioEnRutina
        
    }

    package "Ejercicios" {
        usecase "Buscar Ejercicio" as BuscarEjercicio
        usecase "Ver Ejercicios Disponibles" as VerEjerciciosDisponibles
        usecase "Crear Ejercicio" as CrearEjercicio

        usecase "Ver Ejercicio Específico" as VerEjercicioEspecifico
        usecase "Editar Ejercicio" as EditarEjercicio
    }
}

package "Retos" {
    package "Obligatorios" {
        usecase "Ver Retos Obligatorios" as VerRetosObligatorios
        usecase "Crear Reto Obligatorio" as CrearRetoObligatorio
        usecase "Editar Reto Obligatorio" as EditarRetoObligatorio
    }

    package "Opcionales" {
        usecase "Ver Retos Opcionales" as VerRetosOpcionales
        usecase "Crear Reto Opcional" as CrearRetoOpcional
        usecase "Editar Reto Opcional" as EditarRetoOpcional
    }

    usecase "Asignar Reto a Clase" as AsignarRetoAClase
}

package "Clasificación" {
    usecase "Ver Clasificación de Clases" as VerClasificacionClases
    usecase "Ver Clasificación de Alumnos" as VerClasificacionAlumnos
    VerClasificacionClases --> VerClasificacionAlumnos : <<include>>
}

package "Perfil" {
    usecase "Cerrar Sesión" as CerrarSesion
    usecase "Crear Clase" as CrearClase
    usecase "Mostrar QR Centros Deportivos" as MostrarQRCentros
    usecase "Ver Mis Clases" as VerMisClases

    package "Mis Clases" {
        usecase "Ver Alumnos" as VerAlumnosEnClase

        package "Alumnos" {
            usecase "Ver Retos del Alumno" as VerRetosDelAlumno
            usecase "Evaluar Reto" as EvaluarReto
        }
    }
}

usecase "Iniciar Sesión" as IniciarSesion

Profesor --> IniciarSesion
Profesor --> VerRutinasDisponibles
Profesor --> BuscarRutina
Profesor --> CrearRutina
Profesor --> VerEjerciciosDisponibles
Profesor --> BuscarEjercicio
Profesor --> CrearEjercicio
Profesor --> VerRetosObligatorios
Profesor --> CrearRetoObligatorio
Profesor --> EditarRetoObligatorio
Profesor --> VerRetosOpcionales
Profesor --> CrearRetoOpcional
Profesor --> EditarRetoOpcional
Profesor --> VerClasificacionClases
Profesor --> CerrarSesion
Profesor --> CrearClase
Profesor --> MostrarQRCentros
Profesor --> VerMisClases

VerRutinasDisponibles --> VerRutinaEspecifica : <<include>>
VerRutinaEspecifica --> CrearEjercicio : <<include>>
VerRutinaEspecifica --> VerEjerciciosEnRutina : <<include>>
VerRutinaEspecifica --> EditarRutina : <<include>>
VerRutinaEspecifica --> BuscarEjercicioEnRutina : <<include>>


VerEjerciciosEnRutina --> VerEjercicioEspecifico : <<include>> 
VerEjercicioEspecifico --> EditarEjercicio : <<include>>       

CrearRutina --> BuscarEjercicio : <<include>>


VerEjerciciosDisponibles --> VerEjercicioEspecifico : <<include>>

CrearRetoObligatorio --> AsignarRetoAClase : <<include>>
CrearRetoOpcional --> AsignarRetoAClase : <<include>>

VerMisClases --> VerAlumnosEnClase : <<include>>
VerAlumnosEnClase --> VerRetosDelAlumno : <<include>>
VerRetosDelAlumno --> EvaluarReto : <<include>>

@enduml
