@startuml
left to right direction

actor Alumno

usecase "Ver Clasificacion" as VerClasificaciones
usecase "Usar Rutina" as UsarRutinas
usecase "Completar Reto Obligatorio" as CompletarRetosObligatorios
usecase "Completar Reto Opcional" as CompletarRetosOpcionales
usecase "Inscribirse en Clase" as InscribirseClases
usecase "Mostrar QR para Centros Deportivos" as UsarQR
usecase "Iniciar Sesión" as IniciarSesion
usecase "Cerrar Sesión" as CerrarSesion
usecase "Volver al Inicio" as VolverInicio
usecase "Crear Rutina" as CrearRutinaPersonalizada
usecase "Seleccionar Ejercicio" as SeleccionarEjercicios

Alumno --> VerClasificaciones
Alumno --> UsarRutinas
Alumno --> CompletarRetosObligatorios
Alumno --> CompletarRetosOpcionales
Alumno --> InscribirseClases
Alumno --> UsarQR
Alumno --> IniciarSesion
Alumno --> CerrarSesion
Alumno --> VolverInicio
Alumno --> CrearRutinaPersonalizada

CrearRutinaPersonalizada --> SeleccionarEjercicios : <<include>>

@enduml
