@startuml CdU_Alumno
left to right direction

actor Alumno

package "Rutinas y Ejercicios" {
    usecase "Ver rutinas y ejercicios" as IrARutinasYEjercicios

   
        usecase "Mostar Rutina" as MostrarRutina
        usecase "Crear Rutina" as CrearRutina
        usecase "Editar Rutina" as EditarRutina
        usecase "Buscar Rutina" as BuscarRutina
        usecase "Mostrar Ejercicio" as MostrarEjercicio
        usecase "Buscar Ejercicio" as BuscarEjercicio
    
}

package Retos {
    usecase "Ver Retos" as IrARetos
    usecase "Mostrar Reto" as MostrarReto
    usecase "Subir Evidencia de Reto" as SubirEvidencia
}

package Clasificacion {
    usecase "Ver Clasificacion" as IrAClasificacion
}

package Perfil {
    usecase "Ver Perfil" as IrAPerfil
    usecase "Inscribir en Clase" as InscribirEnClase
    usecase "Mostrar QR" as MostrarQRCentros
    usecase "Ver Insignias" as VerInsignias
    usecase "Cerrar Sesion" as CerrarSesion
}

usecase "Ingresar al Sistema" as IngresarAlSistema
usecase "Iniciar Sesion" as IniciarSesion

usecase "Cambiar Menu" as CambiarMenu

Alumno --> IngresarAlSistema
Alumno --> IniciarSesion
Alumno --> CerrarSesion
Alumno --> CambiarMenu

Alumno --> IrARutinasYEjercicios
Alumno --> MostrarRutina
Alumno --> CrearRutina
Alumno --> EditarRutina
Alumno --> MostrarEjercicio
Alumno --> BuscarEjercicio
Alumno --> BuscarRutina

Alumno --> IrARetos
Alumno --> SubirEvidencia

Alumno --> IrAClasificacion

Alumno --> IrAPerfil
Alumno --> InscribirEnClase
Alumno --> MostrarQRCentros
Alumno --> VerInsignias

@enduml
