@startuml
left to right direction

actor Admin

usecase "Administrar Usuario" as AdministrarUsuarios
usecase "Gestionar Clase" as GestionarClases
usecase "Gestionar Rutina" as GestionarRutinas
usecase "Gestionar Reto" as GestionarRetos
usecase "Supervisar Ejercicio" as SupervisarEjercicios

usecase "Gestionar Permiso" as GestionarPermisos
usecase "Configurar el Sistema" as ConfigurarSistema
usecase "Ver Reporte" as VerReportes
usecase "Descargar Estadística" as DescargarEstadisticas

Admin --> AdministrarUsuarios
Admin --> GestionarClases
Admin --> GestionarRutinas
Admin --> GestionarRetos

Admin --> SupervisarEjercicios
Admin --> GestionarPermisos
Admin --> ConfigurarSistema
Admin --> VerReportes
Admin --> DescargarEstadisticas

@enduml
