@startuml CdU_Profesor
left to right direction
actor Profesor

package "Rutinas y Ejercicios" {
    usecase "Ver Rutinas y Ejercicios" as CambiarARutinasYEjercicios

   
        usecase "Mostrar Rutina" as MostrarRutina
        usecase "Editar Rutina" as EditarRutina
        usecase "Crear Rutina" as CrearRutina
    

   
        usecase "Mostrar Ejercicio" as MostrarEjercicio
        usecase "Editar Ejercicio" as EditarEjercicio
        usecase "Crear Ejercicio" as CrearEjercicio
    
}

package "Retos" {
    usecase "Ver Retos" as CambiarARetos
    usecase "Crear Reto" as CrearReto
    usecase "Editar Reto" as EditarReto
}

package "Clasificación" {
    usecase "Ver Clasificación" as CambiarAClasificacion
    usecase "Ver alumnos dentro  de clase" as VerAlumnosDentroDeClase
}

package "Perfil" {
    usecase "Ver Perfil" as CambiarAPerfil
    usecase "Mostrar QR en centro deportivo" as MostrarQR

  
        usecase "Crear Clase" as CrearClase
        usecase "Ver mis clases" as VerMisClases
        usecase "Ver alumnos" as VerAlumnos
        usecase "Ver retos alumnos" as VerRetosAlumnos
        usecase "Evaluar retos" as EvaluarRetos
        usecase "Cerrar Sesión" as CerrarSesion
    
}


usecase "Iniciar Sesión" as IniciarSesion
usecase "Ingresar al Sistema" as IngresarAlSistema
usecase "Cambiar Menu" as CambiarMenu

Profesor --> IngresarAlSistema
Profesor --> IniciarSesion
Profesor --> CambiarMenu
Profesor --> CerrarSesion

Profesor --> CambiarARutinasYEjercicios
Profesor --> MostrarRutina
Profesor --> EditarRutina
Profesor --> CrearRutina
Profesor --> MostrarEjercicio
Profesor --> EditarEjercicio
Profesor --> CrearEjercicio

Profesor --> CambiarARetos
Profesor --> CrearReto
Profesor --> EditarReto

Profesor --> CambiarAClasificacion
Profesor --> VerAlumnosDentroDeClase

Profesor --> CambiarAPerfil
Profesor --> MostrarQR
Profesor --> CrearClase
Profesor --> VerMisClases
Profesor --> VerAlumnos
Profesor --> VerRetosAlumnos
Profesor --> EvaluarRetos

@enduml
