@startuml diagramaDeEstados

[*] --> LeyendoMensaje: Abrir Mensaje

LeyendoMensaje --> LeyendoDocumento: Seleccionar documento


state confirmandoDocumento <<choice>> 
confirmandoDocumento --> LeyendoDocumento: - Confirmar vista del documento
confirmandoDocumento --> LeyendoDocumento: - Confirmar vista y firma del documento

LeyendoDocumento --> confirmandoDocumento : Seleccionar Confirmacion

LeyendoDocumento --> LeyendoMensaje : Elegir documento

LeyendoMensaje --> [*]: Cerrar Mensaje

@enduml