@startuml diagramaDeEstados

[*] --> LeyendoMensaje: Abrir Mensaje

LeyendoMensaje -l-> LeyendoDocumento: Seleccionar documento


state confirmandoMensaje <<choice>> 
state firmandoMensaje <<choice>> 
confirmandoMensaje --> LeyendoMensaje: - Confirmar vista del mensaje
confirmandoMensaje --> firmandoMensaje: - Confirmar vista y firma del mensaje
firmandoMensaje --> LeyendoMensaje

LeyendoMensaje --> confirmandoMensaje : Seleccionar Confirmación

LeyendoMensaje -r-> [*]: Cerrar Mensaje

@enduml