@startuml diagramaDeEstados

[*] --> LeyendoMensaje: Abrir Mensaje

LeyendoMensaje --> LeyendoDocumento: Seleccionar documento


state confirmandoDocumento <<choice>> 
state firmandoDocumento <<choice>> 
confirmandoDocumento --> LeyendoDocumento: - Confirmar vista del documento
confirmandoDocumento --> firmandoDocumento: - Confirmar vista y firma del documento
firmandoDocumento --> LeyendoDocumento

LeyendoDocumento --> confirmandoDocumento : Seleccionar Confirmacion

LeyendoDocumento --> LeyendoMensaje : Elegir documento

LeyendoMensaje --> [*]: Cerrar Mensaje

@enduml