@startuml diagramaDeEstados

[*] --> CreandoMensaje: Crear un nuevo mensaje

CreandoMensaje : - Añadir Destinatario
CreandoMensaje : - Añadir Asunto
CreandoMensaje : - Añadir Documentos

CreandoMensaje --> SeleccionandoConfirmacion: Seleccionar tipo de documento

state SeleccionandoConfirmacion <<Choice>>
state SeleccionandoConfirmacion2 <<Choice>>
    SeleccionandoConfirmacion --> CreandoMensaje: - Se requiere vista del documento
    SeleccionandoConfirmacion --> SeleccionandoConfirmacion2: - Se requiere vista y firma del documento
    SeleccionandoConfirmacion2 --> CreandoMensaje

CreandoMensaje --> CreandoEnvio
CreandoEnvio --> EnviandoMensaje
EnviandoMensaje --> [*]

@enduml