@startuml Proceso_de_Edicion_Profesor
title Proceso de Edición de Contenido - Profesor

[*] --> EdicionEnProgreso
EdicionEnProgreso : El profesor actualiza y guarda cambios

EdicionEnProgreso --> RevisionInterna : Finaliza cambios
RevisionInterna : Revisión preliminar realizada por el profesor

RevisionInterna --> EnviadoParaRevision : Enviar al Director de Grado
EnviadoParaRevision : Envío para revisión

EnviadoParaRevision --> DevueltoParaModificaciones
EnviadoParaRevision --> Aprobada 
Aprobada : Aprobada por el Director de Grado
DevueltoParaModificaciones --> EdicionEnProgreso

Aprobada --> [*] : Fin de la edición


@enduml
