@startuml diagramaContextoManejoAcciones
state "MENU_PRINCIPAL" as MenuPrincipal
state "LISTANDO_ACCIONES" as Acciones
state "DETALLANDO_ACCION" as AccionDetallada

[*] --> MenuPrincipal

MenuPrincipal --> Acciones
    note on link
        Listar acciones
    end note

Acciones --> AccionDetallada
    note on link
        Ver detalle 
    end note

AccionDetallada --> Acciones
    note on link
        Listar
        acciones
    end note

Acciones --> MenuPrincipal
    note on link
        Abrir Menú Principal
    end note
@enduml