@startuml
hide empty members
hide circle
abstract "Admin1:Remitente"{
    Name: "John"
    Email: "john@doe.com"
    Password: "password"
    Status: "active"
    SendMessage()
    AttachDocs()
    CheckInboxInfo()
}

class "Mensaje:Mensaje"{
    Subject: "Subject"
    Recipients: "ibuprofeno@uneatlantico.es"
    Body: "Body"
    Attachments: RastreadorDocumento()
}

class "Rastreador:RastreadorDocumento"{
    Documento()
    Status: "Sent"
}

class "Documento:Documento"{
    Attachments: "Documents.pdf"
}

abstract "User1:Receptor"{
    Name: "Juan"
    Email: "juan@perez.com"
    Password: "contraseña"
    Status: "active"
    CheckInboxInfo()
    SignDocuments()
    ConfirmReadDocument()
}

"Admin1:Remitente" "1"--"*" "Mensaje:Mensaje" : genera

"Mensaje:Mensaje" "1"--"*" "Rastreador:RastreadorDocumento" : contiene

"Mensaje:Mensaje" "1"-r-"*" "User1:Receptor" : se envía

"Rastreador:RastreadorDocumento" "1"--"1" "Documento:Documento" : adjunta
@enduml

// Tipo de mensaje es definido por el mensaje o por el documento (PENDIENTE)