@startuml Diagrama_de_Estados_Administrador
skinparam defaultTextAlignment center

[*] --> UsuarioAdministrador: se crea administrador

state UsuarioAdministrador{
  [*]-->Activo: necesita gestionar postulantes, ver estadísticas, gestionar pruebas y capacitaciones
  Activo-->CreaPostulantes
  Activo-->EliminaPostulantes
  Activo-->DesactivaPostulantes
  
  Activo-->ActualizaPostulantes
  state acción <<choice>> : cumple los requisitos
  ActualizaPostulantes-->acción : pasa a ser becario
  acción-->CreaBecario : si
  acción-->EliminaPostulante : no
  Activo-->RevisaEstadísticasFinales
  Activo -r-> Inactivo
  Inactivo -l-> Activo
}

@enduml