@startuml Diagrama_de_Estados_Sede
skinparam defaultTextAlignment center

[*] --> UsuarioSede: se crea administrador

state UsuarioSede{
  [*]-->Activo: necesita gestionar postulantes y ver estadísticas
  Activo-->CreaPostulantes
  Activo-->EliminaPostulantes
  Activo-->DesactivaPostulantes
  Activo-->ActualizaPostulantes
  Activo-->RevisaEstadísticasFinales
  Activo -r-> Inactivo
  Inactivo -l-> Activo
}

@enduml