@startuml
state UsuarioBecario {
  [*] -d-> Registro

  State Registro {
    CompletarFormulario -d-> EnEspera
    EnEspera -r-> Aprobado : "Formulario revisado"
    EnEspera -r-> Rechazado : "Formulario no cumple"
  }

  State Evaluacion {
    EvaluarPruebas -d-> EnCurso
    EnCurso -r-> Resultados : "Pruebas finalizadas"
    Resultados -u-> Aprobado : "Candidato aprueba"
    Resultados -u-> Rechazado : "Candidato no aprueba"
  }

  State Capacitacion {
    InicioCapacitacion -d-> EnCursoCapacitacion
    EnCursoCapacitacion -r-> FinalizadoCapacitacion
    FinalizadoCapacitacion -l-> [*] : "Finaliza capacitación"
  }

  Registro -d-> Evaluacion : "Formulario aprobado"
  Evaluacion -d-> Capacitacion : "Candidato aprueba"
  Evaluacion -r-> [*] : "Candidato no aprueba"
}
@enduml
