@startuml
state Administrador {
  [*] -d-> Inicio

  State GestionarBecarios {
    VerSolicitudes -d-> EnRevisión
    EnRevisión -r-> Aprobado : "Solicitud aprobada"
    EnRevisión -r-> Rechazado : "Solicitud rechazada"
  }

  State GestionarCapacitaciones {
    CrearCapacitacion -d-> EnCurso
    EnCurso -r-> Finalizada
  }

  Inicio -d-> GestionarBecarios
  Inicio -d-> GestionarCapacitaciones
}
@enduml
