@startuml
title Casos de Uso: Consultar Estadísticas

actor Administrador
actor Seleccionador

folder "Gestión de Estadísticas" as Estadisticas {
    Administrador --> (Consultar estadísticas)
    Seleccionador --> (Consultar estadísticas)
}

note right of (Consultar estadísticas)
    Permite consultar datos
    relevantes sobre el avance
    o resultados del sistema.
end note
@enduml
