@startuml
title Caso de uso: Ver Progreso de Capacitación

skinparam {
    NoteBackgroundColor #lightYellow
    ArrowColor #blue
    NoteBorderColor #blue
    linetype polyline
}

state startState as "PÁGINA PRINCIPAL"
state endState as "PÁGINA PRINCIPAL"

startState --> VerProgresoCapacitacion
note on link
    <b>Usuario Accede</b>
    * Selecciona una capacitación de la lista
end note

VerProgresoCapacitacion --> MostrarProgreso
note on link
    <b>Sistema Muestra</b>
    * Porcentaje completado
    * Actividades realizadas y pendientes
end note

MostrarProgreso --> endState
note on link
    <b>Usuario Termina</b>
    * Regresa a la página principal
end note
@enduml
