@startuml diagrama_contexto_postulante

state "NO_AUTENTICADO" as NoAuth
state "MENU_PRINCIPAL" as Menu
state "TEST" as Test

state "CAPACITACIÓN" as Capacitacion {
    state "SELECCIÓN_CAPACITACIÓN" as SeleccionCap
    state "EN_CURSO" as EnCurso
    state "COMPLETADA" as Completada
    
    [*] --> SeleccionCap
    SeleccionCap --> EnCurso : Iniciar capacitación
    EnCurso --> Completada : Completar módulos
    Completada --> SeleccionCap : Seleccionar nueva\ncapacitación
}

[*] --> NoAuth

NoAuth --> Menu
    note on link
        Iniciar sesión
    end note

Menu --> NoAuth
    note on link
        Cerrar sesión
    end note

Menu --> Test
    note on link
        Realizar test
    end note

Menu --> Capacitacion
    note on link
        Realizar capacitación
    end note

Capacitacion --> Menu
    note on link
        Volver al menú
    end note

Test --> Menu
    note on link
        Finalizar test
    end note

@enduml
