@startuml

state "NO_AUTENTICADO" as NoAuth
state "MENU_USUARIOS" as Menu_usuarios
state "MENU_ADMINISTRADOR" as Menu_administrador
state "CREAR_USUARIO" as Crear_usuario
state "VER_USUARIO" as Ver_usuario
state "EDITAR_USUARIO" as Editar_usuario
state "ELIMINAR_USUARIO" as Eliminar_usuario
state "CREAR_TEST" as Crear_test
state "VER_TEST" as Ver_test
state "EDITAR_TEST" as Editar_test
state "ELIMINAR_TEST" as Eliminar_test
state "CREAR_CAPACITACIÓN" as Crear_capacitación
state "VER_CAPACITACIÓN" as Ver_capacitación
state "EDITAR_CAPACITACIÓN" as Editar_capacitación
state "ELIMINAR_CAPACITACIÓN" as Eliminar_capacitación
state "CONSULTAR_ESTADÍSTICAS" as Consultar_estadísticas



[*] --> NoAuth

NoAuth --> Menu_usuarios
    note on link
        Iniciar sesión
    end note

Menu_usuarios --> NoAuth
    note on link
        Cerrar sesión
    end note

Menu_usuarios --> Crear_usuario
    note on link
        Insertar registro
    end note

Crear_usuario --> Menu_usuarios
    note on link
        Guardar
    end note

Menu_usuarios --> Editar_usuario
    note on link
        Actualizar registro
    end note

Editar_usuario --> Menu_usuarios
    note on link
        Guardar
    end note

Menu_usuarios --> Ver_usuario
    note on link
        Ver lista
    end note

Ver_usuario --> Menu_usuarios
    note on link
        Salir
    end note

Menu_usuarios --> Eliminar_usuario
    note on link
        Borrar usuario
    end note

Eliminar_usuario --> Menu_usuarios
    note on link
        Guardar
    end note

NoAuth --> Menu_administrador
    note on link
        Iniciar sesión
    end note

Menu_administrador --> NoAuth
    note on link
        Cerrar sesión
    end note

Menu_administrador --> Crear_test
    note on link
        Insertar registro
    end note

Crear_test --> Menu_administrador
    note on link
        Guardar
    end note

Menu_administrador --> Editar_test
    note on link
        Actualizar registro
    end note

Editar_test --> Menu_administrador
    note on link
        Guardar
    end note

Menu_administrador --> Ver_test
    note on link
        Ver lista
    end note

Ver_test --> Menu_administrador
    note on link
        Salir
    end note

Menu_administrador --> Eliminar_test
    note on link
        Borrar test
    end note

Eliminar_test --> Menu_administrador
    note on link
        Guardar
    end note

Menu_administrador --> Crear_capacitación
    note on link
        Insertar registro
    end note

Crear_capacitación --> Menu_administrador
    note on link
        Guardar
    end note

Menu_administrador --> Editar_capacitación
    note on link
        Actualizar registro
    end note

Editar_capacitación --> Menu_administrador
    note on link
        Guardar
    end note

Menu_administrador --> Ver_capacitación
    note on link
        Ver lista
    end note

Ver_capacitación --> Menu_administrador
    note on link
        Salir
    end note

Menu_administrador --> Eliminar_capacitación
    note on link
        Borrar capacitación
    end note

Eliminar_capacitación --> Menu_administrador
    note on link
        Guardar
    end note

Menu_administrador --> Consultar_estadísticas
    note on link
        Ver estadísticas
    end note

Consultar_estadísticas --> Menu_administrador
    note on link
        Salir
    end note

@enduml