@startuml
left to right direction

actor "Ordenación" as ord

usecase "Asignar Carga Docente" as asignarCarga
note top of asignarCarga
    De asignaturas
    a profesores
end note

ord --> asignarCarga
@enduml