@startuml
left to right direction

actor "Técnico Calidad" as tec

usecase "Asignar Valores en Memoria" as asignarValores
note top of asignarValores
    Valores consignados en
    Memoria por Titulación
end note

note "Permitir validar datos\ndel año anterior" as valoresDef

tec ---> asignarValores
@enduml