@startuml
left to right direction

actor "Ordenación" as ord
actor "Administrador" as admin

usecase "Asignar Carga Docente" as asignarCarga
note top of asignarCarga
    De asignaturas
    a profesores
end note

ord --> asignarCarga
admin --> asignarCarga
@enduml