@startuml
left to right direction

actor "Ordenación" as ord
actor "Administrador" as admin

package "Carga Docente" as cargaDocentePackage {
    usecase "Asignar Carga" as asignarCarga
    note right of asignarCarga
        De asignaturas
        a profesores
    end note
}

ord ---> asignarCarga
admin ---> asignarCarga
@enduml