@startuml
left to right direction

actor "Administrador" as admin

usecase "Consultar Claustro" as consClaustro
note top of consClaustro
    Listado PDI asociado
    a una titulación, anual,
    por semestre
end note

admin --> consClaustro
@enduml