@startuml
left to right direction

actor "RRHH" as rrhh
actor "Administrador" as admin
actor "Ordenación" as ord
actor "Técnico Calidad" as tec

package "Claustro Docente" as claustroPackage {
    usecase "Consultar" as consClaustro
    note right of consClaustro
        Listado PDI asociado
        a una titulación, anual,
        por semestre
    end note
}

rrhh --> consClaustro
admin --> consClaustro
ord --> consClaustro
tec --> consClaustro
@enduml