@startuml
left to right direction

actor "Profesor" as prof

usecase "Consultar Datos Personales" as consultaValores
note top of consultaValores
    Consultar valores asignados
    de contrato y otros datos
    personales
end note

prof --> consultaValores
@enduml