@startuml
left to right direction

actor "Administrador" as admin

usecase "Consultar Asignación por Profesor" as consProf
note top of consProf
    Consultar asignación
    docente por profesor
    (créditos y asignaturas)
end note

admin --> consProf
@enduml