@startuml
left to right direction

actor "Profesor" as prof

usecase "Consultar Asignación Docente" as consAsig
note top of consAsig
    Consulta de sus asignaciones
    docentes (por titulación,
    por curso y por semestre) 
end note

prof --> consAsig
@enduml