@startuml
left to right direction

skinparam usecase {
    FontSize 20
}

skinparam nodesep 170

actor "Técnico Calidad" as tec
actor "Administrador" as admin

package "Informes" as informes {
    usecase "Emitir Informe" as emitirInforme
    package "Tipos de Informes" {
        usecase "por Titulación" as titulacion
        usecase "Global" as global
    }
    note top of emitirInforme
        Emitir Informe
        del Profesorado
    end note
}

emitirInforme ..> titulacion
emitirInforme ..> global

tec ---> emitirInforme
admin ---> emitirInforme
@enduml