@startuml
left to right direction

actor "Profesor" as profesor
actor "Administrador" as administrador

usecase "Iniciar Sesión" as inicioSesion

profesor --> inicioSesion
administrador --> inicioSesion
@enduml