@startuml
left to right direction

actor "Profesores" as prof

usecase "Introducir Datos Académicos" as datosAcad
note top of datosAcad
    Experiencia docente, profesional,
    investigadora, sexenios, acreditaciones,
    y movilidad y titulación profesional
end note

note "Permitir heredar datos\ndel año anterior" as notaDatosAcad

prof --> datosAcad
@enduml