@startuml
left to right direction

actor "RRHH" as rrhh
actor "Administrador" as admin

usecase "Introducir Datos Laborales" as datosLab
note top of datosLab
    Datos de contrato de los profesores,
    horas y temporalidad y categoría
    profesional de contrato
end note

note "Permitir heredar datos\ndel año anterior" as notaDatosLab

rrhh --> datosLab
admin --> datosLab
@enduml