@startuml
left to right direction

actor "RRHH" as rrhh
actor "Administrador" as admin

usecase "Modificar Datos del Profesorado" as modDatos
note top of modDatos
    Datos introducidos previamente
    por el profesorado
end note

rrhh --> modDatos
admin --> modDatos
@enduml