@startuml
left to right direction

actor "RRHH" as rrhh
actor "Administrador" as admin

package "Gestión Datos" as gestDatosPackage {
    usecase "Modificar Datos" as modDatos
    note "Datos introducidos previamente\npor el profesorado" as notaGestDatos
}

rrhh --> modDatos
admin --> modDatos
@enduml