@startuml
left to right direction

actor "Técnico Calidad" as tec
actor "Administrador" as admin

package "Indicadores" as indicadores {
    usecase "Obtener indicadores" as obtenerIndicadores
    note top of obtenerIndicadores
    Para Sistema de Gestión
    end note
}

tec --> obtenerIndicadores
admin --> obtenerIndicadores
@enduml