@startuml
left to right direction

actor "RRHH" as rrhh
actor "Administrador" as admin

usecase "Validar Datos del Profesorado" as valDatos
note top of valDatos
    Datos introducidos previamente
    por el profesorado
end note

rrhh --> valDatos
admin --> valDatos
@enduml