@startuml
left to right direction

actor "Ordenación" as ord
actor "Administrador" as admin

package "Validación Memoria" as valMemPackage {
    usecase "Validar Cumplimiento" as valCumpli1
    note top
        Validar cumplimiento de
        valores consignados en la
        memoria por titulacion
    end note
}

ord --> valCumpli1
admin --> valCumpli1
@enduml