@startuml
left to right direction

actor "RRHH" as rrhh

usecase "Validar Datos del Profesorado" as valDatos
note top of valDatos
    Datos introducidos previamente
    por el profesorado
end note

rrhh --> valDatos
@enduml