@startuml
left to right direction

actor "Técnico Calidad" as tec
actor "Administrador" as admin
actor "Ordenación" as ord

package "Validación Memoria" as valMemPackage {
    usecase "Validar Cumplimiento" as valCumpli1
    note top
        Validar cumplimiento de
        compromisos de memoria con
        los valores de la titulación
    end note
}
ord --> valCumpli1
tec --> valCumpli1
admin --> valCumpli1
@enduml