@startuml diagramaContextoUsuario
state "MENU_PRINCIPAL" as MenuPrincipal
state "LISTANDO_MENSAJES" as ListandoMensaje
state "LISTANDO_GRUPOS" as Grupos
state "LISTANDO_USUARIOS" as Usuarios

[*] --> MenuPrincipal
    note on link
        Usuario 
        inicia sesión
    end note

MenuPrincipal -> [*]
    note on link
        Usuario 
        cierra sesión
    end note

MenuPrincipal --> ListandoMensaje
    note on link
        Listar mensajes
    end note

ListandoMensaje --> MenuPrincipal
    note on link
        Abrir Menú Principal
    end note

MenuPrincipal --> Grupos
    note on link
        Listar grupos
    end note

Grupos --> MenuPrincipal
    note on link
        Abrir Menú Principal
    end note

MenuPrincipal --> Usuarios
    note on link
        Listar usuarios
    end note

Usuarios--> MenuPrincipal
    note on link
        Abrir Menú Principal
    end note

@enduml