@startuml
start
:Profesor;
:Seleccionar la opción "Consultar Asignación Por Varios";
:Seleccionar criterios de filtrado;

if (¿Hay filtros seleccionados?) then (sí)
  :Solicitar parámetros de filtrado\n(Curso/Titulación/Semestre);
  :Ingresar parámetros seleccionados;
  :Buscar asignaciones según los\nfiltros especificados;
else (no)
  :Ignorar filtros;
endif

:Combinar resultados de los filtros aplicados;
:Mostrar resultados al usuario;

if (¿Desea realizar otra consulta?) then (sí)
  ->restart
else (no)
  stop
endif
@enduml