@startuml

title Automatización de Guías Docentes - Diagrama de Casos de Uso

left to right direction

actor Profesor
actor "Director de Grado" as DirectorGrado
actor "Técnico de Calidad" as TecnicoCalidad
actor "Dirección de Calidad" as DireccionCalidad

usecase "Editar Contenido de la Guía" as EditarGuia
usecase "Enviar Guía Docente para Revisión" as EnviarGuia

usecase "Revisar Contenido" as RevisarContenido
usecase "Auditar Guías Docentes" as AuditarGuias
usecase "Generar Nueva Versión de la Guía" as GenerarVersion
usecase "Asignar Guías Docentes a Profesor" as AsignarGuiaProfesor
usecase "Asignar Guía a Titulación" as AsignarGuiaTitulacion
usecase "Asignar Asignatura a Titulación" as AsignarAsignaturaTitulacion
usecase "Editar Plantilla de la Guía Docente" as EditarPlantilla
usecase "Publicar Guía Docente" as PublicarGuia
usecase "Verificar Cumplimiento con Memoria Verificada" as VerificarMemoria
usecase "Ver Listado de Estados de las Guías Docentes" as VerEstadosGuias
usecase "Ver Listado de Estados de las Guías Docentes de un Grado" as VerEstadosGuiasGrado

Profesor --> EditarGuia
Profesor --> EnviarGuia

DirectorGrado --> RevisarContenido
DirectorGrado --> PublicarGuia
DirectorGrado --> VerEstadosGuiasGrado
TecnicoCalidad --> GenerarVersion
TecnicoCalidad --> AsignarGuiaProfesor
TecnicoCalidad --> AsignarGuiaTitulacion
TecnicoCalidad --> AsignarAsignaturaTitulacion
TecnicoCalidad --> EditarPlantilla
TecnicoCalidad --> VerEstadosGuias
DireccionCalidad --> AuditarGuias
DireccionCalidad --> VerificarMemoria

@enduml
