@startuml
title Diagrama de estados de Horario
state "HorarioCreado"
state "AsignaturasVinculadas"
state "Confirmado"
state "Cancelado"

[*] --> HorarioCreado
HorarioCreado --> AsignaturasVinculadas: Vincular todas las asignaturas
AsignaturasVinculadas --> Confirmado : Confirmar horario
HorarioCreado --> Cancelado : Cancelar operación
AsignaturasVinculadas --> Cancelado : Cancelar operación
Confirmado --> [*] : Operación completada
Cancelado --> [*] : Operación cancelada
@enduml