@startuml
class Horario {
}

class HorarioAsignaturaAula {
}

class Aula {
}

package "AsignaturaGradoPorfesor" {

  class AsignaturaGradoProfesor {
  }

  class AsignaturaGrado {
  }

  class Profesor {
  }

  class Grado {
  }

  class Asignatura {
  }
  
  AsignaturaGradoProfesor -- AsignaturaGrado
  AsignaturaGradoProfesor -- Profesor
  AsignaturaGrado -- Grado
  AsignaturaGrado -- Asignatura
  Asignatura -- Profesor
}

Horario -- HorarioAsignaturaAula
HorarioAsignaturaAula -- Aula
HorarioAsignaturaAula -- AsignaturaGradoProfesor
@enduml