@startuml
title Diagrama de Clases - Horario

class Administrador {
    - listaHorarios
}
class Profesor {
    - nombre
    - apellido
}
class Asignatura {
    - id
    - nombre
}
class Aula {
    - numero
}
class Horario {
    - dia
    - listaHoraClase
}
class HoraClase {
    - hora
    - asignatura
    - aula
}
class ProfesorImparte {
    - profesor
    - asignatura
}

Administrador -- Horario
Horario -- HoraClase
HoraClase -- Asignatura
HoraClase -- Aula
Profesor -- HoraClase
Profesor -- ProfesorImparte
Asignatura -- ProfesorImparte

@enduml
