@startuml
package "AGP" {
  class Grado {
    - idGrado : int
    - nombre : String
  }

  class Asignatura {
    - idAsignatura : int
    - nombre : String
    - creditos : float
  }

  class AsignaturaGrado {
    - idGrupo : int
    - idAsignatura : int
    - idGrado : int
    - nombreGrupo : String
  }

  class AsignaturaGradoProfesor {
    - idAsignaturaGrupoProfesor : int
    - idAsignaturaGrupo : int
    - idProfesor : int
  }

  class Profesor {
    - idProfesor : int
    - nombre : String
    - apellido : String
    - email : String
  }
  
  Asignatura --> Profesor
  Grado --> AsignaturaGrado
  Asignatura --> AsignaturaGrado
  AsignaturaGrado --> AsignaturaGradoProfesor
  Profesor --> AsignaturaGradoProfesor
}

class Horario {
  - idHorario : int
  - dia : String
  - horaInicio : Time
  - horaFin : Time
}

class HorarioAsignaturaAula {
  - idHorarioAsignaturaAula : int
  - idAsignaturaGrupoProfesor : int
  - idHorario : int
  - idAula : int
}

class Aula {
  - idAula : int
  - nombre : String
  - capacidad : int
}

AsignaturaGradoProfesor --> Horario
Horario *-- HorarioAsignaturaAula
Aula --> HorarioAsignaturaAula
"AGP" --> HorarioAsignaturaAula
@enduml
