@startuml
title Casos de Uso (Usuario) - Cerrar Sesión

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

left to right direction

actor Usuario

folder "Autenticación" as autenticacion {
    Usuario --> (Cerrar Sesión)
}

@enduml
