@startuml

title Cerrar Sesión

skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "NOVUS"
state endState as "NOVUS"

startState --> CerrarSesión
note on link
    <b>Usuario Solicita</b>
    * Cerrar Sesión en Novus
end note

CerrarSesión --> endState

state CerrarSesión {
state 2 as " "
state 3 <<choice>>

[*] -down-> 2

2 -down-> 3
note on link
<b>Sistema Permite</b>
* Cerrar Sesión
end note


3 -down-> endState
note on link
<b>Usuario Cierra Sesión</b>
end note
}

@enduml