@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(NO_REGISTRADO)
RECTANGLE(REGISTRADO)
RECTANGLE(MENU_PRINCIPAL)
RECTANGLE(MENU_CLASE)
RECTANGLE(MENU_RUTINAS)
RECTANGLE(ASIGNATURA)
RECTANGLE(MENU_RETOS)

' Relaciones entre los estados y casos de uso
NO_REGISTRADO --> REGISTRADO : Registrarse

REGISTRADO --> MENU_PRINCIPAL : Iniciar Sesión
MENU_PRINCIPAL --> REGISTRADO : Cerrar Sesión
MENU_PRINCIPAL --> ASIGNATURA : Ver Información de Asignaturas
MENU_PRINCIPAL --> MENU_RUTINAS : Usar Rutinas
MENU_PRINCIPAL --> MENU_RETOS : Participar en Retos/Actividades

' Desde el Menú Principal se puede ir al Menú Clase
MENU_PRINCIPAL --> MENU_CLASE : Acceder a Clases

' Desde el Menú Clase
MENU_CLASE --> ASIGNATURA : Impartir Asignatura
MENU_CLASE --> MENU_CLASE : Gestionar Alumnos
MENU_CLASE --> ASIGNATURA : Calificar Alumnos
MENU_CLASE --> ASIGNATURA : Evaluar Progreso

' Desde el Menú Rutinas
MENU_RUTINAS --> MENU_RUTINAS : Asignar Rutinas
MENU_RUTINAS --> MENU_RUTINAS : Usar Rutinas

' Desde el Menú Principal para el Admin
MENU_PRINCIPAL --> MENU_PRINCIPAL : Administrar Usuarios
MENU_PRINCIPAL --> MENU_PRINCIPAL : Configurar Sistema

@enduml
