@startuml

' Definimos los objetos basados en las clases

object profesor1 {
    nombre = "Juan Pérez"
}


object titulacion1 {
    nombre = "Ingeniería Informática"
}

object asignatura1 {
    nombre = "Programación"
}


object memoria1 {
    fecha = "2024-10-21"
}

object departamento1 {
    nombre = "Departamento de Ingeniería Informática"
}

object planEstudios1 {
    nombre = "Plan 2024"
}

' Definimos las relaciones entre los objetos

profesor1 --> titulacion1 : "imparte en"
profesor1 --> asignatura1 : "enseña"
asignatura1 --> titulacion1 : "pertenece a"
memoria1 --> asignatura1 : "reporta sobre"
profesor1 --> memoria1 : "elabora"
asignatura1 --> planEstudios1 : "forma parte de"
profesor1 --> departamento1 : "pertenece a"
titulacion1 --> departamento1 : "se ofrece en"

@enduml