@startuml

hide circle
hide empty members

class Profesor {}
class Alumno {}
class Asignatura {}
class UnidadDidactica {}
class ClasePractica {
   
}
class ClaseTeorica {}
class CentroDeportivo {}
class Rutina {}
class Reto {}
class Valoracion {}

Profesor -- Alumno : esTutorDe
Profesor -- Asignatura : imparte
Asignatura -- UnidadDidactica : tiene
UnidadDidactica -- ClasePractica : incluye
UnidadDidactica -- ClaseTeorica : incluye
Alumno -- Asignatura : cursa
ClasePractica -- CentroDeportivo : seRealizaEn
ClasePractica -- Rutina : enseña
ClasePractica -- Reto : contiene
ClasePractica -- Valoracion: tiene
ClaseTeorica -- Valoracion: tiene
Alumno -- Rutina: realiza
ClasePractica -- ClaseTeorica : requiere
@enduml