@startuml evas

hide circle
hide empty members

class Profesor{}
class Alumno{}
class Asignatura{}
class UnidadesDidacticas{}
class ClasesPracticas{}
class ClasesTeoricas{}
class CentroDeportivo{}
class Rutina{}
class Actividades{}

Profesor -- Alumno : esTutorDe
Profesor -- Asignatura : imparte
Asignatura -- UnidadesDidacticas : tiene
UnidadesDidacticas -- ClasesPracticas : tiene
UnidadesDidacticas -- ClasesTeoricas : tiene
Alumno -- Asignatura : cursa
ClasesPracticas -- CentroDeportivo : seRealizaEn
ClasesPracticas -- Rutina : enseña
Rutina -- Actividades : contiene

@enduml
