@startuml
title Caso de Uso - Asignar Docente Asignatura
left to right direction
actor Usuario as cust

rectangle "Asignar Docente Asignatura" {
    usecase "Asignar Aula a Asignatura" as OP1
}

cust --> OP1
@enduml