@startuml
title Caso de Uso - Pagina Principal

left to right direction
actor Usuario as cust

rectangle "Pagina Principal" {
    usecase "Visualizar horarios" as OP1
    usecase "Organizar horarios" as OP2
usecase "Crear nuevo horario" as OP3
}

cust --> OP1
cust --> OP2
cust -->OP3
@enduml