@startuml
title Caso de Uso - Horario finalizado
left to right direction
actor Usuario as cust

rectangle "Horario finalizado" {
    usecase "Guardar y salir" as OP1
usecase "Log out" as OP2
}

cust --> OP1
cust -->OP2
@enduml