@startuml
title Caso de Uso - Inicio

left to right direction

actor Usuario_registrado as user
actor Usuario_sin_registro as user1

rectangle "Inicio" {
    usecase "Login" as login
    usecase "Registrarse" as registro
}

user --> login : ""
user1 --> registro : ""
@enduml