@startuml

    [*] --> InicioSesion
    InicioSesion : Administrador/Técnico de calidad inicia sesión en el sistema

    InicioSesion --> SeleccionarDatos
    SeleccionarDatos : Seleccionar tipo de informe (Global o por Titulación)

    note right of SeleccionarDatos
      Seleccionan los parámetros del informe
      y los tipos de datos necesarios.
    end note

    SeleccionarDatos --> RecopilarDatos
    RecopilarDatos : Recopilar datos del profesorado

    note right of RecopilarDatos
      Recopilación de datos para el informe.
    end note

    RecopilarDatos --> GenerarInforme
    GenerarInforme : Generar el informe preliminar

    note right of GenerarInforme
      Utilización herramientas específicas
      para crear el informe según los parámetros seleccionados.
    end note

    GenerarInforme --> RevisarInforme
    RevisarInforme : Revisar y validar el informe

    note right of RevisarInforme
      Revisar el informe para asegurar
      que es exacto y cumplir con los requisitos especificados.
    end note

    RevisarInforme --> ModificarInforme
    ModificarInforme : Modificar informe si es necesario
    ModificarInforme --> GenerarInforme : Re-generar el informe

    RevisarInforme --> EmitirInforme
    EmitirInforme : Emitir el informe final

    note right of EmitirInforme
      Informe validado y finalizado es emitido
      para su uso en decisiones o archivo.
    end note

    EmitirInforme --> GuardarInforme
    GuardarInforme : Guardar una copia del informe


    GuardarInforme --> SeleccionarDatos

    GuardarInforme --> [*]

@enduml