@startuml Compartir_Post
skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #black
    linetype polyline
}

skinparam state {
    BackgroundColor #whiteSmoke
}

hide empty description

state startState as "Pantalla de Feed"
state endState as "Post Compartido"

startState --> CompartirPost

state CompartirPost as "Compartir Post" {
    state SeleccionarPost as " "
    state MostrarOpcionesCompartir <<choice>>
    state ConfirmarCompartir as " "
    state CompartirExitoso as " "

    SeleccionarPost -[#green]-> MostrarOpcionesCompartir
    note on link
        <b>Usuario selecciona el post</b>
        * Post que quiere compartir
    end note

    MostrarOpcionesCompartir -[#green]-> ConfirmarCompartir
    note on link
        <b>Sistema muestra opciones para compartir</b>
        * Compartir por red social
        * Enviar por mensaje
        * Copiar enlace
    end note

    MostrarOpcionesCompartir -[#red]-> SeleccionarPost
    note on link
        <b>Sistema muestra error si hay problemas con la carga de opciones</b>
    end note

    ConfirmarCompartir -[#green]-> CompartirExitoso
    note on link
        <b>Usuario confirma el post a compartir</b>
        * Post se comparte correctamente
    end note

    ConfirmarCompartir -[#red]-> MostrarOpcionesCompartir
    note on link
        <b>Usuario puede cancelar o modificar opciones de compartir</b>
    end note
}

CompartirPost --> endState

@enduml
