@startuml
title Caso de Uso: Registrarse

actor Usuario_Invitado as Usuario
usecase "Registrarse" as Registrarse
usecase "Validar correo no registrado" as ValidarCorreo
usecase "Verificar seguridad de la contraseña" as VerificarContrasena
usecase "Guardar datos del usuario" as GuardarDatos
usecase "Enviar correo de confirmación" as EnviarCorreo

Usuario --> Registrarse
Registrarse --> ValidarCorreo
ValidarCorreo --> VerificarContrasena
VerificarContrasena --> GuardarDatos
GuardarDatos --> EnviarCorreo

@enduml
