@startuml
state " " as Estado1
state " " as Estado2
state " " as Estado3

[*] --> Estado1
    note on link
        El administrador solicita entrar en una oferta para procesarla
    end note
Estado1 --> Estado2
    note on link
        El sistema muestra la oferta al administrador
    end note
Estado2 --> Estado3
    note on link
        El administrador solicita aceptar la oferta
    end note
Estado3 --> [*]
    note on link
        El sistema permite aceptar la oferta y actualiza su estado (publicada)
    end note
@enduml