@startuml
state " " as Estado1
state " " as Estado2
state " " as Estado3

[*] --> Estado1
    note on link
        El administrador accede a la sección de ofertas activas
    end note
Estado1 --> Estado2
    note on link
        El administrador selecciona la oferta que desea cerrar
    end note
Estado2 --> Estado3
    note on link
        El administrador marca la oferta como cerrada
    end note
Estado3 --> [*]
    note on link
        La plataforma actualiza el estado de la oferta (cerrada)
    end note
@enduml