@startuml
state " " as Estado1
state " " as Estado2
state " " as Estado3
state " " as Estado4

[*] --> Estado1
    note on link
        El administrador solicita acceder a la sección de ofertas activas
    end note
Estado1 --> Estado2
    note on link
        La plataforma muestra una lista de ofertas activas
    end note
Estado2 --> Estado3
    note on link
        El administrador solicita cerrar una oferta
    end note
Estado3 --> Estado4
    note on link
        El sistema permite cerrar la oferta
    end note
Estado4 --> [*]
    note on link
        La plataforma actualiza el estado de la oferta (cerrada)
    end note
@enduml