@startuml
actor Usuario

rectangle "Cerrar Sesión" {
    Usuario --> (Solicitar Cierre de Sesión)
    (Solicitar Cierre de Sesión) --> (Terminar Sesión Activa)
    (Terminar Sesión Activa) --> (Redirigir a la Página de Inicio)

    note right of (Solicitar Cierre de Sesión)
        El cierre de sesión finaliza la sesión activa
        y borra datos de usuario en la memoria del cliente.
    end note
}
@enduml