@startuml
actor Usuario

rectangle "Iniciar Sesión" {
    Usuario --> (Introducir Credenciales)
    (Introducir Credenciales) ..> (Validar Credenciales) : «include»
    (Validar Credenciales) --> (Redirigir a la Plataforma)

    note right of (Validar Credenciales)
        Las credenciales incluyen:
        - Usuario/Correo electrónico
        - Contraseña
    end note
}
@enduml