@startuml
state " " as Estado1
state " " as Estado2
state " " as Estado3
state " " as Estado4
state " " as Estado5

[*] --> Estado1
    note on link
        El alumni solicita acceder a la sección de ofertas de trabajo
    end note
Estado1 --> Estado2
    note on link
        El sistema muestra una lista de ofertas de trabajo
    end note
Estado2 --> Estado3
    note on link
        El alumni solicita acceder a una oferta de trabajo
    end note
Estado3 --> Estado4
    note on link
        El sistema le permite acceder a la oferta de trabajo
    end note
Estado4 --> Estado5
    note on link
        El alumni solicita postularse a la oferta
    end note
Estado5 --> [*]
    note on link
        El sistema confirma la solicitud o muestra un mensaje de error
    end note
@enduml