@startuml
state " " as Estado1

[*] --> Estado1
    note on link
        El administrador solicita ver las estadisticas globales
    end note
Estado1 --> [*]
    note on link
        El sistema muestra las estadisticas de la plataforma
    end note
@enduml