@startuml
actor Usuario

rectangle "Ver Ofertas de Trabajo" {
    Usuario --> (Ver contenido de oferta)

    note right of (Ver contenido de oferta)
        Los usuarios pueden ver el contenido de las ofertas colgadas en la plataforma:
        - Sector
        - Jornada
        - Fecha de publicación
        - Salario
    end note
}
@enduml