@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_PROFESOR)
RECTANGLE(REGISTRANDO_PROFESOR)
RECTANGLE(ACTUALIZANDO_PROFESOR)
RECTANGLE(CONSULTANDO_PROFESOR)
RECTANGLE(ELIMINANDO_PROFESOR)
RECTANGLE(MENU_PRINCIPAL)

MENU_PROFESOR --> REGISTRANDO_PROFESOR : Registrar profesor
REGISTRANDO_PROFESOR --> MENU_PRINCIPAL : Regresar al menú principal

MENU_PROFESOR --> ACTUALIZANDO_PROFESOR : Actualizar profesor
ACTUALIZANDO_PROFESOR --> MENU_PRINCIPAL : Regresar al menú principal

MENU_PROFESOR --> CONSULTANDO_PROFESOR : Consultar profesor
CONSULTANDO_PROFESOR --> MENU_PRINCIPAL : Regresar al menú principal

MENU_PROFESOR --> ELIMINANDO_PROFESOR : Eliminar profesor
ELIMINANDO_PROFESOR --> MENU_PRINCIPAL : Regresar al menú principal
@enduml
