@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_ASIGNATURAGRADOPROFESOR)
RECTANGLE(REGISTRANDO_ASIGNATURAGRADOPROFESOR)
RECTANGLE(ACTUALIZANDO_ASIGNATURAGRADOPROFESOR)
RECTANGLE(CONSULTANDO_ASIGNATURAGRADOPROFESOR)
RECTANGLE(ELIMINANDO_ASIGNATURAGRADOPROFESOR)
RECTANGLE(MENU_PRINCIPAL)

MENU_ASIGNATURAGRADOPROFESOR --> REGISTRANDO_ASIGNATURAGRADOPROFESOR : Registrar asignatura-grado-profesor
REGISTRANDO_ASIGNATURAGRADOPROFESOR --> MENU_PRINCIPAL : Regresar al menú principal

MENU_ASIGNATURAGRADOPROFESOR --> ACTUALIZANDO_ASIGNATURAGRADOPROFESOR : Actualizar asignatura-grado-profesor
ACTUALIZANDO_ASIGNATURAGRADOPROFESOR --> MENU_PRINCIPAL : Regresar al menú principal

MENU_ASIGNATURAGRADOPROFESOR --> CONSULTANDO_ASIGNATURAGRADOPROFESOR : Consultar asignatura-grado-profesor
CONSULTANDO_ASIGNATURAGRADOPROFESOR --> MENU_PRINCIPAL : Regresar al menú principal

MENU_ASIGNATURAGRADOPROFESOR --> ELIMINANDO_ASIGNATURAGRADOPROFESOR : Eliminar asignatura-grado-profesor
ELIMINANDO_ASIGNATURAGRADOPROFESOR --> MENU_PRINCIPAL : Regresar al menú principal
@enduml