@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_HORARIO)
RECTANGLE(REGISTRANDO_HORARIO)
RECTANGLE(ACTUALIZANDO_HORARIO)
RECTANGLE(CONSULTANDO_HORARIO)
RECTANGLE(ELIMINANDO_HORARIO)
RECTANGLE(MENU_PRINCIPAL)

MENU_HORARIO --> REGISTRANDO_HORARIO : Registrar horario
REGISTRANDO_HORARIO --> MENU_PRINCIPAL : Regresar al menú principal

MENU_HORARIO --> ACTUALIZANDO_HORARIO : Actualizar horario
ACTUALIZANDO_HORARIO --> MENU_PRINCIPAL : Regresar al menú principal

MENU_HORARIO --> CONSULTANDO_HORARIO : Consultar horario
CONSULTANDO_HORARIO --> MENU_PRINCIPAL : Regresar al menú principal

MENU_HORARIO --> ELIMINANDO_HORARIO : Eliminar horario
ELIMINANDO_HORARIO --> MENU_PRINCIPAL : Regresar al menú principal
@enduml
