@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_AULA)
RECTANGLE(REGISTRANDO_AULA)
RECTANGLE(ACTUALIZANDO_AULA)
RECTANGLE(CONSULTANDO_AULA)
RECTANGLE(ELIMINANDO_AULA)
RECTANGLE(MENU_PRINCIPAL)

MENU_AULA --> REGISTRANDO_AULA : Registrar aula
REGISTRANDO_AULA --> MENU_PRINCIPAL : Regresar al menú principal

MENU_AULA --> ACTUALIZANDO_AULA : Actualizar aula
ACTUALIZANDO_AULA --> MENU_PRINCIPAL : Regresar al menú principal

MENU_AULA --> CONSULTANDO_AULA : Consultar aula
CONSULTANDO_AULA --> MENU_PRINCIPAL : Regresar al menú principal

MENU_AULA --> ELIMINANDO_AULA : Eliminar aula
ELIMINANDO_AULA --> MENU_PRINCIPAL : Regresar al menú principal
@enduml
