@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_ASIGNATURA)
RECTANGLE(REGISTRANDO_ASIGNATURA)
RECTANGLE(ACTUALIZANDO_ASIGNATURA)
RECTANGLE(CONSULTANDO_ASIGNATURA)
RECTANGLE(ELIMINANDO_ASIGNATURA)
RECTANGLE(MENU_PRINCIPAL)

MENU_ASIGNATURA --> REGISTRANDO_ASIGNATURA : Registrar asignatura
REGISTRANDO_ASIGNATURA --> MENU_PRINCIPAL : Regresar al menú principal

MENU_ASIGNATURA --> ACTUALIZANDO_ASIGNATURA : Actualizar asignatura
ACTUALIZANDO_ASIGNATURA --> MENU_PRINCIPAL : Regresar al menú principal

MENU_ASIGNATURA --> CONSULTANDO_ASIGNATURA : Consultar asignatura
CONSULTANDO_ASIGNATURA --> MENU_PRINCIPAL : Regresar al menú principal

MENU_ASIGNATURA --> ELIMINANDO_ASIGNATURA : Eliminar asignatura
ELIMINANDO_ASIGNATURA --> MENU_PRINCIPAL : Regresar al menú principal
@enduml
