@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_HORARIOASIGNATURAAULA)
RECTANGLE(REGISTRANDO_HORARIOASIGNATURAAULA)
RECTANGLE(ACTUALIZANDO_HORARIOASIGNATURAAULA)
RECTANGLE(CONSULTANDO_HORARIOASIGNATURAAULA)
RECTANGLE(ELIMINANDO_HORARIOASIGNATURAAULA)
RECTANGLE(MENU_PRINCIPAL)

MENU_HORARIOASIGNATURAAULA --> REGISTRANDO_HORARIOASIGNATURAAULA : Registrar horario-asignatura-aula
REGISTRANDO_HORARIOASIGNATURAAULA --> MENU_PRINCIPAL : Regresar al menú principal

MENU_HORARIOASIGNATURAAULA --> ACTUALIZANDO_HORARIOASIGNATURAAULA : Actualizar horario-asignatura-aula
ACTUALIZANDO_HORARIOASIGNATURAAULA --> MENU_PRINCIPAL : Regresar al menú principal

MENU_HORARIOASIGNATURAAULA --> CONSULTANDO_HORARIOASIGNATURAAULA : Consultar horario-asignatura-aula
CONSULTANDO_HORARIOASIGNATURAAULA --> MENU_PRINCIPAL : Regresar al menú principal

MENU_HORARIOASIGNATURAAULA --> ELIMINANDO_HORARIOASIGNATURAAULA : Eliminar horario-asignatura-aula
ELIMINANDO_HORARIOASIGNATURAAULA --> MENU_PRINCIPAL : Regresar al menú principal
@enduml
