@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_ASIGNATURAGRADO)
RECTANGLE(REGISTRANDO_ASIGNATURAGRADO)
RECTANGLE(ACTUALIZANDO_ASIGNATURAGRADO)
RECTANGLE(CONSULTANDO_ASIGNATURAGRADO)
RECTANGLE(ELIMINANDO_ASIGNATURAGRADO)
RECTANGLE(MENU_PRINCIPAL)

MENU_ASIGNATURAGRADO --> REGISTRANDO_ASIGNATURAGRADO : Registrar asignatura-grado
REGISTRANDO_ASIGNATURAGRADO --> MENU_PRINCIPAL : Regresar al menú principal

MENU_ASIGNATURAGRADO --> ACTUALIZANDO_ASIGNATURAGRADO : Actualizar asignatura-grado
ACTUALIZANDO_ASIGNATURAGRADO --> MENU_PRINCIPAL : Regresar al menú principal

MENU_ASIGNATURAGRADO --> CONSULTANDO_ASIGNATURAGRADO : Consultar asignatura-grado
CONSULTANDO_ASIGNATURAGRADO --> MENU_PRINCIPAL : Regresar al menú principal

MENU_ASIGNATURAGRADO --> ELIMINANDO_ASIGNATURAGRADO : Eliminar asignatura-grado
ELIMINANDO_ASIGNATURAGRADO --> MENU_PRINCIPAL : Regresar al menú principal
@enduml

