@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_GRADO)
RECTANGLE(REGISTRANDO_GRADO)
RECTANGLE(ACTUALIZANDO_GRADO)
RECTANGLE(CONSULTANDO_GRADO)
RECTANGLE(ELIMINANDO_GRADO)
RECTANGLE(MENU_PRINCIPAL)

MENU_GRADO --> REGISTRANDO_GRADO : Registrar grado
REGISTRANDO_GRADO --> MENU_PRINCIPAL : Regresar al menú principal

MENU_GRADO --> ACTUALIZANDO_GRADO : Actualizar grado
ACTUALIZANDO_GRADO --> MENU_PRINCIPAL : Regresar al menú principal

MENU_GRADO --> CONSULTANDO_GRADO : Consultar grado
CONSULTANDO_GRADO --> MENU_PRINCIPAL : Regresar al menú principal

MENU_GRADO --> ELIMINANDO_GRADO : Eliminar grado
ELIMINANDO_GRADO --> MENU_PRINCIPAL : Regresar al menú principal
@enduml