@startuml
!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_CASOSADICIONALES)
RECTANGLE(ASIGNANDO_PROFESOR)
RECTANGLE(CONSULTANDO_HORARIO_PROFESOR)
RECTANGLE(EDITANDO_ASIGNACION)
RECTANGLE(ELIGIENDO_GRADO)
RECTANGLE(REGISTRANDO_HORARIOASIGNATURAAULA)
RECTANGLE(MENU_PRINCIPAL)

MENU_CASOSADICIONALES --> ASIGNANDO_PROFESOR : Asignar profesor
ASIGNANDO_PROFESOR --> MENU_PRINCIPAL : Regresar al menú principal

MENU_CASOSADICIONALES --> CONSULTANDO_HORARIO_PROFESOR : Consultar horario del profesor
CONSULTANDO_HORARIO_PROFESOR --> MENU_PRINCIPAL : Regresar al menú principal

MENU_CASOSADICIONALES --> EDITANDO_ASIGNACION : Editar asignación
EDITANDO_ASIGNACION --> MENU_PRINCIPAL : Regresar al menú principal

MENU_CASOSADICIONALES --> ELIGIENDO_GRADO : Elegir grado
ELIGIENDO_GRADO --> REGISTRANDO_HORARIOASIGNATURAAULA : Registrar horario-asignatura-aula
REGISTRANDO_HORARIOASIGNATURAAULA --> MENU_PRINCIPAL : Regresar al menú principal
@enduml