@startuml
title Caso de uso: Crear Capacitación

skinparam {
    NoteBackgroundColor #lightYellow
    ArrowColor #blue
    NoteBorderColor #blue
    linetype polyline
}

state startState as "PÁGINA PRINCIPAL"
state endState as "PÁGINA PRINCIPAL"

startState --> IniciarCreacion
note on link
    <b>Administrador Accede</b>
    * Selecciona la opción de crear capacitación
end note

IniciarCreacion --> CompletarFormulario
note on link
    <b>Sistema Muestra</b>
    * Formulario de nueva capacitación
end note

state CompletarFormulario {
    state "Rellenar Campos" as RellenarCampos
    state "Validar Información" as ValidarInformacion

    [*] --> RellenarCampos
    RellenarCampos --> ValidarInformacion
    note on link
        <b>Administrador Verifica</b>
        * Información ingresada es correcta
    end note
    ValidarInformacion --> [*] : Información válida
}

CompletarFormulario --> GuardarCapacitacion
note on link
    <b>Administrador Confirma</b>
    * Guarda la capacitación
end note

GuardarCapacitacion --> endState
note on link
    <b>Sistema Redirige</b>
    * Página principal con notificación de éxito
end note
@enduml
