@startuml
left to right direction

usecase "Buscar Oferta" as BuscarOferta
usecase "Postular Oferta" as PostularOferta
usecase "Ver Ofertas" as VerOfertas



Alumni --> BuscarOferta
Alumni --> PostularOferta
Alumni --> VerOfertas
@enduml
