@startuml

title Registrar Asignatura-Grado

start
:El usuario solicita registrar Asignatura-Grado;
:El sistema permite elegir un grado;
:El usuario elige un grado;
:El sistema le muestra las asignaturas del grado;
:El usuario elige una asignatura y la asocia al grado;
if (¿Datos válidos?) then (Sí)
:El sistema permite registrar la asignación;
:El sistema incorpora la nueva asignación al sistema;
:El sistema presenta una confirmación: "Asignación creada correctamente";
else (No)
:El sistema presenta un mensaje de error: "Los datos de la asignación no son válidos";
:El sistema permite introducir nuevamente los datos;
endif
stop

@enduml