@startuml
title Caso de uso: Consultar Estadísticas

skinparam {
    NoteBackgroundColor #lightYellow
    ArrowColor #blue
    NoteBorderColor #blue
    linetype polyline
}

state startState as "PÁGINA PRINCIPAL"
state endState as "PÁGINA PRINCIPAL"

startState --> ConsultarEstadisticas
note on link
    <b>Administrador Accede</b>
    * Selecciona la opción de estadísticas
end note

ConsultarEstadisticas --> MostrarEstadisticas
note on link
    <b>Sistema Muestra</b>
    * Datos gráficos y numéricos
    * Tendencias y métricas clave
end note

MostrarEstadisticas --> endState
note on link
    <b>Administrador Finaliza</b>
    * Regresa a la página principal
end note
@enduml
