@startuml EnvioDocumentos
left to right direction
actor "Responsable" as Responsable
actor "Administrador General" as AdminGeneral

package "Envío de Documentos" {
    usecase "Crear/Redactar Mensaje" as ED1
    usecase "Crear Envío" as ED2
    usecase "Descargar Resumen de Estados" as ED3
}

AdminGeneral --|> Responsable
Responsable --> ED1
Responsable --> ED2
Responsable --> ED3
@enduml