@startuml 
!define RECTANGLE(x) rectangle x

RECTANGLE(NAVEGACION_MENUS)
RECTANGLE(MENU_PERFIL) 

' Submenús de "Perfil"
RECTANGLE(CREANDO_CLASE) 
RECTANGLE(MOSTRANDO_QR) 
RECTANGLE(VIENDO_MIS_CLASES) 
RECTANGLE(VIENDO_ALUMNOS) 
RECTANGLE(VIENDO_RETOS_ALUMNOS) 
RECTANGLE(EVALUANDO_RETOS) 

CREANDO_CLASE --> NAVEGACION_MENUS : Cambiar menú
MOSTRANDO_QR --> NAVEGACION_MENUS : Cambiar menú
VIENDO_MIS_CLASES --> NAVEGACION_MENUS : Cambiar menú
VIENDO_ALUMNOS --> NAVEGACION_MENUS : Cambiar menú
VIENDO_RETOS_ALUMNOS --> NAVEGACION_MENUS : Cambiar menú
EVALUANDO_RETOS --> NAVEGACION_MENUS : Cambiar menú

' Menú "Perfil"
MENU_PERFIL --> CREANDO_CLASE : Crear clase
MENU_PERFIL --> MOSTRANDO_QR : Mostrar QR en centro deportivo
MENU_PERFIL --> VIENDO_MIS_CLASES : Ver mis clases
VIENDO_MIS_CLASES --> VIENDO_ALUMNOS : Ver alumnos
VIENDO_ALUMNOS --> VIENDO_RETOS_ALUMNOS : Ver retos alumnos
VIENDO_RETOS_ALUMNOS --> EVALUANDO_RETOS : Evaluar retos

@enduml