@startuml evas

hide circle
hide empty members

class Profesor {
    nombre = "Ivan"
    apellido ="Gonzalez"
}

class Alumno {
    nombre = "Alejandro"
    apellido = "Higuera"
    edad = "17"
}

class Asignatura {
    nombre = "EVAS"
    codigo = "056"
}

class UnidadesDidacticas {
    titulo = "Cardio"
}

class ClasesPracticas {
    fecha = "12-11-2024"
    duracion = "2 horas"
    ubicacion = "Gimnasio"
}

class ClasesTeoricas {
    fecha = "07-11-2024"
    duracion = "2 horas"
    ubicacion = "Aula 101"
}

class CentroDeportivo {
    nombre = "Instalaciones de Muriedas"
}

class Rutina {
    titulo = "Atletismo"
    nivel = "Iniciacion"
    objetivo = "Mejorar resistencia"
}

class Actividades {
    nombre = "Test Course-Navette"
    tipo = "Cardio"
}

class Valoracion {
    tiempo = "11 minutos"
    comentario = "Buen rendimiento"
}


Profesor -- Alumno : esTutorDe
Profesor -- Asignatura : imparte
Asignatura -- UnidadesDidacticas : tiene
UnidadesDidacticas -- ClasesPracticas : tiene
UnidadesDidacticas -- ClasesTeoricas : tiene
Alumno -- Asignatura : cursa
ClasesPracticas -- CentroDeportivo : seRealizaEn
ClasesPracticas -- Rutina : enseña
Rutina -- Actividades : contiene
Rutina -- Valoracion: tiene
Alumno -- Rutina: realiza

@enduml
