@startuml evas

hide circle
hide empty members

class Profesor {
    nombre = "Ivan"
    apellido = "Gonzalez"
}

class Alumno {
    nombre = "Alejandro"
    apellido = "Higuera"
    edad = "17"
}

class Asignatura {
    nombre = "EVAS"
    codigo = "056"
}

class UnidadDidactica {
    titulo = "Cardio"
}

class ClasePractica {
    fecha = "12-11-2024"
    duracion = "2 horas"
    ubicacion = "Gimnasio"
}

class ClaseTeorica {
    fecha = "07-11-2024"
    duracion = "2 horas"
    ubicacion = "Aula 101"
}

class CentroDeportivo {
    nombre = "Instalaciones de Muriedas"
}

class Rutina {
    titulo = "Atletismo"
    nivel = "Iniciacion"
    objetivo = "Mejorar resistencia"
}

class Reto {
    nombre = "Completar 5km"
    tipo = "Cardio"
    descripcion = "Correr 5km en menos de 30 minutos"
}

class Valoracion {
    nota = 8
    comentario = "Buen trabajo"
}

Profesor -- Alumno : esTutorDe
Profesor -- Asignatura : imparte
Asignatura -- UnidadDidactica : tiene
UnidadDidactica -- ClasePractica : incluye
UnidadDidactica -- ClaseTeorica : incluye
Alumno -- Asignatura : cursa
ClasePractica -- CentroDeportivo : seRealizaEn
ClasePractica -- Rutina : enseña
ClasePractica -- Reto : contiene
ClasePractica -- Valoracion: tiene
ClaseTeorica -- Valoracion: tiene
Alumno -- Rutina: realiza

ClasePractica -- ClaseTeorica : requiere

@enduml
