@startuml

hide empty description

state Menu_Rutinas_y_Ejercicios
state BuscandoRutina
state BuscarRutina {
  [*] --> MostrarBuscador
  note on link
      El sistema muestra: buscador.
  end note

  MostrarBuscador --> IntroducirNombre
  note on link
      El profesor introduce: nombre de la rutina.
  end note

  IntroducirNombre --> ConfirmarBusqueda
  note on link
      El alumno introduce: confirmación presionando "Buscar".
  end note

  ConfirmarBusqueda --> [*]
  note on link
      El sistema muestra: mensaje de rutina buscada con éxito.
  end note
}

Menu_Rutinas_y_Ejercicios --> BuscarRutina
BuscarRutina --> BuscandoRutina

@enduml