@startuml


Menu_Rutinas_y_Ejercicios --> CrearRutina

state CrearRutina {
  hide empty description

  [*] --> SolicitarDatosRutina
  note on link
      El sistema muestra: solicitud de nombre y objetivo de la rutina.
  end note

  SolicitarDatosRutina --> SeleccionarEjercicios
  note on link
      El alumno introduce: selección de ejercicios de la lista.
  end note

  SeleccionarEjercicios --> ConfirmarCreacion
  note on link
      El alumno introduce: confirmación presionando "Crear".
  end note

  ConfirmarCreacion --> [*]
  note on link
      El sistema muestra: mensaje de rutina creada con éxito.
  end note
}
CrearRutina --> CreandoRutina
@enduml
