@startuml EditarRutina

hide empty description

state Mostrando_Rutina
state EditandoRutina

state EditarRutina {
  [*] --> SolicitarEdicion
  note on link
      El sistema muestra: nombre y objetivo actuales para edición.
  end note

  SolicitarEdicion --> ModificarEjercicios
  note on link
      El alumno introduce: actualizaciones a la lista de ejercicios.
  end note

  ModificarEjercicios --> ConfirmarEdicion
  note on link
      El alumno introduce: confirmación presionando "Editar".
  end note

  ConfirmarEdicion --> [*]
  note on link
      El sistema muestra: mensaje de cambios guardados con éxito.
  end note
}

Mostrando_Rutina --> EditarRutina
EditarRutina --> EditandoRutina

@enduml
