@startuml
state Menu_Rutinas_y_Ejercicios
state rombo2 <<choice>>
state Obligatorios
state Opcionales
state MostrarReto
state Menu_Perfil
state Menu_Retos
state Clasificación
state Menu_Principal

[*] --> Menu_Retos : "El alumno solicita entrar a\nMenu Retos"
Menu_Retos -->Obligatorios : El alumno escoge
Menu_Retos --> Opcionales
Opcionales --> MostrarReto
Obligatorios -->MostrarReto : El alumno solicita

Menu_Retos --> rombo2 : "El alumno solicita a\nir a otra opción"
rombo2 --> Menu_Perfil
rombo2 --> Menu_Retos: "Volver al menú"
rombo2 --> Clasificación
rombo2 --> Menu_Principal
rombo2 --> Menu_Rutinas_y_Ejercicios

Menu_Retos --> [*]
@enduml
