@startuml

hide empty description

state Navegacion_Menus
state Menu_Clasificacion
state VerClasificacion{
    state Ver as "Ver Clasificación"
    [*] --> Ver
    note on link
        El alumno introduce que quiere ir a Clasificación
    end note
    Ver --> [*]
    note on link
        El sistema muestra Clasificación
    end note
}

Navegacion_Menus --> VerClasificacion
VerClasificacion --> Menu_Clasificacion

@enduml
