@startuml IngresarAlSistema

hide empty description

state Alumno
state Pagina_Principal
state IngresarAlSistema{
    [*] --> [*]
    note on link
        El sistema muestra la página principal del Alumno
    end note
}

Alumno --> IngresarAlSistema
IngresarAlSistema --> Pagina_Principal

@enduml
