@startuml
state " " as Estado1
state " " as Estado2
state rombo <<choice>>
[*] --> Estado1
    note on link
        El Alumno solicita ir a la página de inicio
    end note
Estado1 --> Estado2
    note on link
        El Sistema muestra la página de inicio.
    end note
Estado2 --> [*]
Estado2 --> rombo
note on link
El profesor decide
end note
rombo --> Menu_Retos
rombo --> Menu_Rutinas_Y_Ejercicios
rombo --> Clasificacion
rombo --> Perfil
@enduml