@startuml

hide empty description

state Menu_Rutinas_y_Ejercicios

state MostrarReto{
    state VerReto as "Mostrar Reto"
    [*] --> VerReto
    note on link
        El alumno introduce que quiere ver el reto
    end note
    VerReto --> [*]
    note on link
        El sistema muestra el reto
    end note
}
Menu_Rutinas_y_Ejercicios --> MostrarReto
MostrarReto --> MostrandoReto
@enduml
