@startuml 

hide empty description

state Menu_Rutinas_y_Ejercicios
state MostrandoRutina

state MostrarRutina {
  state VerRutina as "Mostar Rutina"
  [*] --> VerRutina
  note on link
    El alumno introduce ver una rutina
  end note
  VerRutina --> Ejercicios
  note on link
    El sistema muestra los ejercicios de la rutina
  end note
  Ejercicios --> SeleccionEjercicio
  note on link
    El alumno selecciona un ejercicio
  end note
  SeleccionEjercicio --> [*]
  note on link
    El sistema muestra los detalles del ejercicio
  end note
}

Menu_Rutinas_y_Ejercicios --> MostrarRutina
MostrarRutina --> MostrandoRutina
@enduml
