@startuml 

hide empty description

state Menu_Rutinas_y_Ejercicios
state MostrandoEjercicio
state MostrarEjercicio {
  [*] --> VerDetalles
  note on link
    El sistema muestra los detalles del ejercicio
  end note
 
  VerDetalles --> [*]
  note on link
    Finaliza visualización
  end note
}

Menu_Rutinas_y_Ejercicios --> MostrarEjercicio
MostrarEjercicio --> MostrandoEjercicio

@enduml
