@startuml

hide empty description

state Menu_Rutinas_y_Ejercicios

state VerReto{
    state Ver as "Ver Reto"
    [*] --> Ver
    note on link
        El alumno introduce que quiere ver el reto
    end note
    Ver --> [*]
    note on link
        El sistema muestra el reto
    end note
}
Menu_Rutinas_y_Ejercicios --> VerReto
VerReto --> MostrandoReto
@enduml
