@startuml

hide empty description

state MostrandoReto
state SubiendoEvidencia

state SubirEvidencia {

    state IniciarSubirEvidencia as "Subir Evidencia"
    [*] --> IniciarSubirEvidencia
    note on link
        El alumno introduce: acceso a SubirEvidencia.
    end note

    IniciarSubirEvidencia --> Archivo
    note on link
        El alumno adjunta: archivo del reto.
    end note


    Archivo --> ConfirmarArchivo
    note on link
        El sistema muestra: opción de "Subir Evidencia"".
    end note

    ConfirmarArchivo --> [*]
    note on link
        El sistema muestra: confirmación de reto creado.
    end note
}

MostrandoReto --> SubirEvidencia
SubirEvidencia --> SubiendoEvidencia

@enduml
