@startuml Ver_Insignias

hide empty description

state Viendo_Mis_Insignias
state Viendo_Insignias
state Ver_Insignas {
    state VerInsignias as "Ver Insignias"
    [*] --> VerInsignias
    note on link
        El Alumno introduce ver las insignias
    end note
    VerInsignias --> [*]
    note on link
        El sistema muestra todas las insignias
    end note
}

Viendo_Mis_Insignias --> Ver_Insignas
Ver_Insignas --> Viendo_Insignias

@enduml
