@startuml
title Caso de uso: Eliminar Postulante

skinparam {
    NoteBackgroundColor #lightYellow
    ArrowColor #blue
    NoteBorderColor #blue
    linetype polyline
}

state startState as "PÁGINA PRINCIPAL"
state endState as "PÁGINA PRINCIPAL"

startState --> SeleccionarPostulante
note on link
    <b>Administrador Navega</b>
    * Selecciona un postulante de la lista
end note


SeleccionarPostulante --> ConfirmarEliminacion
note on link
    <b>Sistema Solicita</b>
    * Confirmación de eliminación
end note

ConfirmarEliminacion --> EliminarPostulante
note on link
    <b>Administrador Acepta</b>
    * Confirmación de eliminación
end note

EliminarPostulante --> endState
note on link
    <b>Sistema Notifica</b>
    * "Postulante eliminado exitosamente"
end note
@enduml
