@startuml
class Usuario {
    +String id
    +String nombre
    +String correo
    +String contraseña
    +Date fechaRegistro
}
class Post {
    +String id
    +Date fechaCreacion
    +Date fechaResuelto
    +int duracion
    +String mensaje
    +boolean resuelto
    +Usuario usuarioOP
    +List<Etiqueta> etiquetas
}
class Etiqueta {
        +String id
        +String nombre
        +String descripcion
        +String color
        +crearEtiqueta()
        +actualizarEtiqueta()
        +obtenerPosts()
}
Usuario "1" --> "n" Post : "publica"
Post "n" --> "n" Etiqueta : "caracterizado por"
@enduml
