@startuml CerrarSesion

hide empty description

state choice <<choice>>

Alumno --> choice
Profesor --> choice
choice --> CerrarSesion

state CerrarSesion {
    state " " as Inicio
    state " " as Confirmacion
    state " " as Fin

    [*] --> Inicio
    note on link
        El alumno/profesor introduce la opción "Cerrar sesión".
    end note

    Inicio --> Confirmacion
    note on link
        El sistema muestra un mensaje de confirmación
        para cerrar sesión.
    end note

    state Decisión <<choice>>
    Confirmacion --> Decisión
    note on link
        El alumno/profesor introduce su decisión: confirmar o cancelar.
    end note

    Decisión --> Fin
    note on link
        El alumno/profesor introduce "Confirmar".
    end note

    Decisión --> Inicio
    note on link
        El alumno/profesor introduce "Cancelar".
    end note

    Fin --> [*]
    note on link
        El sistema muestra el cierre de la sesión y redirige
        al inicio de sesión.
    end note
}

CerrarSesion --> Usuario
@enduml
