@startuml

state " " as Estado1
state " " as Estado2

[*] --> Estado1
    note on link
        El usuario solicita cerrar sesión
    end note
Estado1 --> Estado2
    note on link
        El Sistema muestra la confirmación 
        de la operación
    end note
state rombo <<choice>>
Estado2 --> rombo
note on link
    El usuario confirma la operación
end note
rombo --> [*] 
  note on link
    EL usuario cancela la operación
    end note
rombo --> Registrarse
    
@enduml
