@startuml

top to bottom direction

[*] --> MenuPrincipal

MenuPrincipal --> MenuRutinas : Alumno selecciona "Menú Rutinas"
note on link
    El sistema muestra las rutinas disponibles:
    - Pecho.
    - Espalda.
    - Piernas.
end note

MenuRutinas --> ListaDeRutinas : Acceder a lista de rutinas
MenuRutinas --> [*] : Alumno finaliza desde "Menú de Rutinas"
note on link
    El alumno puede regresar al Menú Principal desde aquí.
end note

ListaDeRutinas --> TipoDeRutina : Alumno selecciona tipo de rutina
note on link
    El alumno decide realizar una rutina de pecho, espalda o piernas.
end note

state TipoDeRutina <<choice>>
TipoDeRutina --> RutinaDePecho : "Rutina de Pecho"
TipoDeRutina --> RutinaDeEspalda : "Rutina de Espalda"
TipoDeRutina --> RutinaDePiernas : "Rutina de Piernas"

RutinaDePecho --> CompletarRutina : Comienza rutina de pecho
note on link
    El alumno comienza los ejercicios de la rutina de pecho.
end note
RutinaDeEspalda --> CompletarRutina : Comienza rutina de espalda
note on link
    El alumno comienza los ejercicios de la rutina de espalda.
end note
RutinaDePiernas --> CompletarRutina : Comienza rutina de piernas
note on link
    El alumno comienza los ejercicios de la rutina de piernas.
end note

CompletarRutina --> GuardarRegistro
note on link
    El sistema guarda el registro de la rutina realizada,
    incluyendo la carga de cada ejercicio.
end note

GuardarRegistro --> MenuRutinas : Regresar al Menú de Rutinas
GuardarRegistro --> [*] : Finalizar y volver al Menú Principal
note on link
    Registro guardado correctamente. El alumno puede
    elegir finalizar o continuar con otras rutinas.
end note

@enduml
