@startuml

[*] --> MenuPrincipal 

MenuPrincipal --> MenuRutinas : Alumno selecciona "Menu Rutinas"
MenuPrincipal --> [*] : "Finalizar desde Menú Principal". Alumno vuelve al menu inicial
note on link
    El sistema muestra las rutinas disponibles:
    - Pecho.
    - Espalda.
    - Piernas
end note
MenuRutinas -u-> ListaDeRutinas : Alumno accede a Lista de Rutinas disponibles
MenuRutinas -u-> [*] : "Finalizar desde Menú de Rutinas". Alumno vuelve al menu inicial


ListaDeRutinas -u-> TipoDeRutina
note on link
    El alumno decide realizar una rutina de pecho, espalda o piernas.
end note

state TipoDeRutina <<choice>>
TipoDeRutina -u-> RutinaDePecho : Alumno selecciona "Rutina de Pecho"
TipoDeRutina -u-> RutinaDeEspalda : Alumno selecciona "Rutina de Espalda"
TipoDeRutina -u-> RutinaDePiernas : Alumno selecciona "Rutina de Piernas"

RutinaDePecho -u-> RealizarRutina
note on link
    El alumno comienza la rutina de pecho.
    
end note
RutinaDeEspalda -u-> RealizarRutina
note on link
    El alumno comienza la rutina de espalda.
    
end note
RutinaDePiernas -u-> RealizarRutina
note on link
    El alumno comienza la rutina de piernas.
    
end note

RealizarRutina -u-> GuardarRegistro
note on link
    El sistema guarda el registro de la rutina utilizada y de la carga de cada ejercicio
end note

GuardarRegistro  -u-> MenuRutinas : Alumno regresa al Menú de Rutinas
GuardarRegistro -u-> [*] : Alumno finaliza después de enviar la evidencia. Alumno vuelve al menu inicial.
note on link
    Registro guardado correctamente. 
    Opción de finalizar o continuar con otras rutinas.
end note

@enduml