@startuml

[*] --> MenuPrincipal 

MenuPrincipal --> MenuRetos : Alumno selecciona "Menu Retos"
MenuPrincipal --> [*] : Finalizar desde Menú Principal. Alumno vuelve al menu de inicio
note on link
    El sistema muestra los retos disponibles:
    - Obligatorios: necesarios para completar la asignatura.
    - Opcionales: para puntos extra.
end note
MenuRetos --> ListaDeRetos : Alumno accede a Lista de Retos disponibles
MenuRetos --> [*] : Finalizar desde Menú de Retos.  Alumno vuelve al menu de inicio


ListaDeRetos --> TipoDeReto
note on link
    El alumno decide realizar un reto obligatorio o opcional.
end note

state TipoDeReto <<choice>>
TipoDeReto --> RetoObligatorio : Alumno selecciona "Reto Obligatorio"
TipoDeReto --> RetoOpcional : Alumno selecciona "Reto Opcional"

RetoObligatorio --> RealizarReto
note on link
    El alumno comienza el reto obligatorio.
    
end note

RetoOpcional --> RealizarReto
note on link
    El alumno comienza el reto opcional.
    
end note

RealizarReto --> SubirEvidencia
note on link
    El alumno sube una evidencia (foto o video)
end note

SubirEvidencia --> ConfirmarEnvio
note on link
    El alumno revisa la evidencia y confirma su envío.
end note

ConfirmarEnvio --> MenuRetos : Alumno regresa al Menú de Retos
ConfirmarEnvio --> [*] : Alumno finaliza después de enviar la evidencia. Alumno vuelve al menu de inicio
note on link
    Evidencia enviada correctamente. 
    Opción de finalizar o continuar con otros retos.
end note
@enduml