@startuml

[*] --> CrearRetos : El profesor solicita CrearRetos
CrearRetos --> UnidadesDidacticas : El sistema muestra las UnidadesDidacticas
UnidadesDidacticas --> OpcionReto : El profesor ingresa la UnidadesDidacticas
state reto <<choice>>
OpcionReto --> reto : El sistema muestra las opciones de reto
reto --> RetoObligatorio : El profesor ingresa RetoObligatorio
reto --> RetoOpcional : El profesor ingresa RetoOpcional
RetoObligatorio --> DescripcionReto : El profesor ingresa una descripcion del reto
RetoOpcional --> DescripcionReto : El profesor ingresa una descripcion del reto
DescripcionReto --> OpcionGuardarEditar : El sistema muestra las opciones de "Guardar" o "Editar"
state OpcionGuardarEditar <<choice>>
OpcionGuardarEditar --> GuardarReto : El profesor elige Guardar
OpcionGuardarEditar --> EditarDescripcion : El profesor elige Editar
EditarDescripcion --> DescripcionReto : El profesor edita la descripcion
GuardarReto --> [*] : El sistema guarda el reto

@enduml
