@startuml

top to bottom direction

[*] --> MenuPrincipal

MenuPrincipal --> MenuRutinas : Profesor selecciona "Menú Rutinas"

MenuRutinas --> CrearRutina : Profesor selecciona "Crear Rutina"

state SeleccionarCategoria <<choice>>
CrearRutina --> SeleccionarCategoria
note on link
    Profesor selecciona una categoría general para la rutina, como:
    - Fuerza
    - Resistencia
    - Flexibilidad
end note

SeleccionarCategoria --> ConfigurarRutina : Seleccionar "Fuerza"
SeleccionarCategoria --> ConfigurarRutina : Seleccionar "Resistencia"
SeleccionarCategoria --> ConfigurarRutina : Seleccionar "Flexibilidad"

ConfigurarRutina --> ElegirEjercicios : Configurar detalles básicos
note bottom of ConfigurarRutina
    Detalles básicos incluyen:
    - Nombre de la rutina
    - Objetivo de la rutina
end note

ElegirEjercicios --> RevisarRutina : Seleccionar ejercicios
note bottom of ElegirEjercicios
    El profesor selecciona ejercicios específicos basados en la categoría elegida.
end note

RevisarRutina --> ElegirEjercicios : Volver a editar ejercicios
RevisarRutina --> PublicarRutina : Confirmar y publicar

note bottom of PublicarRutina
    La rutina queda visible para los estudiantes.
end note

PublicarRutina --> CrearRutina : Crear otra rutina
PublicarRutina --> MenuRutinas : Volver al menú de rutinas
PublicarRutina --> [*] : Salir. El profesor vuelve a ir al inicio

@enduml
