@startuml

top to bottom direction

[*] --> MenuPrincipal

MenuPrincipal --> MenuRutinasYEjercicios : Profesor selecciona "Menú Rutinas y Ejercicios"

MenuRutinasYEjercicios --> CrearRutina : Profesor selecciona "Crear Rutina"

CrearRutina --> ConfigurarRutina


ConfigurarRutina --> ElegirEjercicios : Configurar detalles 
note bottom of ConfigurarRutina
    Detalles básicos incluyen:
    - Nombre de la rutina
    - Objetivo de la rutina
end note

ElegirEjercicios --> RevisarRutina : Seleccionar ejercicios
note bottom of ElegirEjercicios
    El profesor selecciona ejercicios específicos basados en la categoría elegida.
end note

RevisarRutina --> ElegirEjercicios : Volver a editar ejercicios
RevisarRutina --> BotonCrearRutina : Confirmar y publicar

note bottom of BotonCrearRutina
    La rutina queda visible para los estudiantes.
end note

BotonCrearRutina --> CrearRutina : Crear otra rutina
BotonCrearRutina --> MenuRutinasYEjercicios : Volver al menú de rutinas
BotonCrearRutina --> [*] : Salir. 

@enduml
