@startuml IniciarSesion

hide empty description

state Usuario
state IniciarSesion{
    state " " as Estado1
    state " " as Estado2
    state " " as Estado3

    [*] --> Estado1
    note on link
        El Usuario solicita iniciar sesión
    end note
    Estado1 --> Estado2
    note on link
        El Sistema solicita
        - Correo
        - Contraseña
    end note
    Estado2 --> Estado3
    note on link
        Usuario introcude
        - Correo
        - Contraseña
    end note
    Estado3 --> [*]
    note on link
        El sistema identifica si es alumno o profesor
    end note

    Estado3 --> Estado1
    note on link
        Datos incorrectos
    end note
}
state Profesor
state Alumno


Usuario --> IniciarSesion
IniciarSesion --> Profesor
IniciarSesion --> Alumno

@enduml