@startuml
state " " as Estado1

[*] --> Estado1
    note on link
        El usuario solicita ir a la página de inicio
    end note
Estado1 --> [*]
    note on link
        El Sistema muestra la página de inicio.
        El alumno va Completar Retos, Completar Rutinas o Cerrar Sesion

    end note
@enduml