@startuml
state Menu_Clasificacion
state rombo1 <<choice>>
state Ver_Alumnos_Clase
state Menu_Perfil
state Menu_Retos
state Menu_Rutinas_y_Ejercicios
state Menu_Principal

[*] --> Menu_Clasificacion : "El profesor solicita entrar a\nMenu Clasificacion"

Menu_Clasificacion --> Ver_Alumnos_Clase : "El profesor solicita ver alumnos"



Menu_Clasificacion --> rombo1 : "El profesor solicita ir a otra opción"
rombo1 --> Menu_Perfil
rombo1 --> Menu_Retos
rombo1 --> Menu_Rutinas_y_Ejercicios
rombo1 --> Menu_Principal
rombo1 --> Menu_Clasificacion : "Volver al menú"

Menu_Clasificacion --> [*]
@enduml