@startuml
state Menu_Rutinas_y_Ejercicios
state rombo1 <<choice>>
state rombo2 <<choice>>
state Ejercicios
state Rutinas
state Crear_Rutina
state Crear_Ejercicio
state Menu_Perfil
state Menu_Retos
state Clasificación
state Menu_Principal

[*] --> Menu_Rutinas_y_Ejercicios : "El profesor solicita entrar a\nMenu Rutinas y Ejercicios"

Menu_Rutinas_y_Ejercicios --> rombo1 : "El profesor solicita mostrar"
rombo1 --> Ejercicios
Ejercicios --> rombo1

Ejercicios --> Crear_Ejercicio : "El sistema permite"
Ejercicios --> Mostrar_Ejercicio
rombo1 --> Rutinas
Rutinas --> Crear_Rutina: "El sistema permite"
Rutinas --> Mostrar_Rutina
Rutinas --> rombo1
Menu_Rutinas_y_Ejercicios --> rombo2 : "El profesor solicita ir a otra opción"
rombo2 --> Menu_Perfil
rombo2 --> Menu_Retos
rombo2 --> Clasificación
rombo2 --> Menu_Principal
rombo2 --> Menu_Rutinas_y_Ejercicios : "Volver al menú"

Menu_Rutinas_y_Ejercicios --> [*]
@enduml
