@startuml
state Menu_Clasificacion
state rombo1 <<choice>>
state rombo2 <<choice>>
state Clase_1
state Clase_2
state Clase_3
state Clase_4
state Menu_Perfil
state Menu_Retos
state Menu_Rutinas_y_Ejercicios
state Menu_Principal

[*] --> Menu_Clasificacion : "El profesor solicita entrar a\nMenu Clasificacion"

Menu_Clasificacion --> rombo1 : "El profesor solicita ver clase"
rombo1 --> Clase_1
rombo1 --> Clase_2
Clase_1 --> rombo1
Clase_2 --> rombo1
rombo1 --> Clase_3
Clase_3 --> rombo1
rombo1 --> Clase_4
Clase_4 --> rombo1


Menu_Clasificacion --> rombo2 : "El profesor solicita ir a otra opción"
rombo2 --> Menu_Perfil
rombo2 --> Menu_Retos
rombo2 --> Menu_Rutinas_y_Ejercicios
rombo2 --> Menu_Principal
rombo2 --> Menu_Clasificacion : "Volver al menú"

Menu_Clasificacion --> [*]
@enduml