@startuml
[*] --> Menu_Rutinas_y_Ejercicios : Inicio del proceso
state rombo <<choice>>
rombo --> Menu_Perfil
rombo --> Menu_Retos
rombo --> Clasificación
rombo --> Menu_Rutinas_y_Ejercicios
rombo --> Menu_Principal

Menu_Rutinas_y_Ejercicios --> ListaRutinas : Presionar botón "Rutinas"
ListaRutinas --> MostrarRutina : Seleccionar una rutina de la lista
MostrarRutina --> rombo

state MostrarRutina {
  VerDetallesRutina : El sistema muestra la lista de ejercicios
  VerDetallesRutina --> MostrarEjercicio : Seleccionar un ejercicio de la lista
  VerDetallesRutina --> EditarRutina
  VerDetallesRutina --> CrearRutina
  VerDetallesRutina --> [*] : Finaliza visualización de la rutina
}
@enduml
