@startuml
top to bottom direction

[*] --> Menu_Perfil : Inicio del proceso
state rombo <<choice>>
rombo -u-> Menu_Perfil
rombo --> Menu_Retos
rombo --> Menu_Clasificación
rombo --> Menu_Rutinas_y_Ejercicios
rombo --> Menu_Principal

Menu_Perfil --> MostrarQR : Presionar "Mostrar QR"
MostrarQR --> rombo

state MostrarQR {
  VerQR --> VerQR : El sistema muestra el QR
  VerQR --> [*] : Finaliza visualización del QR
}
@enduml
