@startuml
hide empty description

state UsuarioNoRegistrado
state Registro 
state Registrar {
  [*] --> Registrandose
  note on link
    Sistema muestra: Formulario de registro.
  end note

  Registrandose --> RellenandoLogin
  note on link
    Usuario introduce: Nombre, Apellido, Correo Electrónico, Contraseña, Sexo, Peso, Altura.
  end note

  state rombo <<choice>>
  RellenandoLogin --> rombo
  note on link
    Usuario introduce: Marca la casilla "Soy profesor".
  end note

  rombo --> EsProfesor : Sí

  rombo --> EsAlumno : No

  EsAlumno --> RolEstablecido
  note on link
    Sistema muestra: Rol asignado como Alumno.
  end note

  EsProfesor --> RolEstablecido
  note on link
    Sistema muestra: Rol asignado como Profesor.
  end note

  RolEstablecido --> UsuarioRegistrado
  note on link
    Usuario introduce: Crear cuenta
  end note

  UsuarioRegistrado --> [*]
  note on link
    Sistema muestra: Usuario registrado correctamente.
  end note
}

UsuarioNoRegistrado --> Registrar 
Registrar --> Registro

@enduml
