@startuml

  [*] --> UsuarioNoRegistrado
  UsuarioNoRegistrado --> Registrandose
  note on link
    Usuario sin cuenta se registra.
  end note

  UsuarioNoRegistrado --> ProcesoDeInicioDeSesión
  note on link
    Usuario con cuenta se registra.
  end note

  Registrandose --> RellenandoLogin
  note on link
    El usuario ingresa los datos de Login:
    - Nombre
    - Apellido
    - Correo Electrónico
    - Contraseña
    - Peso
    - Altura
    - Objetivo
  end note
  
  state rombo <<choice>>
  RellenandoLogin --> rombo
  note on link
    El usuario usa correo @educantabria.es?
  end note
  
  rombo --> EsProfesor
  note on link
    El usuario ingresa sí
  end note
  
  rombo --> EsAlumno
  note on link
    El usuario ingresa no
  end note

  EsAlumno --> RolEstablecido
  note on link
    El sistema asigna rol de Alumno.
  end note
  
  EsProfesor --> RolEstablecido
  note on link
    El sistema asigna rol de Profesor.
  end note
  
  RolEstablecido --> UsuarioRegistrado
  note on link
    El usuario queda registrado con su rol asignado.
  end note
  
  ProcesoDeInicioDeSesión --> VerificarUsuario
  note on link
    El usuario rellena con correo y contraseña.
  end note
  
  VerificarUsuario --> IniciandoSesión
  note on link
    El sistema verifica correo y contraseña correctos.
  end note
  
  IniciandoSesión --> [*]
  note on link
    El sistema verifica inicio de sesión correcto.
  end note

  UsuarioRegistrado --> [*]
  note on link
    El proceso de registro ha finalizado.
  end note

@enduml

