@startuml
[*] --> UsuarioRegistrado
UsuarioRegistrado --> VolviendoAlInicio
note on link
    Usuario desea regresar a la página de inicio
end note

VolviendoAlInicio --> EnPáginaDeInicio
note on link
    Sistema regresa al inicio
end note

EnPáginaDeInicio --> [*]
note on link
    El usuario a regresado a la página de inicio correctamente
end note
@enduml
