@startuml EnvioDocumentos
left to right direction
actor "Administrador General" as AdminGeneral
actor "Responsable" as Responsable
actor "Destinatario" as Destinatario

package "Manejo de Sesión" {
    usecase "Iniciar Sesión" as MS1
    usecase "Cerrar Sesión" as MS2
}

AdminGeneral --|> Responsable
Responsable <|- Destinatario
Responsable --> MS1
Responsable --> MS2
@enduml
