@startuml ManejoSesion
left to right direction
actor "Administrador" as Administrador
actor "Gestor" as Usuario
actor "Destinatario" as Destinatario

package "Manejo de Sesión" {
    usecase "Iniciar Sesión" as MS1
    usecase "Cerrar Sesión" as MS2
}

Administrador --|> Usuario
Usuario <|- Destinatario
Usuario --> MS1
Usuario --> MS2
@enduml
