@startuml
title Actualizar datos del Usuario

skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "CONFIGURACIÓN"
state endState as "CONFIGURACIÓN"

startState --> ActualizarDatosUsuario
note on link
    <b>Usuario Solicita</b>
    * Actualizar datos del Usuario
end note

ActualizarDatosUsuario --> endState

state ActualizarDatosUsuario {
state 2 as " "
state 3 as " "
state 4 <<choice>>

[*] -down-> 2

2 -down-> 3
note on link
<b>Sistema Solicita</b>
* Foto de perfil
* Nombre
* Apellido
* Fecha de nacimiento
* Email
* Contraseña
* <b>Usuario Egresado</b>
    - Dirección
    - Teléfono
    - Ocupación
<b>Sistema Permite</b>
* Actualizar datos del Usuario
end note

3 -down-> 4
note on link
<b>Usuario introduce</b>
* Foto de perfil
* Nombre
* Apellido
* Fecha de nacimiento
* Email
* Contraseña
* <b>Usuario Egresado</b>
    - Dirección
    - Teléfono
    - Ocupación
end note

4 -down-> [*]
note on link
<b>Sistema Muestra</b>
* Cambios realizados
end note

4 -[#red]-> 2
note on link
<b>Sistema Muestra</b>
* Mensaje de error en los datos introducidos
end note

}
@enduml