@startuml CambiarARetos

hide empty description

state Navegacion_Menus
state Menu_Retos
state CambiarARetos{
    state Cambiar as "Cambiar a Retos"
    [*] --> Cambiar
    note on link
        El profesor introduce ir a Retos
    end note
    Cambiar --> [*]
    note on link
        El sistema muestra el menu Retos
    end note
}

Navegacion_Menus --> CambiarARetos
CambiarARetos --> Menu_Retos

@enduml
