@startuml

hide empty description

state Menu_Retos
state CreandoRetos

state CrearRetos {

    state IniciarRetos as "Crear Retos"
    [*] --> IniciarRetos
    note on link
        El profesor introduce: acceso a CrearRetos.
    end note

    IniciarRetos --> NombreReto
    note on link
        El profesor introduce: nombre del reto.
    end note

    NombreReto --> OpcionReto
    note on link
        El profesor introduce: tipo de reto.
    end note

    state reto <<choice>>
    OpcionReto --> reto
    note on link
        El sistema muestra: opciones de tipo de reto.
    end note

    reto --> RetoObligatorio
    note on link
        El profesor introduce: selección de RetoObligatorio.
    end note

    reto --> RetoOpcional
    note on link
        El profesor introduce: selección de RetoOpcional.
    end note

    RetoObligatorio --> DescripcionReto
    note on link
        El profesor introduce: descripción del reto.
    end note

    RetoOpcional --> DescripcionReto
    note on link
        El profesor introduce: descripción del reto.
    end note

    DescripcionReto --> AsignarClases
    note on link
        El profesor introduce: clases asignadas al reto.
    end note

    AsignarClases --> CrearReto
    note on link
        El sistema muestra: opción de "Crear".
    end note

    CrearReto --> [*]
    note on link
        El sistema muestra: confirmación de reto creado.
    end note
}

Menu_Retos --> CrearRetos
CrearRetos --> CreandoRetos

@enduml
