@startuml CrearEjercicio

hide empty description

state Menu_Rutinas_y_Ejercicios as "Menu Rutinas y Ejercicios"
state Creando_Ejercicio as "Creando Ejercicio"
state CrearEjercicio {
  state RegistrarEjercicio as " "
  [*] --> RegistrarEjercicio
  note on link 
    El profesor introduce: "Crear Ejercicio"
  end note
  RegistrarEjercicio --> SolicitarDatos
  note on link
    El sistema muestra: formulario para crear el ejercicio con los campos: Nombre del ejercicio, Descripción del ejercicio.
  end note
  SolicitarDatos --> AdjuntarDatos 
  note on link
   El profesor introduce el video, nombre y descripción
  end note
  AdjuntarDatos --> ConfirmarCreacion
  note on link
  El profesor introduce "Crear"
  end note
  ConfirmarCreacion --> [*] 
  note on link
   El sistema muestra "Ejercicio creado con éxito"
  end note
}


Menu_Rutinas_y_Ejercicios --> CrearEjercicio
CrearEjercicio --> Creando_Ejercicio


@enduml
