@startuml
[*] --> MostrarEjercicio : Inicio del proceso
state rombo <<choice>>
rombo --> Menu_Perfil
rombo --> Menu_Retos
rombo --> Clasificación
rombo --> Menu_Rutinas_y_Ejercicios
rombo --> Menu_Principal

MostrarEjercicio --> EditarEjercicio : Presionar botón "Editar"
EditarEjercicio --> rombo
state EditarEjercicio {
  SolicitarDatosEdicion : El sistema solicita los datos a editar
  SolicitarDatosEdicion --> ModificarDatos : El profesor modifica nombre, video, descripción o ambos
  ModificarDatos --> ConfirmarEdicion : El profesor presiona "Guardar cambios"
  ConfirmarEdicion --> [*] : Cambios guardados con éxito
}
@enduml
