@startuml EditarEjercicio

hide empty description

state Mostrando_Ejercicio
state EditandoEjercicio

state EditarEjercicio {
  [*] --> SeleccionarEdicion
    note on link
        El profesor introduce: "Editar ejercicio".
    end note
  
  SeleccionarEdicion-->SolicitarEdicion
  note on link
      El sistema muestra: El formmulario para editar los datos del ejercicio.
  end note

  SolicitarEdicion --> EditarDatos
  note on link
      El profesor introduce: cambios en el nombre, video, descripción o ambos.
  end note

  EditarDatos --> ConfirmarEdicion
  note on link
      El profesor introduce: confirmación presionando "Editar".
  end note

  ConfirmarEdicion --> [*]
  note on link
      El sistema muestra: confirmación de que los cambios fueron guardados correctamente.
  end note
}

Mostrando_Ejercicio --> EditarEjercicio
EditarEjercicio --> EditandoEjercicio

@enduml
