@startuml EditarRutina

hide empty description

state Mostrando_Rutina
state EditandoRutina

state EditarRutina {
  [*] --> SeleccionarEdicion
    note on link
        El profesor introduce: "Editar rutina".
    end note
  
  SeleccionarEdicion --> SolicitarEdicion
  note on link
      El sistema muestra: formulario para editar los datos de la rutina.
  end note

  SolicitarEdicion --> ModificarEjercicios
  note on link
      El profesor introduce: actualizaciones a el nombre, objetivo y/o la lista de ejercicios.
  end note

  ModificarEjercicios --> ConfirmarEdicion
  note on link
      El profesor introduce: confirmación presionando "Editar".
  end note

  ConfirmarEdicion --> [*]
  note on link
      El sistema muestra: mensaje de cambios guardados con éxito.
  end note
}

Mostrando_Rutina --> EditarRutina
EditarRutina --> EditandoRutina

@enduml