@startuml EditarEjercicio

hide empty description

state Mostrando_Ejercicio
state EditandoEjercicio

state EditarEjercicio {
  [*] --> SolicitarDatosEdicion
  note on link
      El sistema muestra: solicitud de los datos a editar.
  end note

  SolicitarDatosEdicion --> ModificarDatos
  note on link
      El profesor introduce: modificaciones al nombre, video, descripción o ambos.
  end note

  ModificarDatos --> ConfirmarEdicion
  note on link
      El profesor introduce: confirmación presionando "Guardar cambios".
  end note

  ConfirmarEdicion --> [*]
  note on link
      El sistema muestra: mensaje de cambios guardados con éxito.
  end note
}

Mostrando_Ejercicio --> EditarEjercicio
EditarEjercicio --> EditandoEjercicio

@enduml
