@startuml Evaluar_Retos

hide empty description
state Viendo_Retos_Alumnos
state Evaluando_Reto
state EvaluarReto {
    [*] --> PuntuarReto
    note on link
        El profesor introduce: Una puntuacion de 1 a 5 (estrellas).
    end note
    state " " as Estado
    PuntuarReto --> Estado
    note on link
        El profesor introduce enviar
    end note
    Estado --> [*]
    note on link
        El sistema muestra: Un tick en el reto evaluado
    end note

}

Viendo_Retos_Alumnos --> EvaluarReto
EvaluarReto --> Evaluando_Reto

@enduml
