@startuml Evaluar_Retos

hide empty description
state Viendo_Retos_Alumnos
state Evaluando_Reto
state EvaluarReto {
    [*] --> Evaluar_Reto
    note on link
        El sistema muestra: inicio de la evaluación del reto.
    end note

    Evaluar_Reto --> DescripcionReto
    note on link
        El sistema muestra: la descripción del reto.
    end note

    DescripcionReto --> MostrarEvidencia
    note on link
        El sistema muestra: la evidencia del reto.
    end note

    MostrarEvidencia --> ValidarEvidencia
    note on link
        El profesor introduce: calificación y comentarios sobre el reto.
    end note

    ValidarEvidencia --> Aprobado
    note on link
        El sistema muestra: confirmación de reto aprobado.
    end note

    ValidarEvidencia --> Rechazado
    note on link
        El sistema muestra: notificación de reto rechazado.
    end note

    Aprobado --> [*]
    note on link
        El sistema muestra: evaluación finalizada con éxito.
    end note

    Rechazado --> [*]
    note on link
        El sistema muestra: evaluación finalizada con rechazo.
    end note
}

Viendo_Retos_Alumnos --> EvaluarReto
EvaluarReto --> Evaluando_Reto

@enduml
