@startuml IngresarAlSistema

hide empty description

state Profesor 
state choice <<choice>>
state Pagina_Principal
state IngresarAlSistema{
    [*] --> [*]
    note on link
        El sistema muestra la página principal 
    end note
}

Profesor --> choice
Alumno --> choice
choice --> IngresarAlSistema
IngresarAlSistema --> Pagina_Principal

@enduml