@startuml
state Menu_Perfil_Profesor
state rombo1 <<choice>>
state rombo2 <<choice>>
state Crear_Clase
state Ver_Mis_Clases
state Mostrar_QR
state Menu_Perfil
state Menu_Retos
state Menu_Rutinas_y_Ejercicios
state Menu_Principal

[*] --> Menu_Perfil_Profesor : "El profesor solicita entrar a\nMenu Perfil Profesor"

Menu_Perfil_Profesor --> rombo2 : "El profesor solicita acceder a las opciones del perfil"
rombo2 --> Crear_Clase
rombo2 --> Ver_Mis_Clases
rombo2 --> Mostrar_QR 


Menu_Perfil_Profesor --> rombo1 : "El profesor solicita ir a otra opción"
rombo1 --> Menu_Perfil
rombo1 --> Menu_Retos
rombo1 --> Menu_Rutinas_y_Ejercicios
rombo1 --> Menu_Principal
rombo1 --> Menu_Perfil_Profesor : "Volver al menú"

Menu_Perfil_Profesor --> [*]
@enduml