@startuml
state MenuPerfilProfesor
state rombo1 <<choice>>
state rombo2 <<choice>>
state Crear_Clase
state Ver_Mis_Clases
state Mostrar_QR
state Menu_Perfil
state Menu_Retos
state Menu_Rutinas_y_Ejercicios
state Menu_Principal

[*] --> MenuPerfilProfesor : "El profesor solicita entrar a\nMenu Perfil Profesor"

MenuPerfilProfesor --> rombo2 : "El profesor solicita acceder a las opciones del perfil"
rombo2 --> Crear_Clase
rombo2 --> Ver_Mis_Clases
rombo2 --> Mostrar_QR 


MenuPerfilProfesor --> rombo1 : "El profesor solicita ir a otra opción"
rombo1 --> Menu_Perfil
rombo1 --> Menu_Retos
rombo1 --> Menu_Rutinas_y_Ejercicios
rombo1 --> Menu_Principal
rombo1 --> MenuPerfilProfesor : "Volver al menú"

MenuPerfilProfesor --> [*]
@enduml