@startuml MostrarEjercicio

hide empty description

state Menu_Rutinas_y_Ejercicios
state MostrandoEjercicio
state MostrarEjercicio {
  [*] --> SeleccionarEjercicio
  note on link
    El profesor selecciona un ejercicio
  end note

  SeleccionarEjercicio --> VerDetalles
  note on link
    El sistema muestra los detalles del ejercicio
  end note
  VerDetalles --> [*]
}

Menu_Rutinas_y_Ejercicios --> MostrarEjercicio
MostrarEjercicio --> MostrandoEjercicio

@enduml
