@startuml
[*] --> Menu_Rutinas_y_Ejercicios : Inicio del proceso
state rombo <<choice>>
rombo --> Menu_Perfil
rombo --> Menu_Retos
rombo --> Clasificación
rombo --> Menu_Rutinas_y_Ejercicios
rombo --> Menu_Principal

Menu_Rutinas_y_Ejercicios --> ListaEjercicios : Presionar botón "Ejercicios"
ListaEjercicios --> MostrarEjercicio : Seleccionar un ejercicio de la lista
MostrarEjercicio --> rombo
state MostrarEjercicio {
  [*] --> VerDetalles : El sistema muestra los detalles del ejercicio
  VerDetalles --> EditarEjercicio : Presionar botón "Editar"
  VerDetalles --> [*] : Finaliza visualización
}
@enduml
