@startuml MostrarRutina

hide empty description

state Menu_Rutinas_y_Ejercicios
state MostrandoRutina

state MostrarRutina {
  state VerRutina as "Mostar Rutina"
  [*] --> VerRutina
  note on link
    El profesor introduce ver la rutina
  end note
  VerRutina --> [*]
  note on link
    El sistema muestra la rutina
  end note
}

Menu_Rutinas_y_Ejercicios --> MostrarRutina
MostrarRutina --> MostrandoRutina
@enduml
