@startuml Mostrar_QR

hide empty description

state Menu_Perfil
state Mostrando_QR
state Mostrar_QR{
    state Mostrar as "Mostrar QR"
    [*] --> Mostrar
    note on link
        El profesor introduce: Mostrar QR   
    end note
    Mostrar --> [*]
    note on link
        El sistema muestra el QR
    end note
}

Menu_Perfil --> Mostrar_QR
Mostrar_QR --> Mostrando_QR

@enduml