@startuml Ver_Alumnos

hide empty description

state Viendo_Mis_Clases
state Viendo_Alumnos
state Ver_Alumnos {
    state VerAlumnos as "Ver Alumnos"
    [*] --> VerAlumnos
    note on link
        El profesor introduce ver los alumnos
    end note
    VerAlumnos --> [*]
    note on link
        El sistema muestra todos los alumnos
    end note
}

Viendo_Mis_Clases --> Ver_Alumnos
Ver_Alumnos --> Viendo_Alumnos

@enduml