@startuml Ver_Retos_Alumnos

hide empty description

state Viendo_Alumnos
state Viendo_Retos_Alumnos
state Ver_Retos_Alumnos {
    [*] --> SeleccionarAlumno
    note on link
        El profesor introduce ver retos de un alumno
    end note
    SeleccionarAlumno --> EstadoRetos
    note on link
        El sistema muestra los retos del alumno y su estado
    end note
    EstadoRetos --> RevisarReto
    note on link
        El profesor introduce un reto para revisar
    end note
    RevisarReto --> [*]
    note on link
        El sistema muestra el reto y la evidencia del alumno
    end note
}

Viendo_Alumnos --> Ver_Retos_Alumnos
Ver_Retos_Alumnos --> Viendo_Retos_Alumnos

@enduml