@startuml Ver_Alumnos_Clase

hide empty description

state Menu_Clasificacion
state Viendo_Alumnos_Clase

state VerClasificacionDentroDeClase {
  state Ver_Alumnos as "Ver Alumnos"
  [*] --> Ver_Alumnos
  note on link
    El profesor introduce: una clase 
  end note
    Ver_Alumnos --> [*]
    note on link
    El sistema muestra la clasificación de la clase seleccionada
    end note
}

Menu_Clasificacion --> VerClasificacionDentroDeClase
VerClasificacionDentroDeClase --> Viendo_Alumnos_Clase

@enduml