@startuml Ver_Alumnos_Clase

hide empty description

state Menu_Clasificacion
state Viendo_Alumnos_Clase

state Ver_Alumnos_Clase {
  state Ver_Alumnos as "Ver Alumnos"
  [*] --> Ver_Alumnos
  note on link
    El profesor introduce ver los alumnos de la clase
  end note
    Ver_Alumnos --> [*]
    note on link
    El sistema muestra los alumnos de la clase
    end note
}

Menu_Clasificacion --> Ver_Alumnos_Clase
Ver_Alumnos_Clase --> Viendo_Alumnos_Clase

@enduml