@startuml Ver_Mis_Clases

hide empty description

state Menu_Perfil
state Viendo_Mis_Clases
state Ver_Mis_Clases{
    state VerMisClases as "Ver mis clases"
    [*] --> VerMisClases
    note on link
        El profesor introduce ver mis clases
    end note
    VerMisClases --> ClasesDisponibles
    note on link
        El sistema muestra las clases disponibles
    end note
    ClasesDisponibles --> ClaseSeleccionada
    note on link
        El profesor introduce ver una clase
    end note
    ClaseSeleccionada --> [*]
    note on link
        El sistema muestra la clase seleccionada
    end note
    ClaseSeleccionada --> ClasesDisponibles
    note on link
        El profesor introduce ver las clases otra vez
    end note
}

Menu_Perfil --> Ver_Mis_Clases
Ver_Mis_Clases --> Viendo_Mis_Clases

@enduml