@startuml Ver_Retos_Alumnos

hide empty description

state Viendo_Alumnos
state Viendo_Retos_Alumnos
state Ver_Retos_Alumnos {
    [*] --> VerDetalles
    note on link
        El sistema muestra el estado del reto
    end note
    VerDetalles --> RevisarReto
    note on link
        El profesor introduce evaluar retos
    end note
    VerDetalles --> [*]
    note on link
        El profesor introduce salir
    end note

}

Viendo_Alumnos --> Ver_Retos_Alumnos
Ver_Retos_Alumnos --> Viendo_Retos_Alumnos

@enduml