@startuml VerClasificacion

hide empty description

state Navegacion_Menus
state Menu_Clasificacion
state VerClasificacion{
    state Cambiar as "Ver Clasificación"
    [*] --> Cambiar
    note on link
        El profesor introduce que quiere ir a Clasificación
    end note
    Cambiar --> [*]
    note on link
        El sistema muestra Clasificación
    end note
}

Navegacion_Menus --> VerClasificacion
VerClasificacion --> Menu_Clasificacion

@enduml
