@startuml VerPerfil

hide empty description

state NavegacionMenus
state MenuPerfil
state VerPerfil{
    state Cambiar as "Ver Perfil"
    [*] --> Cambiar
    note on link
        El profesor introduce que quiere ir a su perfil
    end note
    Cambiar --> [*]
    note on link
        El sistema muestra el perfil del profesor
    end note
}

NavegacionMenus --> VerPerfil
VerPerfil --> MenuPerfil
@enduml
