@startuml
state Profesor {
    [*] --> Libre

    state Libre {
        [*] --> CargaVerificada
        CargaVerificada --> [*]: No está lleno
    }

    state EnProceso {
        [*] --> AsignaturaValidada
        AsignaturaValidada --> AsignaturaAsignada
        AsignaturaAsignada --> [*]
    }

    Libre --> EnProceso: Iniciar asignaciones
    EnProceso --> Lleno: Carga máxima alcanzada
    Lleno --> Libre: Liberar carga
    EnProceso --> Libre: Cancelar asignaciones
}
@enduml