@startuml
Package UNEATLANTICO{
    hide circle
    hide empty members
    
    Asignacion --> Profesor : asigna
    Asignacion --> Asignatura : corresponde
    Asignacion --> MemoriaAcademica : cumple
    MemoriaAcademica --> Indicador : meta y valores
    Indicador --> Profesor : extrae datos
    Asignatura .. Titulacion : pertenece
    Titulacion --> Profesor : de
    Profesor --> MemoriaAcademica : mira
    Profesor --> Asignatura : imparte
}
@enduml