@startuml
state Profesor {
    [*] --> Libre

    state Libre {
        [*] --> CargaVerificada
    }

    state EnProceso {
        [*] --> AsignaturaValidada
        AsignaturaValidada --> AsignaturaAsignada
    }

    Libre --> EnProceso: No está lleno
    EnProceso --> Lleno: Asignación completa
    Lleno --> Libre: Reset
    Lleno --> [*]: Carga máxima alcanzada
    EnProceso --> Libre: Cancelar asignaciones
}
@enduml