@startuml
state Asignatura {
    [*] --> Libre

    state Libre {
        [*] --> CapacidadVerificada
    }

    state EnProceso {
        [*] --> ProfesorValidado
        ProfesorValidado --> ProfesorAsignado
    }

    Libre --> EnProceso: No está llena
    EnProceso --> Completa: Asignacion completa
    Completa --> Libre: Reset
    Completa --> [*]: Todas las horas cubiertas
    EnProceso --> Libre: Cancelar proceso
}
@enduml