@startuml IniciarSesion

hide empty description

state Usuario
state IniciarSesion{
    state " " as Estado1
    state " " as Estado2
    state " " as Estado3

    [*] --> Estado1
    note on link
        El Usuario solicita iniciar sesión
    end note
    Estado1 -[#green]-> Estado2
    note on link
        El Sistema solicita
        - Correo
        - Contraseña
    end note
    Estado2 -[#green]-> Estado3
    note on link
        El Usuario introduce
        - Correo
        - Contraseña
    end note
    Estado3 --> [*]
    note on link
        El sistema identifica el departamento al que pertenece
    end note

    Estado3 -[#red]-> Estado1
    note on link
        Datos incorrectos
    end note
}
state rombo <<choice>>
state Profesor
state RRHH
state Calidad
State Admin
State Ordenación

Usuario --> IniciarSesion
IniciarSesion --> rombo

rombo --> Profesor
rombo --> RRHH
rombo --> Calidad
rombo --> Admin
rombo --> Ordenación

@enduml