@startuml ProfesorCasosDeUso
!define RECTANGLE(x) rectangle x

RECTANGLE(PROFESOR)
RECTANGLE(PAGINA_PRINCIPAL)
RECTANGLE(MENU_RUTINAS_EJERCICIOS)
RECTANGLE(MENU_RETOS)
RECTANGLE(MENU_CLASIFICACION)
RECTANGLE(MENU_PERFIL)
RECTANGLE(CREAR_RUTINA)
RECTANGLE(CREAR_EJERCICIO)
RECTANGLE(EDITAR_RUTINA)
RECTANGLE(EDITAR_EJERCICIO)
RECTANGLE(CREAR_RETOS)
RECTANGLE(EDITAR_RETOS)
RECTANGLE(VER_CLASES)
RECTANGLE(VER_ALUMNOS_CLASE)
RECTANGLE(CREAR_CLASE)
RECTANGLE(MOSTRAR_QR)
RECTANGLE(VER_MIS_CLASES)
RECTANGLE(VER_ALUMNOS)
RECTANGLE(VER_RETOS_ALUMNOS)
RECTANGLE(EVALUAR_RETOS)


PROFESOR --> PAGINA_PRINCIPAL : Ingresar al sistema

PAGINA_PRINCIPAL --> MENU_RUTINAS_EJERCICIOS : Gestionar rutinas y ejercicios
PAGINA_PRINCIPAL --> MENU_RETOS : Gestionar retos
PAGINA_PRINCIPAL --> MENU_CLASIFICACION : Consultar clasificación
PAGINA_PRINCIPAL --> MENU_PERFIL : Revisar perfil

MENU_RUTINAS_EJERCICIOS --> CREAR_RUTINA : Crear rutina
MENU_RUTINAS_EJERCICIOS --> CREAR_EJERCICIO : Crear ejercicio
MENU_RUTINAS_EJERCICIOS --> EDITAR_RUTINA : Editar rutina
MENU_RUTINAS_EJERCICIOS --> EDITAR_EJERCICIO : Editar ejercicio
MENU_RUTINAS_EJERCICIOS --> MENU_RETOS : Cambiar de menu
MENU_RUTINAS_EJERCICIOS --> MENU_CLASIFICACION : Cambiar de menu
MENU_RUTINAS_EJERCICIOS --> MENU_PERFIL : Cambiar de menu

CREAR_RUTINA --> MENU_RUTINAS_EJERCICIOS : Volver al menú rutinas y ejercicios
CREAR_EJERCICIO --> MENU_RUTINAS_EJERCICIOS : Volver al menú rutinas y ejercicios
EDITAR_RUTINA --> MENU_RUTINAS_EJERCICIOS : Volver al menú rutinas y ejercicios
EDITAR_EJERCICIO --> MENU_RUTINAS_EJERCICIOS : Volver al menú rutinas y ejercicios

MENU_RETOS --> CREAR_RETOS : Crear retos
MENU_RETOS --> EDITAR_RETOS : Editar retos
CREAR_RETOS --> MENU_RETOS : Volver al menú retos
EDITAR_RETOS --> MENU_RETOS : Volver al menú retos
MENU_RETOS --> MENU_PERFIL : Cambiar de menu
MENU_RETOS --> MENU_CLASIFICACION : Cambiar de menu
MENU_RETOS --> MENU_RUTINAS_EJERCICIOS : Cambiar de menu

MENU_CLASIFICACION --> VER_CLASES : Ver clases
VER_CLASES --> VER_ALUMNOS_CLASE : Ver alumnos dentro de clases
VER_ALUMNOS_CLASE --> MENU_CLASIFICACION : Volver al menú clasificación
VER_CLASES --> MENU_CLASIFICACION : Volver al menú clasificación

MENU_PERFIL --> CREAR_CLASE : Crear clase
MENU_PERFIL --> MOSTRAR_QR : Mostrar QR en centro deportivo
MENU_PERFIL --> VER_MIS_CLASES : Ver mis clases
MENU_PERFIL --> PROFESOR : Cerrar sesión
MENU_PERFIL --> MENU_RETOS : Cambiar de menu
MENU_PERFIL --> MENU_CLASIFICACION : Cambiar de menu
MENU_PERFIL --> MENU_RUTINAS_EJERCICIOS : Cambiar de menu

VER_MIS_CLASES --> VER_ALUMNOS : Ver alumnos
VER_ALUMNOS --> VER_RETOS_ALUMNOS : Ver retos alumnos
VER_RETOS_ALUMNOS --> EVALUAR_RETOS : Evaluar/calificar retos
EVALUAR_RETOS --> VER_RETOS_ALUMNOS : Volver a retos alumnos
VER_RETOS_ALUMNOS --> VER_ALUMNOS : Volver a alumnos
VER_ALUMNOS --> VER_MIS_CLASES : Volver a mis clases

CREAR_CLASE --> MENU_PERFIL : Volver al perfil
MOSTRAR_QR --> MENU_PERFIL : Volver al perfil
MENU_RUTINAS_EJERCICIOS --> PAGINA_PRINCIPAL : Volver a página principal
MENU_RETOS --> PAGINA_PRINCIPAL : Volver a página principal
MENU_CLASIFICACION --> PAGINA_PRINCIPAL : Volver a página principal
MENU_PERFIL --> PAGINA_PRINCIPAL : VolvER a página principal
@enduml
