@startuml DiagramaDeObjetos
title Automatización de Guías Docentes

object "guia1 : Guia" as guia1
object "ana : DirecciónDeCalidad" as ana
object "jorge : TécnicoDeCalidad" as jorge
object "breñosa : Profesor" as breñosa
object "masias : DirectorDeGrado" as masias
object "temario : Contenido" as temario
object "informatica : Titulacion" as informatica
object "programacion : Asignatura" as programacion
object "version1 : Version" as version1

guia1 --* informatica : "forma_parte_de"
guia1 o-- programacion : "incluye"

programacion <-down- temario : "pertenece_a"
programacion o-down- informatica : "forma_parte"

guia1 -down- ana : "es_auditada_por"
guia1 <-down- jorge : "es_editada_por"
guia1 *-down- version1 : "tiene"

temario <-- informatica : "es_definido_por"

ana -- jorge : "supervisa_a"
ana -- breñosa : "audita_a"
ana -l-- masias : "audita_a"

breñosa o-up-- informatica : "está_asociado_con"
masias o-up-- informatica : "está_asociado_con"

temario <- masias : "aprueba_o_rechaza"
temario <-- breñosa : "edita"

@enduml
