@startuml Diagrama de Clases
title Automatización de Guías Docentes - Refinado

class Profesor
class DirectorDeGrado
class TécnicoDeCalidad
class DirecciónDeCalidad
class Guia
class Contenido
class Titulacion
class Asignatura
class Version

Guia --* Titulacion: forma_parte_de
Guia o-- Asignatura: incluye

Asignatura <-down- Contenido: pertenece_a
Asignatura o-down- Titulacion: forma_parte

Guia -down- DirecciónDeCalidad: es_auditada_por
Guia <-down- TécnicoDeCalidad: es_editada_por
Guia *-down- Version: tiene

Contenido <-- Titulacion: es_definido_por

DirecciónDeCalidad -- TécnicoDeCalidad: supervisa_a
DirecciónDeCalidad -- Profesor: audita_a
DirecciónDeCalidad -l-- DirectorDeGrado: audita_a

Profesor o-up-- Titulacion: está_asociado_con
DirectorDeGrado o-up-- Titulacion: está_asociado_con

Contenido <- DirectorDeGrado: aprueba_o_rechaza
Contenido <-- Profesor: edita

@enduml