@startuml
actor Estudiante
actor Administracion
actor SistemaDeCampus as Sistema

Estudiante --> (Acceder al campus)
Estudiante --> (Realizar test inicial)
Estudiante --> (Acc
eder a recursos)
Estudiante --> (Realizar tests de seguimiento)

Administracion --> (Evaluar test inicial)
Administracion --> (Notificar aceptación/rechazo)

(Sistema) -- (Acceder al campus)
(Sistema) -- (Proveer test inicial)
(Sistema) -- (Proveer recursos)
(Sistema) -- (Proveer tests de seguimiento)

Estudiante -left-> (Acceder al campus): utiliza
(Sistema) -up-> (Acceder al campus): autentica
Administracion -down-> (Evaluar test inicial): evalua
@enduml
