@startuml
class Estudiante {
  +nombre: String
  +correo: String
  +estado: String
  +realizarTest()
  +accederRecursos()
}

class Test {
  +puntuacion: int
  +fecha: Date
  +tipo: String
  +realizar()
}

class Recurso {
  +tipo: String
  +dificultad: String
  +consultar()
}

class Administracion {
  +nombre: String
  +evaluarTest()
}

Estudiante --> Test : "realiza"
Estudiante --> Recurso : "consulta"
Administracion --> Test : "evalua"
@enduml
