@startuml Diagrama_de_Objetos_Beca
title Diagrama de Objetos - Ejemplo de Plataforma de Gestión de Becas

object "Plataforma : Novus" as plataforma {
  Objetivo = "Gestión de Becas"
}

object "Administrador : Diego" as administrador {
  Nombre = "Diego"
  Apellido = "Pérez"
  Email = "diego.perez@ejemplo.com"
}

object "Becario : Samuel" as candidato {
  DNI = "12345678"
  Carnet de Estudiante = "BEC2024"
  Dirección = "Calle Falsa 123"
  Porcentaje de Beca = 100%
}

object "Prueba : Aptitud" as pruebas {
  Descripción = "Pruebas de conocimiento"
}
object "Prueba : Especialización" as pruebas1 {
  Descripción = "Pruebas de control"
}

object "Capacitación : Programa de Capacitación" as capacitacion {
}

object "videoTutorial : VIDEO_TUTORIAL" as videoTutorial {
}

object "documentación : DOCUMENTACIÓN" as documentacion {
}

object "Requisito : Aprobar" as requisito {
  Descripción = "Aprobar pruebas de selección"
}

plataforma -d-- administrador : "administra"
plataforma -d-- candidato : "tiene acceso"

plataforma -d-- pruebas : "incluye"
plataforma -d-- pruebas1 : "incluye"
plataforma -d-- capacitacion : "ofrece"

capacitacion  -d-- videoTutorial : "incluye"
capacitacion  -d-- documentacion : "incluye"

candidato -d-- requisito : "cumple"

@enduml
