@startuml AdministradorContextDiagram


!define RECTANGLE(x) rectangle x


RECTANGLE(ADMINISTRADOR) #LightPink
RECTANGLE(PAGINA_PRINCIPAL) #LightBlue
RECTANGLE(NAVEGACION_MENUS) #SkyBlue


RECTANGLE(MENU_GESTIONAR_OFERTAS) #LightYellow
RECTANGLE(VER_ESTADISTICAS) #LightYellow

ADMINISTRADOR -[#Black]-> PAGINA_PRINCIPAL : .
PAGINA_PRINCIPAL -[#SkyBlue]-> NAVEGACION_MENUS : Navegar por menús
NAVEGACION_MENUS -[#SkyBlue]-> PAGINA_PRINCIPAL : Regresar al inicio


NAVEGACION_MENUS -[#LightBlue]-> MENU_GESTIONAR_OFERTAS : Gestionar ofertas
NAVEGACION_MENUS -[#LightBlue]-> VER_ESTADISTICAS : Ver estadísticas


MENU_GESTIONAR_OFERTAS -[#LightBlue]-> NAVEGACION_MENUS : Cambiar menú
VER_ESTADISTICAS -[#LightBlue]-> NAVEGACION_MENUS : Cambiar menú

@enduml