@startuml AdministradorContextDiagram

!define RECTANGLE(x) rectangle x

RECTANGLE(MENU_GESTIONAR_OFERTAS) #Yellow

RECTANGLE(VER_OFERTAS) #LightCoral
RECTANGLE(ACEPTANDO_OFERTA) #Yellow
RECTANGLE(CERRANDO_OFERTA) #PaleGreen
RECTANGLE(CANCELANDO_OFERTA) #LightSalmon
RECTANGLE(NAVEGACION_MENUS) #SkyBlue


MENU_GESTIONAR_OFERTAS -[#LightCoral]-> VER_OFERTAS : Ver Ofertas
VER_OFERTAS -[#SkyBlue]-> NAVEGACION_MENUS : Cambiar Menú


VER_OFERTAS -[#Yellow]-> ACEPTANDO_OFERTA : Aceptar Oferta
VER_OFERTAS -[#PaleGreen]-> CERRANDO_OFERTA : Cerrar Oferta
VER_OFERTAS -[#LightSalmon]-> CANCELANDO_OFERTA : Cancelar Oferta


ACEPTANDO_OFERTA -[#LightCoral]-> VER_OFERTAS : Ver Ofertas
CERRANDO_OFERTA -[#LightCoral]-> VER_OFERTAS : Ver Ofertas
CANCELANDO_OFERTA -[#LightCoral]-> VER_OFERTAS :  Ver Ofertas

@enduml

