@startuml
hide empty description

[*] --> InicioSesion : Administrador inicia sesión

state "Gestión de Usuarios" as GestionUsuarios {
    [*] --> CrearUsuario : Agregar un nuevo usuario
    CrearUsuario --> ModificarUsuario : Editar información
    ModificarUsuario --> EliminarUsuario : Eliminar usuario
    EliminarUsuario --> [*] : Salir del módulo
}

state "Gestión de Asignaturas" as GestionAsignaturas {
    [*] --> CrearAsignatura : Registrar nueva asignatura
    CrearAsignatura --> ModificarAsignatura : Actualizar detalles
    ModificarAsignatura --> EliminarAsignatura : Eliminar asignatura
    EliminarAsignatura --> [*] : Salir del módulo
}

state "Gestión de Retos" as GestionRetos {
    [*] --> GenerarRetos : Crear un nuevo Reto
    GenerarRetos --> [*] : Reto listo
}

InicioSesion --> GestionUsuarios : Administrar usuarios
InicioSesion --> GestionAsignaturas : Administrar asignaturas
InicioSesion --> GestionRetos : Consultar aplicacion
GestionUsuarios --> InicioSesion : Regresar al menú principal
GestionAsignaturas --> InicioSesion : Regresar al menú principal
GestionRetos --> InicioSesion : Regresar al menú principal

InicioSesion --> CerrarSesion : Cerrar sesión
CerrarSesion --> [*] : Finalizar
@enduml
