@startuml manejoNotificaciones
actor "Tiempo" as Tiempo

package "Recordatorios" {
    usecase "Enviar recordatorio de confirmación de lectura al destinatario" as R1
    usecase "Enviar recordatorio de firma al destinatario" as R2
    usecase "Enviar notificacion de confirmación/firma del destinatario al remitente" as R3
}

Tiempo --> R1
Tiempo --> R2
Tiempo --> R3
@enduml
