@startuml
skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "MENU_PRINCIPAL"
state endState as "LISTANDO_ACCIONES"

startState --> ListarAcciones
note on link
    <b>Usuario Solicita</b>
    * Listar acciones
end note

ListarAcciones --> endState
ListarAcciones -[#red]> endState

state ListarAcciones{
    state solicitudFiltros as " "
    state envioFiltros as " "
    state revisionFiltrosEnviados <<choice>>

    [*] --> solicitudFiltros
    note on link
        <b>Sistema Muestra</b>
        Lista de acciones
    end note

    solicitudFiltros -r-> [*]

    solicitudFiltros --> envioFiltros
    note on link
        <b>Sistema Permite Filtrar</b>
        * <b> Filtros opcionales </b>
            - Términos de búsqueda
            - Usuario
            - Rango de fechas
    end note

    envioFiltros --> revisionFiltrosEnviados
    note on link
        <b>Usuario Introduce</b>
        * <b> Filtros opcionales </b>
            - Términos de búsqueda
            - Usuario
            - Rango de fechas
    end note

    revisionFiltrosEnviados -[#red]-> [*]
    note on link
        <b>Sistema Muestra</b>
        Mensaje de error

    end note

    revisionFiltrosEnviados --> [*]
    note on link
        <b>Sistema Muestra</b>
        Lista de acciones filtrada

    end note
}
@enduml