@startuml
skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "LISTANDO_GRUPOS"
state endState as "LISTANDO_GRUPOS"

startState --> ListarGrupos

ListarGrupos --> endState

state ListarGrupos {
    state solicitudFiltros as " "
    state envioFiltros as " "
    state revisionFiltrosEnviados <<choice>>
    state usuarioSolicita as "<b>Usuario Solicita:</b> \n Listar grupos"

    usuarioSolicita -> solicitudFiltros
    [*] --> solicitudFiltros
    note on link
        <b>Sistema Muestra</b>
        Lista de grupos
    end note

    solicitudFiltros -r-> [*]

    solicitudFiltros --> envioFiltros
    note on link
        <b>Sistema Solicita</b>
        * <b> Filtros opcionales </b>
            - Términos de búsqueda
            - Nombre del grupo
            - Usuario del grupo
        <b>Sistema Permite</b>
        * Listar grupos
    end note

    envioFiltros --> revisionFiltrosEnviados
    note on link
        <b>Usuario Introduce</b>
        * <b> Filtros opcionales </b>
            - Términos de búsqueda
            - Nombre del grupo
            - Usuario del grupo
    end note

    revisionFiltrosEnviados -[#red]-> solicitudFiltros
    note on link
        <b>Sistema Muestra</b>
        Mensaje de error
    end note

    revisionFiltrosEnviados --> [*]
    note on link
        <b>Sistema Muestra</b>
        Lista de grupos filtrada

    end note
}
@enduml