@startuml
left to right direction
actor Moderador

package Aplicacion{

    package publicaciones{
        usecase "Revisar publicaciones" as UC1
        usecase "Eliminar publicaciones" as UC2
        usecase "Revisar reportes de contenido" as UC4

usecase "Revisar comentarios" as UC6
    }

    package Usuarios{
        usecase "Suspender usuarios" as UC3
        usecase "Enviar advertencias" as UC5
        usecase "Desbloquear usuarios" as UC8
    }
usecase "Bloquear palabras o expresiones" as UC7

usecase "Eliminar Comunidad" as UC9
}

Moderador --> UC1
Moderador --> UC2
Moderador --> UC3
Moderador --> UC4
Moderador --> UC5
Moderador --> UC6
Moderador --> UC7
Moderador --> UC8
Moderador --> UC9

@enduml
