@startuml
title Caso de uso: Tomar un Examen

skinparam {
    NoteBackgroundColor #lightYellow
    ArrowColor #blue
    NoteBorderColor #blue
    linetype polyline
}

state startState as "PÁGINA PRINCIPAL"
state endState as "PÁGINA PRINCIPAL"

startState --> AbrirExamen
note on link
    <b>Usuario Accede</b>
    * Selecciona el examen desde la lista
end note

AbrirExamen --> ResponderExamen
note on link
    <b>Sistema Muestra</b>
    * Preguntas del examen
end note

state ResponderExamen {
    state "Responder Pregunta" as ResponderPregunta
    state "Editar Respuesta" as EditarRespuesta

    [*] --> ResponderPregunta
    ResponderPregunta --> EditarRespuesta : Usuario decide cambiar
    note on link
        <b>Usuario Edita</b>
        * Modifica la respuesta seleccionada
    end note
    EditarRespuesta --> ResponderPregunta

    ResponderPregunta --> [*] : Todas las preguntas respondidas
}

ResponderExamen --> EnviarExamen
note on link
    <b>Usuario Confirma</b>
    * Envío del examen completo
end note

EnviarExamen --> NotificacionPendiente
note on link
    <b>Sistema Muestra</b>
    * "Tu examen ha sido enviado con éxito"
    * "Resultados estarán disponibles próximamente"
    
end note

NotificacionPendiente --> endState
note on link
    <b>Sistema Redirige</b>
    * Página principal
end note
@enduml
