@startuml
title Casos de Uso (Postulante) - Realizar Capacitación

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

left to right direction

actor Postulante

folder "Capacitación" as capacitacion {
    Postulante --> (Realizar Capacitación)
    Postulante --> (Consultar Disponibilidad de Capacitación)
}

@enduml
