@startuml manejo_sesion_logout
skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #black
    linetype polyline
}

skinparam state {
    BackgroundColor #whiteSmoke
}

hide empty description

state startState as "MENU_PRINCIPAL"
state endState as "VISTA_LOGIN"

startState --> ManejoLogout

state ManejoLogout {
    state Logout as " "

    Logout --> ValidarCierreSesion
    note on link
        <b>Usuario solicita</b>
        * Cerrar sesión
    end note

    ValidarCierreSesion --> [*]
    note on link
        <b>Sistema finaliza</b>
        * Sesión activa
    end note
}

    ValidarCierreSesion -[#red]-> Logout
    note on link
        <b>Sistema muestra</b>
        * Error: "Ocurrió un error al cerrar sesión"
    end note

ManejoLogout --> endState

@enduml
