@startuml manejo_sesion
skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #black
    linetype polyline
}

skinparam state {
    BackgroundColor #whiteSmoke
}

hide empty description

state startState as "VISTA_LOGIN"
state endState as "VISTA_LOGIN"

startState --> ManejoSesion

ManejoSesion --> endState

state ManejoSesion {
    state IngresoCredenciales as " "
    state ValidarCredenciales <<choice>>
    state InicioSesionCorrecto as " "
    state Logout as " "

    IngresoCredenciales --> ValidarCredenciales
    note on link
        <b>Usuario introduce</b>
        * Nombre de usuario
        * Contraseña
    end note

    ValidarCredenciales -[#red]-> IngresoCredenciales
    note on link
        <b>Sistema muestra</b>
        * Error: "Credenciales inválidas"
    end note

    ValidarCredenciales --> InicioSesionCorrecto
    note on link
        <b>Sistema redirige</b>
        * A la pantalla principal
    end note

    InicioSesionCorrecto --> Logout
    note on link
        <b>Usuario solicita</b>
        * Cerrar sesión
    end note

    Logout --> [*]
    note on link
        <b>Sistema finaliza</b>
        * Sesión activa
        <b>Redirige</b> a login
    end note
}

@enduml
