@startuml
hide empty description

[*] --> Inscrito : Inscribirse en asignatura
Inscrito --> EnClaseTeorica : Asistir a clases teóricas
Inscrito --> EnClasePractica : Asistir a clases prácticas

EnClaseTeorica --> EnEvaluacion : Completar teoría
EnClasePractica --> Rutina : Recibir rutina

state Rutina {
    AsignandoRutina --> RutinaNoAsignada : Rutina no asignada
    AsignandoRutina --> RutinaAsignada : Rutina asignada
    RutinaAsignada --> EjecutandoRutina : Comenzar rutina
    EjecutandoRutina --> EjecutandoRutina : Continuar rutina
    EjecutandoRutina --> RutinaTerminada : Rutina completada
}

Rutina --> EnEvaluacion : Completar prácticas
Rutina --> EnClaseTeorica : Refuerzo teórico

EnEvaluacion --> FinDelCurso : Cierre de asignatura
FinDelCurso --> [*] : Terminar curso

@enduml
