@startuml diagramaContextoDestinatario
state "LISTANDO_MENSAJES" as ListarMensajes
state "LEYENDO_MENSAJE" as LeyendoMensaje
state "LEYENDO_DOCUMENTO" as LeyendoDocumento

[*] --> ListarMensajes
    note on link
        Destinatario 
        - Iniciar sesión
        - Listar mensajes
    end note

ListarMensajes -> [*]
    note on link
        Destinatario 
        Cerrar sesión
    end note


ListarMensajes --> LeyendoMensaje
    note on link
        Abrir mensaje
    end note

LeyendoMensaje -> LeyendoDocumento
    note on link
        Abrir documento
    end note

LeyendoDocumento --> LeyendoDocumento
    note on link
        - Confirmar Lectura
        - Firmar Documento
    end note

LeyendoDocumento --> LeyendoMensaje
    note on link
        Abrir mensaje
    end note

LeyendoMensaje --> ListarMensajes
    note on link
        Listar mensajes
    end note

@enduml