@startuml
left to right direction
actor Profesor
package "Sistema Académico" {
    usecase "Introducir Datos Académicos" as IntroducirDatosAcademicos
    usecase "Consultar Datos Personales" as ConsultarValores
    usecase "Consultar Asignación Docente" as ConsultarAsignaciones
}
Profesor --> IntroducirDatosAcademicos
Profesor --> ConsultarValores
Profesor --> ConsultarAsignaciones
@enduml