@startuml manejoAuditoria
left to right direction
actor "Usuario" as Usuario
actor "Administrador General" as AdminGeneral

package "Manejo Auditorias" {
    usecase "Ver Auditoria" as CA1
    usecase "Descargar Informe de Audítoria" as CA2
}

AdminGeneral --|> Usuario
Usuario --> CA1
Usuario --> CA2
Usuario --> CA3
@enduml     