@startuml
title Casos de Uso: Crear Capacitación

actor Administrador

folder "Gestión de Capacitación" as Capacitacion {
    Administrador --> (Crear capacitación)
}

note right of (Crear capacitación)
    Permite al administrador registrar
    nuevos programas de capacitación en
    el sistema, incluyendo sus detalles.
end note
@enduml
