@startuml

title Actualizar Profesor

start
:El usuario solicita introducir cambios en un profesor;
:El sistema permite introducir los datos del profesor a modificar;
:El usuario introduce los nuevos datos del profesor;
if (¿Datos válidos?) then (Sí)
:El sistema permite guardar los cambios;
:El sistema actualiza el profesor con la nueva información;
:El sistema presenta una confirmación: "Profesor actualizado correctamente";
else (No)
:El sistema presenta un mensaje de error: "Los datos introducidos no son válidos";
:El sistema permite introducir nuevamente los datos;
endif
stop

@enduml